### ISSUE TITLE
Dark Mode for React Application using Context API and Hooks

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1001]
## Brief Summary

In this tutorial, we will be going over how to implement Dark Mode for a React Application using the `useContext` and `useReducer` hooks. This tutorial will also explain when to use these hooks to manage state instead of something like Redux.

## Key Takeaways

- Project Structure
- How to use `useContext` and `useReducer` Hooks.
- Concepts about global state management.
- When to use these hooks instead of Redux.

**Comment by ninjaginja** [comment]
cool topic @zolomohan - approved
