### ISSUE TITLE
Getting started with Android UI Layouts. 

### ISSUE THREAD

**Issue by BrianaNzivu** [section-io/engineering-education#1003]
### Brief Summary: 
Layouts are the backbone of UI when it comes to Android development. One cannot design an application without using one or two layouts and that is why most Android developers are taught how to use most if not all layouts during their course. This article will cover types of layouts, their uses, and how to implement them in Android applications.

### Key Takeaways: 
1. Understand what a layout is and its importance in mobile development.
2. Learn different types of layouts and how to use & implement them in an application.
3. Be able to implement a few if not all the layout in Android applications.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @BrianaNzivu - approved. Just one suggestion, the title is a bit generic and doesn't really speak to what the user can expect to takeaway from the content. I'd advise being more specific, e.g. 'How to...', 'Getting started with...', 'Implementing...'

**Comment by BrianaNzivu** [comment]
Sure... Let me change it ASAP @ninjaginja .

**Comment by ninjaginja** [comment]
great, thank you!
