### ISSUE TITLE
5 Real Life Use Cases of 5G Ultra-Reliable Low-Latency Communication (URLLC) 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#1004]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

URLLC is one of the three facets of 5G, alongside MMTC (Massive Machine Type Communication) and eMBB (enhanced Mobile Broadband). In particular, URLLC features two parts; ultra-reliability, which constitutes network reliability of beyond 99.999%, coupled with very low latency for packet transmission. This article discusses real-life use cases of 5G URLLC.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is 5G URLLC?
2. Application of 5G URLLC in:

 

- Smart Factory/Industrial Automation
- Healthcare industry
- Intelligent transportation
- Entertainment 
- Smart Electricity grid and harbor automation

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
