### ISSUE TITLE
PyTorch vs TensorFlow for Deep Learning 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#1008]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

PyTorch and TensorFlow lead the list of the most popular frameworks in deep learning. Given its pythonic nature, PyTorch fits smoothly into the Python machine learning ecosystem. The high-level Keras API for TensorFlow in Python has proven so successful with deep learning practitioners that the newest TensorFlow version integrates it by default. This comparison of TensorFlow vs. PyTorch will provide readers with knowledge about the top Deep Learning Frameworks and help them find the most suitable one.  
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. An Overview of PyTorch 
2. An Overview of TensorFlow
3. A Comparison in terms of:

- Graph Definition
- Integration
- Visualization
- Deployment
- Serialization
- Speed

4. Which Library to use for Deep Learning 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
This topic is already being covered in #965
