### ISSUE TITLE
NPM vs NPX

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#1011]
### Brief Summary: 

NPM is the package manager bundled with Node.js. It provides a way for developers to install packages both globally and locally. NPM doesn’t run any packages. If you want to run a package using NPM, you must specify that package in your package.json file. Npx the package runner pre-bundled with NPM. Typically used to download and run a package temporarily or for trials. It provides a clear and easy way of executing packages, commands, modules, and even GitHub gists and repositories. Executes packages that are not previously installed based executable that you would normally install via NPM.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

NPM the package manager
Npx the package runner
Using NPM.
Using npx.
Executing packages.
Run code from GitHub using npx.
Shell auto fallback.
### References: 
https://www.NPMjs.com/package/npx
https://docs.NPMjs.com/packages-and-modules

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
