### ISSUE TITLE
Topic Suggestion-What Is TCP/IP?

### ISSUE THREAD

**Issue by soaspro** [section-io/engineering-education#1013]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
-This article will be about what TCP and IP and how they work when a user connects to a web server for example. It's important to know this for troubleshooting an internet connection or as a reference for brushing up on previous knowledge.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
-Understand how data travels through the internet
-Know the basic communication of the web
-Know the key differences between TCP and IP
-Have an important topic added to their skillset

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
-Internet search, books, although not sure which links or articles exactly yet.

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @soaspro, however this concept has already been covered in [this article](https://www.section.io/engineering-education/tcp-node/). Please feel free to suggest a different topic area to explore.
