### ISSUE TITLE
Getting started with Constraint view group design in Android

### ISSUE THREAD

**Issue by Ericgacoki** [section-io/engineering-education#1017]
### Brief Summary: 

Over the past few years, Android has undergone a lot of improvements.  As an android developer, learning newly released technologies enable you to create powerful, lightweight, and modern applications. Constraint view group, also called constraint view alignment, is one of the newest skills that you need to arrange views and widgets on the screen the best way.

### Key Takeaways: 

By the end of this tutorial the learner should be able to;

1. Implement the concepts of chained alignment of views in a view group
2. Create a parent-child view group relationship
3. Design a responsive user interface - one that fits all devices screen sizes 
4. Generate a data binding object for referencing views within the view group

### References: 

N/A

**Comment by ninjaginja** [comment]
good topic @Ericgacoki - approved
