### ISSUE TITLE
Creating and connecting Maria Database to a PHP registration form

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-io/engineering-education#1018]
### Brief Summary: 
The database is a set of clear data stored in a computer. It is used to store information that is very important to an organization. it can hold one or more tables.  In PHP Mysql query_function is used to create a MySQL database. MySQL is the most popular database system used with PHP.

### Key Takeaways: 
After reading this article the reader should be able to:
1. install Xampp
2. create tables in the database using SQL commands
3. store data in a database
4. fetch the stored data from the database and display them on a website
5. create a registration form using bootstrap and CSS

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @Erastuskanyatta - approved

**Comment by Erastuskanyatta** [comment]
@ninjaginja

**Comment by ninjaginja** [comment]
@Erastuskanyatta were you requesting my attention on something here?

**Comment by Erastuskanyatta** [comment]
Yes, @ninjaginja I just wanted to know the progress of my PR.

**Comment by ninjaginja** [comment]
As @hectorkambow noted in the linked PR, your article is currently in our review queue. Our (small) team of reviewers is working through the PR backlog as quickly as possible and will get to your article as soon as they can. You'll receive updates once the review has started. Thank you for your patience.

**Comment by Erastuskanyatta** [comment]
@ninjaginja thankyou for the updates.
