### ISSUE TITLE
Effect of Ensemble Learning on Bias and Variance

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#1022]
### Brief Summary: 

In a previous [article](/engineering-education/ensemble-learning/) we covered ensemble learning and how it improves machine learning. We mentioned that it reduces the errors of bias and variance. These errors have an impact on the performance of a machine learning model. It is preferable to have low bias and variance. In this article, we dissect the two errors and the effect of ensemble learning on them. 

### Key Takeaways: 

Reader should:
1. Get an overview of bias and variance errors
2. Learn the relationship between bias, variance, and ensemble learning.
3. Understand how ensemble methods affect/reduce bias and variance

### References: 

https://medium.com/ml-research-lab/ensemble-learning-relation-with-bias-and-variance-431cdc0a3fc9

https://www.researchgate.net/publication/315067126_A_bias-variance_analysis_of_ensemble_learning_for_classification

https://machinelearningmastery.com/gentle-introduction-to-the-bias-variance-trade-off-in-machine-learning/

https://www.geeksforgeeks.org/ml-bias-variance-trade-off/?ref=rp

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
