### ISSUE TITLE
Hypothesis Testing in Data Science

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#1023]
### Brief Summary: 

In machine learning, we need to be able to trust our models and the predictions they make. We may use sample data to train our models. This sample data may make certain assumptions about a population. But if we have no way to test whether the assumptions represent a whole population or not, we struggle to tell if our results are due to statistical significance or just by chance. This article explores the steps to test out hypotheses. 

### Key Takeaways: 

Reader should:
1. Understand the significance of hypotheses
2. Compare hypotheses in machine learning versus statistics
3. Learn how to test a hypothesis using 5 key steps

### References: 

https://towardsdatascience.com/hypothesis-testing-in-data-science-875e9d24785e

https://machinelearningmastery.com/what-is-a-hypothesis-in-machine-learning/#:~:text=A%20scientific%20hypothesis%20is%20a%20provisional%20explanation%20for,a%20target%20function%20for%20mapping%20inputs%20to%20outputs.

https://www.geeksforgeeks.org/ml-understanding-hypothesis/

https://www.datacamp.com/community/tutorials/hypothesis-testing-machine-learning

https://www.edugrad.com/tutorials/maths-for-machine-learning/56

https://medium.com/dataseries/hypothesis-testing-in-machine-learning-what-for-and-why-ad6ddf3d7af2

https://www.datasciencecentral.com/profiles/blogs/importance-of-hypothesis-testing-in-quality-management

https://sciencing.com/the-importance-of-hypothesis-testing-12750921.html

**Comment by ninjaginja** [comment]
@collins-a I noticed you have several open issues that are still awaiting PR submissions. Please work through some of those outstanding drafts before suggesting new topics. This helps us expedite reviews/payouts for everyone. I'm going to close this issue until you've worked through open issues, then you can request this issue to be reopened when ready. Thanks!

**Comment by collins-a** [comment]
@ninjaginja noted and thank you. I have them ready actually. Just some minor editing and then submission between today and tomorrow. Confident I'll be reopening this tomorrow

**Comment by collins-a** [comment]
Hello @ninjaginja, I've worked on a number of open issues, except the one I suggested a couple of days ago. Just a request to reopen this issue so that I may work on the two over the next week!
