### ISSUE TITLE
Web sockets with Node and socket.io

### ISSUE THREAD

**Issue by Larry-Mason** [section-io/engineering-education#1028]
### Brief Summary: 
Node is a JavaScript runtime for building server side applications with JavaScript language. WebSocket is a computer communications protocol, providing full-duplex communication channels over a single TCP connection.We shall use Node and socket.io to learn and build a simple server that uses this technology.

### Key Takeaways: 
1. Basics of web sockets
2. Learn how to use socket.io
3. Build a simple JavaScript interface to establish connections

### References: 
 N/A

**Comment by ninjaginja** [comment]
@Larry-Mason Could you please review this [previously published article](https://www.section.io/engineering-education/understanding-socket/) to ensure that there's not too much overlap in the content that you're suggesting for this article? If there is duplication, then please select a different topic to explore.

**Comment by ReactifyStudio** [comment]
The content might overlap. I see, please close the issue.
