### ISSUE TITLE
Uploading multi-part form data using Node.js and the Multer.

### ISSUE THREAD

**Issue by sardug10** [section-io/engineering-education#1035]
### Brief Summary: 
Multer is an npm package that is used as a middleware for uploading multipart/form-data. I will be writing this article as a step-by-step tutorial on how to upload PDF files from client-side to server-side with the help of the Multer package. Also, how to view those files on the front-end of a website.

### Key Takeaways: 
1) How to design an API endpoint for posting data.
2) How to use Multer as a middleware for that API.
3) How to manage and store those files on the server-side.
4) How to view those files on the Frontend.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @sardug10 - approved
