### ISSUE TITLE
How Artificial Intelligence has transformed the sports industry

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#1040]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

For a very long time in the sports industry, the human body has been the main protagonist. Today, technoscience has taken a major role and has become instrumental, thereby transforming the sports industry.  
This article critically outlines the applications, advantages, and disadvantages of artificial intelligence in the sports industry.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	Understanding technology framework in the sports industry.
2.	Applications of artificial intelligence in the sports industry.
3.	Advantages of using artificial intelligence in sports.
4.	Challenges of using artificial intelligence in sports.
5.	Areas that need consideration before introducing Artificial Intelligence. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
very cool topic @Pius1991  - approved
