### ISSUE TITLE
Deploying your wordpress to AWS Lightsail

### ISSUE THREAD

**Issue by Aju100** [section-io/engineering-education#1041]
### Brief Summary: 
Learned about the importance of modern cloud computing and the overall service of AWS (Lightsail). In-depth knowledge of configuring WordPress in the production environment and knows how to scale it.

### Key Takeaways: 
-  Deploy WordPress using AWS Lightsail and know about its pricing
- Learned about DNS and nameservers configuration and hosting plan
- Learned about how to create back up for WordPress in AWS
- Learned about how the metrics works and know how to monitor it

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Aju100. This borders on competitive technology to Section, and we prefer to not spotlight competitive tech. Could you please select a different topic area to explore? Thank you.

**Comment by Aju100** [comment]
yeah sure. Can you please look through my new topics? #1055
