### ISSUE TITLE
How to create CRUD API in Python Flask

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#1042]
### Brief Summary: 
[Flask](https://flask.palletsprojects.com/en/1.1.x/) is a micro web framework written in [Python](https://www.python.org/). It is classified as a micro-framework because it does not require particular tools or libraries. In this tutorial I will be using [SQLAlchemy](https://www.sqlalchemy.org/) as the Object Relational Mapper to abstract away the database layer. This article aims to teach the reader how to create various CRUD APIs using Flask and SQLAlchemy.

### Key Takeaways: 
Basic Python knowledge is required to understand the concept covered in this article.
1. What is Flask and SQLAlchemy.
2. Basics of Flask and SQLAlchemy.
3. How to create CRUD API using Flask.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
1. [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/13/orm/examples.html)
2. [Flask documentation](https://flask.palletsprojects.com/en/1.1.x/)

**Comment by ninjaginja** [comment]
good topic @paulodhiambo. I see that some basics on this topic were previously covered in [this article](https://www.section.io/engineering-education/node-vs-python/), but I think a more extensive article would provide a lot of value for developers.

**Comment by paulodhiambo** [comment]
Hello @ninjaginja in the article I will be explaining beyond the basics show in the already published article.
