### ISSUE TITLE
What is 5G?

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#1044]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

5G is the 5th generation mobile network. It is a new global wireless standard after 1G, 2G, 3G, and 4G networks. 5G enables a new kind of network that is designed to connect virtually everyone and everything together including machines, objects, and devices.
In this article, we'll be expounding on that introduction and understanding why we use 5G.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, you will be able to understand:

1. Understanding the history of the previous generations of mobile networks, i.e., 1G, 2G, 3G, 4G
2. What is 5G?
3. How 5G works
4. Applications of 5G

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Bayler, however this topic has already been covered in a [previously published article](https://www.section.io/engineering-education/wireless-mobile-networking/). Please select a different topic area to explore. Thank you.
