### ISSUE TITLE
How to consume data from an API using react

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#1046]
### Brief Summary: 

React is a popular framework for building front-end user interfaces. It is used by many companies and developers. However, for one to be more productive, they should understand how to make requests and receive data from APIs. 

### Key Takeaways: 
 - Understand API structure and JSON data.
 -  Know how to consume data with react.
 - Debug any errors that may occur.

### References: 

N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE - approved
