### ISSUE TITLE
How to Generate Random Numbers

### ISSUE THREAD

**Issue by botahamec** [section-io/engineering-education#1049]
### Brief Summary: 
The article will talk about various random number generators. It will explain how each one works. Some Python implementations will be shown.

### Key Takeaways: 
1. What pseudo-random means
2. The ways computers can create random numbers (real-world events vs algorithms)
3. The pros and cons of different random number generators

### References: 
https://www.iro.umontreal.ca/~lecuyer/myftp/papers/xorshift.pdf
https://en.wikipedia.org/wiki/Xorshift
https://www.youtube.com/watch?v=Qq8ZRWkhovs
https://www.kernel.org
https://www.random.org
http://www0.cs.ucl.ac.uk/staff/d.jones/GoodPracticeRNG.pdf

**Comment by ninjaginja** [comment]
good topic @botahamec - approved. Just one small note, if you're focusing in on Python for examples, then the title should incorporate that - 'How to Generate Random Numbers in Python'.
