### ISSUE TITLE
How AI predicted the coronavirus outbreak

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#1050]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

BlueDot, a Canadian company built an early warning system back in 2013 for the detection of infectious diseases across the globe. On 31st of December 2019, they sent an warning about a contagious infectious disease in Wuhan. This was nine days before the World Health Organisation made an official report. 

In this article we will understand the details about BlueDot and how their software was able to detect the emergence of the virus.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of the article, the reader should be able to understand:

1. Introducing BlueDot
2. How their prediction software worked
3. Leveraging AI for early disease detection

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. [Anticipating the international spread of Zika virus from Brazil](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(16)00080-5/fulltext/) by Isaac I Bogoch, Oliver J Brady, Moritz U G Kraemer,Matthew German, Marisa I Creatore, and Manisha A Kulkarni.
2. [Pneumonia of unknown aetiology in Wuhan, China: potential for international spread via commercial air travel](https://pubmed.ncbi.nlm.nih.gov/31943059/) by Isaac I Bogoch, Alexander Watts, Andrea Thomas-Bachli, Carmen Huber, Moritz U G Kraemer, and Kamran Khan in the Journal of Travel Medicine.

**Comment by ninjaginja** [comment]
cool topic @Bayler - approved
