### ISSUE TITLE
Promises and asyn or wait in JavaScript

### ISSUE THREAD

**Issue by Mwars56** [section-io/engineering-education#1053]
### Brief Summary:
As a programmer sometimes teaching yourself JavaScript is so hard. In this tutorial, we will learn what are promises and async/wait using simple examples. This will make the learner advance in programming skills.
### Key Takeaways: 
Important things the reader should understand or be able to do after reading this article.
1. Understand how promises work.
2. Be able to enhance promises by adding async/wait.
3. Be able to write and run programs using promises and async in JavaScript.
### References: 
N/A.

**Comment by ninjaginja** [comment]
@Mwars56 Thanks for the topic suggestion. We actually already have an article in the works for this, just awaiting a PR on #536. Could you please select a different topic area to explore?
