### ISSUE TITLE
Object Oriented programming concepts in Kotlin

### ISSUE THREAD

**Issue by jumapaul** [section-io/engineering-education#1060]
### Brief Summary: 
Kotlin is a cross-platform, statically typed, general-purpose programming language with type inference.  In the article, I will explain and give examples of the various object-oriented programming concepts. At the end of the article, we will be a simple application that demonstrates the use of various concepts covered in the article.

### Key Takeaways:  
The reader should have basic programming knowledge. No prior Kotlin knowledge is needed to understand the various concepts that will be in the article.
1. Kotlin Classes and objects.
2. Kotlin visibility modifiers.
3. Kotlin abstract classes and interfaces.
4. Kotlin Sealed classes and extension functions.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
[Kotlin documentation](https://kotlinlang.org/docs/reference/classes.html)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @jumapaul, however I believe this content is already being covered in this article - #901. Could you please select a different subject matter to explore? Thank you.

**Comment by jumapaul** [comment]
Noted. Thank you
