### ISSUE TITLE
Understanding the Internet of Things (IoT) in the healthcare industry

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#1063]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Internet of Things (IoT) has been of great help in the healthcare industry. It has been used overtime widely, and as technology evolves, its applications are increasing.
This article will outline the basics of IoT, the benefits, and the challenges paused by the IoT technology in the healthcare industry.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	How IoT is applied in the healthcare industry.
2.	What are the benefits of IoT in the healthcare industry?
3.	What are the challenges of IoT in the healthcare industry?
4.	Emerging trends and future of IoT in the healthcare industry.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Pius1991, but this topic is far broader than we prefer for article contributions. We're really looking for content that takes a practitioner's approach to addressing specific challenges that engineers face. Please take a look at the list of published articles and approved topics for guidance and select a different topic area to explore. Thank you.
