### ISSUE TITLE
Batch Processing vs Stream Processing

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#1064]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Many organizations leverage big data and cloud technologies to improve the traditional IT infrastructure and support data-driven culture and decision-making while modernizing data centers.
Cloud computing is nothing less than a revolutionary shift in the data analytics industry, and cloud-based technologies are the key to ensure a sophisticated data management structure. But the challenge is how to get data processed faster. Batch processing or stream processing are the two primary ways of processing data faster.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. An overview of Batch Processing 
2. An overview of Stream Processing
3. Batch Processing and Stream Processing pros and cons
4. Use cases of both Batch Processing and Stream Processing

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
