### ISSUE TITLE
Implementing Localisation in Laravel

### ISSUE THREAD

**Issue by jumamiller** [section-io/engineering-education#1066]
### Brief Summary: 
At the end of this article, the learner will be able to write laravel projects that are standardized to use different languages depending on the user's choice of language.
### Key Takeaways: 
1.Introduction to Localisation in Laravel.
2.Configuring locale.
3.Translation Strings.
4.Overriding package language files
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @jumamiller - approved. You may consider adding 'language' into the title (e.g. 'Implementing Language Localization in Laravel')... If I think about how somebody might seek out this content, it seems that 'language' might be a keyword that's worth including.
