### ISSUE TITLE
Implementing Shimmer Loading Effect in Android Studio

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#1069]
### Brief Summary: 
[Shimmer](https://facebook.github.io/shimmer-android/) is an Android library that implements a shimmer loading effect (Skeleton Screen Loading) when fetching data from a server. Facebook developed it to show loading animation while loading data from API or the Local Database. It implements the same concept as you would do with loading or a progress dialog. Many big corporates such as YouTube, Linkedin, Google Drive and Facebook have implemented the shimmer loading effect, just to name a few.
![shimmer-loading-effect](https://user-images.githubusercontent.com/36155624/103098278-41fb9480-461b-11eb-9fc7-ad181cc96027.gif)

### Key Takeaways: 

This guide will discuss how to implement the loading effect using android studio using live data. We will use HTTP request libraries such as [volley](https://www.section.io/engineering-education/making-api-requests-using-volley-android/) or [retrofit](https://github.com/section-io/engineering-education/pull/989) to load data from the internet and display it the app page while implementing the shimmer loading effect. The guide will not focus on the volley or retrofit section have more information about them. The guide will focus on shimmer effects.

### References: 
https://facebook.github.io/shimmer-android/

**Comment by ninjaginja** [comment]
cool topic @kimkimani - approved.
