### ISSUE TITLE
How to use intersection observer by building a simple image lazy loading website

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#1079]
### Brief Summary: 
The Intersection Observer API provides a way to asynchronously observe changes in the intersection of a target element with an ancestor element or with a top-level document's viewport. In this article I will discuss intersection observer web API by building a simple app that lazy loads images.

### Key Takeaways: 
1. Understanding the intersection observer API
2. Building a simple app using this API
3. Learn to improve performance and best practices using intersection observer
### References: 
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio - approved.
