### ISSUE TITLE
Article Error: Static Site to Node.js Syntax Error

### ISSUE THREAD

**Issue by ninjaginja** [section-io/engineering-education#1086]
@louisefindlay23 we received an email from somebody referencing one of your published articles, alerting us to a potential syntax error:

> Dear Team
>I’ve been going through your tutorial for the NODE -EJS server at the url-
>https://www.section.io/engineering-education/static-site-dynamic-nodejs-web-app/
>I found a mistake at the line which is : “<% include('../partials/header') %>.”
>Please correct this to
>“<-% include('../partials/header') %>.”
>CORRECTION: you missed the HYPHEN after opening tag (<).

In looking at the EJS docs, it appears to me that there is a hyphen missing, but the placement should be after the '%'. Could you please take a look and confirm the correct syntax? You can either open a PR to correct the article, or I'm happy to make the correction from our end once I receive confirmation on the correct syntax.

Thanks,
Molly

**Comment by louisefindlay23** [comment]
Sure, @ninjaginja. Can confirm it should be `<%-` as you thought. Will open a PR shortly.

**Comment by ninjaginja** [comment]
Excellent! Thanks for the quick follow-up 👍
