### ISSUE TITLE
Introduction to Dynamic Programming

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#1088]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Dynamic programming is a complex algorithmic technique feared by many computer science engineers and is commonly asked in coding interviews. In this tutorial, I am going to make it easy to understand by solving problems based on dynamic programming. This tutorial will be the successor to the article on recursion. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand the limitations of recursion 
2. Understand what Dynamic programming and how it overcomes the problems of recursion
3. Understand how to solve problems using DP

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @adithbharadwaj - approved
