### ISSUE TITLE
Functional Programming with Haskell

### ISSUE THREAD

**Issue by nimra200** [section-io/engineering-education#1093]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
This article introduces Haskell, which is a functional programming language. Characteristics that make Haskell unique will be discussed. There will be some examples to get the reader to solve a few basic problems with functional programming.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Ability to define the difference between functional and imperative programming. 
2. Write basic functions involving lists and tuples in Haskell. 
3. Understand why Haskell is famous for "lazy" computations and how it affects function argument evaluation.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
Learn You a Haskell for Greater Good (available at http://learnyouahaskell.com/)

**Comment by ninjaginja** [comment]
good topic @nimra200 - approved
