### ISSUE TITLE
Node.js vs. Django

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#1096]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Node.js and Django are technologies used in building versatile web and mobile applications. They have a large number of users, and both have a vast web community. They are both essential in developing web applications, and they are unique in their ways. 
The article will draw detailed comparisons of the two technologies, which will help the reader decide which one to use depending on the project needs. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.	In-depth comparisons between Node.js and Django. A comparison between the two in programming, architecture, security, templates and documentation, customization, scalability, performance, tools, etcetera. 
2.	Enumerate the advantages and disadvantages of using Node.js.
3.	Enumerate the advantages and disadvantages of using Django. 
4.	Types of apps that work well on each. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Pius1991 - approved. Please be mindful of grammar and word selection when drafting your article. For example, in your description, you mention, "They are both essential in developing web applications." The word choice of 'essential' would make it seem that these technologies are required, whereas they are two of many choices.

**Comment by Pius1991** [comment]
@ninjaginja thank you madam, sure I will
