### ISSUE TITLE
How to create a password strength checker using JavaScript Regex

### ISSUE THREAD

**Issue by Agusioma** [section-io/engineering-education#1097]
### Brief Summary: 
We will discuss how to check the strength of  a password a user enters basing on if the password:</br>
- Is at least 8 characters long
- Has at least one uppercase letter
- Has at least one lowercase letter
- Has at least one digit
- Has at least one special character

### Key Takeaways: 
At the end, the reader should:
- Have a basic understanding of the JavaScript Regular Expressions(**Regex**)
- Compare and check strings using the Regex
- Check a password's strength

### References: 
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

**Comment by ninjaginja** [comment]
good topic @Agusioma - approved
