### ISSUE TITLE
Guide for installation of NodeMCU using Arduino IDE

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#1100]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

In this article, we will cover step-by-step guide for the installation of NodeMCU ESP2866 using Ardunio IDE. Setting up the right configurations and installation of drivers will also be covered.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader will be able to install Ardunio IDE for working with NodeMCU
- The reader will go through various configuration setups.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

- https://www.arduino.cc/en/software
- https://dzone.com/articles/programming-the-esp8266-with-the-arduino-ide-in-3

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @srishilesh, however this subject matter is more hardware-focused than we prefer. We're looking for content that dives into web technologies. Please take guidance from previously published articles and approved topics, and select a different topic area to explore. Thank you.
