### ISSUE TITLE
How to containerize Django application using Docker

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#1101]
### Brief Summary: 
[Docker](https://docs.docker.com/get-started/overview/), an open-source project launched in 2013, has helped popularize technology and has helped drive the trend towards containerization and micro-services in software development that’s known as cloud-native development. In the article I will be explaining how to containerize the Todo application that was created in [this](https://www.section.io/engineering-education/django-crud-api/) article using Docker and push the Docker container to [Docker hub](https://hub.docker.com/).

### Key Takeaways: 
1. What is Docker.
2. What is Dockerfile and how to create it.
3. Creating Docker container from Dockerfile.
4. Pushing Docker container to the Docker hub.
### References: 
[Understanding Docker concepts](https://www.section.io/engineering-education/docker-concepts/)
[Getting started with Docker](https://www.section.io/engineering-education/getting-started-with-docker/)

**Comment by ninjaginja** [comment]
great topic @paulodhiambo - approved 👍
