### ISSUE TITLE
How to create an animated counter in JavaScript

### ISSUE THREAD

**Issue by Agusioma** [section-io/engineering-education#1107]
### Brief Summary: 
We will learn to create an animated counter for a webpage using JavaScript

### Key Takeaways: 
At the end, the reader will learn about:
- The Animation Frame in JavaScript
- Timestamps and their use in counters
- How the `Math.min` and `Math.floor` methods are also used in counters

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Agusioma. Just one question for clarification - what do you mean when you say, "for a webpage, mostly landing pages"?

**Comment by Agusioma** [comment]
@ninjaginja I meant the counters could be used in the page which site visitors first get into then it gives them a brief description.</br>In a case where there are 543 people registered to the site, the number could be animated using JavaScript.</br>Nevertheless, I have removed the clause.</br>
Thank you

**Comment by ninjaginja** [comment]
Ah, ok. I was a bit confused by the difference between a webpage and a landing page, and I think others might be too. I'd suggest that if you intend to describe the usage, you do so with descriptive language rather than terms that might have different meaning to readers. Thank you.

**Comment by Agusioma** [comment]
Noted. Thank you.
