### ISSUE TITLE
Introduction to InfluxDB

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#1114]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Time-series databases are very popular for data analytics and visualization. In this tutorial, I will explore the basics of time-series databases and where they can be used. I will also cover the basics of InfluxDB, how to set it up and get it running on your local system.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand time-series data and time-series databases
2. Understand why and where time-series databases can be used
3. Grasp the basics of InfluxDB
4. Setup InfluxDB and run it on your local system
5. Store some data in the database and execute basic queries

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.influxdata.com/

**Comment by ninjaginja** [comment]
good topic @adithbharadwaj - approved
