### ISSUE TITLE
Text to Speech using Web Speech API in JavaScript

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1127]
## Brief Summary
In this tutorial, we will develop a web application that will convert Text to Speech using the SpeechSynthesis object in the Web Speech API.

## Key Takeaways

- Project Structure
- Learn about Speech Synthesis.
- Develop a simple website to convert Text to Speech.

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved
