### ISSUE TITLE
Popular Machine Learning (ML) Datasets in 2021

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#1129]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

The data that we use to train our models is really important. In this article, we'll tackle the most popularly used datasets, explain what they are and what kind of models we use them for.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

In this article, the reader will be able to understand some of the popular machine learning datasets used today that can improve the reader's machine learning skills. 

Some include of these datasets include:

1. MNIST Dataset
2. Fashion MNIST Dataset
3. CIFAR-10 Dataset
4. Wisconsin Breast Cancer Dataset
5. Iris Dataset

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Bayler - approved
