### ISSUE TITLE
Introduction to Membership Functions and Fuzzy Operations

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#1130]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Fuzzy logic is an interesting tool used for analysis and reasoning. It further helps the design of various control systems. In this article, I build on the earlier article on Fuzzy sets by going deeper into the membership functions and fuzzy operations. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Discuss what membership functions are and their significance through an example.
2. Understand the types of membership functions, along with diagrams.
3. Understand the various operations possible on a fuzzy set.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
