### ISSUE TITLE
How to set up a Reverse Proxy for Apache?

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#1132]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A reverse proxy resides in front of a web server, and its function is to receive all the requests before they reach the origin server.  It works the same as a forward proxy only that the webserver is using the proxy rather than the user or client. Reverse proxies are used to improve performance, security and reliability of the webserver.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

Basics of reverse proxy servers.
How to reverse proxy server’s work?
Benefits of reverse proxy servers.
How can you use proxy servers to speed up and secure the site?
How to setup Apache as a reverse proxy?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Pius1991 - approved. Please note that we already have quite a bit of content on the Section blog around reverse proxies (https://www.section.io/blog/search/?q=reverse%20proxy). Try not to be too repetitive of existing content and instead focus on the tutorial section of how to set up Apache as a reverse proxy. Also, please be mindful of grammar/readability. I noticed some grammatical errors in your description. We request that all articles undergo a thorough grammar/readability check prior to submitting your final draft for review. Thank you.

**Comment by Pius1991** [comment]
@ninjaginja well noted Ma` thank you.
