### ISSUE TITLE
Amazon S3 with Spring Boot

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#1138]
### Brief Summary: 
Amazon Simple Storage Service (Amazon S3) is a service offered by Amazon Web Services that provides object storage through a web service interface. In the article I will be explaining step by step on how to upload and download static files like images and videos to Amazon S3.

### Key Takeaways: 
The Reader should have some knowledge of Spring Boot to fully understand the article.
1. What is Amazon S3.
2. Importance of Amazon S3.
3. Uploading and downloading files from Amazon S3.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @paulodhiambo - approved
