### ISSUE TITLE
Design Patterns in Java

### ISSUE THREAD

**Issue by elkiplangat** [section-io/engineering-education#1139]
### Brief Summary: 
Design patterns are reusable solutions to commonly occurring  problems in software design. In this article I will introduce  common software design patterns while providing some basic examples and use cases.

### Key Takeaways: 
1. What design patterns are 
2. When to use them
3. How to implement some common design patterns in java

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @elkiplangat - approved. I just one minor suggestion for the title. It would be more impactful to include some wording around what the user can expect to takeaway from the article, e.g. "How to...", "Understanding...", "Breaking Down..."
