### ISSUE TITLE
Surveillance - Theft Detection using Arduino 

### ISSUE THREAD

**Issue by PraisySam** [section-io/engineering-education#1150]
### Brief Summary: 
This article will provide support to build security and the surveillance function
anywhere, like the Museums, Bank vaults, high secure areas, microbiology
centers, data centers, etc using Arduino circuit.

### Features
It can identify possible theft attempts made either by trying to melt the vault. But, even
before that, the circuit can identify such possibilities when the Excess of luminosity is
observed in the surroundings.
The next level of security is provided by the motion sensors which can sense for any
motion within the restricted.

### Key Takeaways: 
Circuit designing 
Learn how to interface Arduino with different sensors and LCD using C Programming
Online platform-Tinkercad utility

### References: 
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @PraisySam, however this is a bit outside of our preferred topic areas, as it leans more into the hardware space. We're really interested in featuring content that centers around web technologies. Please take a look at previously published articles and approved topics and suggest a different topic to explore. Thank you.
