### ISSUE TITLE
Constraint-Satisfaction Problems with MiniZinc+Geocode (tutorial)

### ISSUE THREAD

**Issue by nicholaskross** [section-io/engineering-education#1151]
### Brief Summary: 
Constraint-Satisfaction Problems (CSPs) represent problems in terms of variables, their possible values, and constraints on those values. Many problems, from graph-theory to type inference to puzzle-solving, are easily converted into CSPs. In this tutorial, we will use MiniZinc, a programming language built for CSPs, and Geocode, a CSP solver, to model and solve a simple graph-coloring problem.

### Key Takeaways: 
- Understand what a Constraint-Satisfaction Problem is
- Identify problems that lend themselves well to CSP solutions
- Model a CSP in MiniZinc
- Use Geocode to solve the MiniZinc CSP

### References: 
- https://www.cs.upc.edu/~erodri/webpage/cps/theory/cp/intro/slides.pdf
- https://www.minizinc.org/
- https://www.minizinc.org/doc-2.5.3/en/index.html
- https://cis.temple.edu/~giorgio/cis587/readings/constraints.html

**Comment by ninjaginja** [comment]
great topic @nicholaskross - approved 👍
