### ISSUE TITLE
React Native Firebase Storage for Non-Expo Workflow

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1154]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) to upload Images/Videos to Firebase Storage.

## Key Takeaways

- Set up Firebase Project for Cloud Storage.
- Add a Picker component to select mages/videos or take images/videos using the camera to upload them.
- Upload images/videos to Firebase cloud storage.

**Comment by ninjaginja** [comment]
Thanks for opening a new issue for part 2 of this article.

**Comment by zolomohan** [comment]
@ninjaginja This is approved, right?

**Comment by ninjaginja** [comment]
yes, approved
