### ISSUE TITLE
AlphaFold: AI Breakthrough in Protein Folding

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#1156]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Protein structure prediction can be used to determine the three-dimensional shape of a protein from its amino acid sequence. This problem is of fundamental importance as the structure of a protein largely determines its function. However, protein structures can be difficult to determine experimentally. In this article, we'll show how AlphaFold  was achieve to achieve state-of-the-art results (considered a breakthrough) in predicting 3D shapes of proteins when only the amino acid sequence was given.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

In this article, we'll understand:
1. What is the protein folding problem?
2. Why protein folding is important biology?
3. How AI is used to predict the 3D shape of protein

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. https://www.nature.com/articles/s41586-019-1923-7.epdf?author_access_token=Z_KaZKDqtKzbE7Wd5HtwI9RgN0jAjWel9jnR3ZoTv0MCcgAwHMgRx9mvLjNQdB2TlQQaa7l420UCtGo8vYQ39gg8lFWR9mAZtvsN_1PrccXfIbc6e-tGSgazNL_XdtQzn1PHfy21qdcxV7Pw-k3htw%3D%3D

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Bayler, however this is outside of our preferred topic areas.
