### ISSUE TITLE
Getting Started With Selenium Automation Testing

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1161]
### Brief Summary: 
This article is a continuation of the article ['An Overview on Automation Testing With Selenium'](https://www.section.io/engineering-education/automation-testing-in-selenium/). It aims at taking readers through steps for installing and configuring Selenium web-driver. Readers will get an understanding of how to create and run an automation test in Selenium.

### Key Takeaways: 
1. Introduction
2. Step-by-step guide on how to download and install Selenium web-driver.
3. How to configure Selenium web-driver (with Eclipse)
3. How to create and run the first automation test in Selenium.
4. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved. Once this article has been reviewed/approved/published, please be sure to go back to the first article to add a reference link to the new article.

**Comment by mbaabuones** [comment]
> 
> 
> good topic @mbaabuones - approved. Once this article has been reviewed/approved/published, please be sure to go back to the first article to add a reference link to the new article.

Alright. Thank you.
