### ISSUE TITLE
MOLAP vs ROLAP vs HOLAP in Online Analytical Processing (OLAP)

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1163]
### Brief Summary: 
MOLAP, HOLAP and ROLAP are important terms in data warehousing. They are the main data storage modes in OLAP (online analytical processing). This article aims at providing a comparison of these terminologies. 

### Key Takeaways: 
1. Overview of OLAP
2. comparison of the three main types of OLAP (MOLAP, HOLAP and ROLAP), including the advantages and disadvantages
3. Summary table 
4. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
