### ISSUE TITLE
Theoretical Introduction to Linear Regression

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#1164]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this article, I discuss the theory behind linear regression. Linear regression is one of the most important algorithms used in machine learning to find the line of best fit given a set of data points. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What is linear regression?
2. Methods to derive the line of best-fit
- a. Least-Squares solution: One-shot solution
- b. Using Gradients: Iterative solution
3. Code to implement the least-square solution in Python. 
### References: 
N/A
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @lalith1403  - approved
