### ISSUE TITLE
React Native Firebase Storage for Non-Expo Workflow Part 2

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1169]
## Brief Summary

This is a follow-up tutorial to #1154 (React Native Firebase Storage for Non-Expo Workflow).

In this tutorial, we will continue developing the React Native Firebase Storage application from the previous tutorial by adding new features.

## New Features

- Get the Download URL for the uploaded media.
- Display the upload progress of the file.
- Add Functionality to Pause/ Resume the upload.

**Comment by zolomohan** [comment]
@ninjaginja I can't think of a better title grouping all the 3 new features. Any Suggestions?

**Comment by ninjaginja** [comment]
Can this be incorporated into the previous article? Add-on features don't seem to encapsulate a complete, comprehensive tutorial.

**Comment by zolomohan** [comment]
The article was getting lengthy, that's why I thought I'll break it down. Combining these resulted in around 2000 words. If that's okay, I'll add this to the previous article and not break it down.

**Comment by ninjaginja** [comment]
We always err on the side of complete content vs length, and I think the article would be better suited as a combined piece.

**Comment by zolomohan** [comment]
Got it. I will close this and merge both.
