### ISSUE TITLE
An Overview of Teradata RDBMS

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1186]
### Brief Summary: 
Teradata is an open RDBMS (Relational Database Management System) that can handle massive volumes of data. This article introduces readers to this concept.

### Key Takeaways: 
1. Introduction
2. Importance of Teradata
3. Features of Teradata
4. Teradata components
5. How Teradata works
6. Advantages and disadvantages of Teradata

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
