### ISSUE TITLE
Introduction to C++ operators

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#1197]
### Brief Summary: 
The base of every programming language is operators. Thus, without the use of operators, the C++ programming language functionality is incomplete. Operators can be described as symbols that help us perform specific mathematical and logical operand computations. . C++ language has several types of operators built-in. This article will go through the commonly used operators.

### Key Takeaways: 
1. What is an operator and operand
2. Types of operators
3. How to use operators to perform mathematical and logical computations in a C++ program

### References: 
https://www.geeksforgeeks.org/operators-c-c/

**Comment by ninjaginja** [comment]
good topic @Dawe-7 - approved
