### ISSUE TITLE
Dependency Injection (Dagger-Hilt Android Kotlin)

### ISSUE THREAD

**Issue by stevechacha** [section-io/engineering-education#1201]
### Brief Summary: 

Dagger is one of the most popular and most used libraries for building dependency injection, especially in Android. It's a jetpack library .Dagger-Hilt, it helps us to provide a different set of bindings for different build types,to just take care of where to inject dependencies and rest all of the code generations happens by dagger itself by using annotations and thus removing all the boilerplate code.

### Key Takeaways: 
What is dependency injection and it's used in android
How to perform dependency Injecting into Activities
Providing dependencies that need other dependencies
 How to use dependency Injecting into ViewModels

### References: 
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @stevechacha. While the topic sounds interesting, the grammar and readability of the description and bullet points that you've provided raises some red flags. Are you able to provide a writing sample of 2-3 paragraphs that will help us get a better sense of your English writing aptitude? You can simply post it via comment in this issue. Thank you.

**Comment by stevechacha** [comment]
Brief Summary:
Dagger is one of the most popular and most used libraries for building dependency injection, especially in Android. It's a jetpack library .Dagger-Hilt helps us to provide a different set of bindings for different build types. It also just take care of where to inject dependencies and rest all of the code generations happens by dagger itself by using annotations and thus removing all the boilerplate code.

Key Takeaways:

1. What is dependency injection and it's used in android
2. How to perform dependency Injecting into Activities
3. Providing dependencies that need other dependencies
4. How to use dependency Injecting into ViewModels

References:
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by stevechacha** [comment]
I have rectified the mistake above

**Comment by stevechacha** [comment]
Brief Summary:
Dagger is one of the most popular and most used libraries for building dependency injection, especially in Android. It's a jetpack library .Dagger-Hilt helps us to provide a different set of bindings for different build types. It also just take care of where to inject dependencies and rest all of the code generations happens by dagger itself by using annotations and thus removing all the boilerplate code.

Key Takeaways:

1. What is dependency injection and it's used in android
2. How to perform dependency Injecting into Activities
3. Providing dependencies that need other dependencies
4. How to use dependency Injecting into ViewModels


References:
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by stevechacha** [comment]
rectified @ninjaginja

**Comment by stevechacha** [comment]
Checked  @ninjaginja 
Brief Summary:
Dagger is one of the most popular and most used libraries for building dependency injection, especially in Android. It's a jetpack library .Dagger-Hilt helps us to provide a different set of bindings for different build types. It also just take care of where to inject dependencies and rest all of the code generations happens by dagger itself by using annotations and thus removing all the boilerplate code.

Key Takeaways:

1. What is dependency injection and it's used in android
2. How to perform dependency Injecting into Activities
3. Providing dependencies that need other dependencies
4. How to use dependency Injecting into ViewModels

References:
https://developer.android.com/training/dependency-injection/hilt-android

**Comment by ninjaginja** [comment]
@stevechacha I don't see many changes to the original text, and this is still very rough. We try to curb these types of errors upfront in order to respect the time of our peer reviewers, who do not provide editing services. If you'd like to continue working on this and come back with an extended writing sample that's more polished, please feel free to do so. In the meantime, I'm going to close this issue, and you can request that it be reopened if/when ready. Thank you.

**Comment by stevechacha** [comment]
Brief Summary:
Hilt provides a standard way to incorporate Dagger dependency injection into an Android application.
Key Takeaways:
1. To simplify Dagger-related infrastructure for Android apps.
2. To create a standard set of components and scopes to ease setup, readability/understanding, and code sharing between apps.
3. To provide an easy way to provide different bindings to various build types (e.g. testing, debug, or release).
In this tutorial, you will be able to 
Understanding Dagger, setting up a new project, project Structure, integrating Dagger-Hilt, work manager with Dagger-Hilt

References:
N/A

reopen @ninjaginja

**Comment by stevechacha** [comment]
reopen  @ninjaginja
