### ISSUE TITLE
Data Security and Privacy in Mobile Cloud Computing

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#1204]
### Brief Summary: 
The concept of mobile cloud computing has emerged out of mobile technology and cloud computing. Data security and privacy are critical issues for mobile cloud computing applications. In this article, we will demonstrate the existing threats and attacks on data privacy and security. Also, we will learn data security and privacy solutions in mobile cloud computing.
### Key Takeaways: 
1.  Mobile Cloud Computing.
2.  Data Security and Privacy threats and attacks in mobile cloud computing.
3. Data Security and Privacy solutions for mobile cloud computing

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @JudyNduati, but this is much broader of a topic than we prefer to cover. Are you able to suggest a topic that addresses a specific challenge that developers might be seeking to address?
