### ISSUE TITLE
Image Labeling using Firebase ML in a Non-Expo React Native Application

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1208]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) to label images using Firebase's ML modules. Image labeling gives you insight into the content of images.

## Key Takeaways

- Set up Firebase Project for Image Labeling.
- Add a Picker component to select Images or use the camera to take pictures.
- Use Firebase ML to label images.
- List all the labels made by the ML module.

**Comment by ninjaginja** [comment]
cool topic @zolomohan - approved
