### ISSUE TITLE
Introduction to Database Management System

### ISSUE THREAD

**Issue by carteblanchemunene** [section-io/engineering-education#1209]
### Brief Summary: 
In this article, we will understand how to store and retrieve data effectively using Database Management System. Also, learn how DMS provides proper security measures for protecting data from unauthorized access.

### Key Takeaways: 
1. Differentiating file system and Database Management System
2. Types of Database Management Systems.
3. Application of Database Management System.
4. Users in a Database Management System environment.
5. Database Management System functions.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @carteblanchemunene. This topic is a bit more broad than we typically prefer. We're really looking for content that addresses specific challenges that web engineers face in the modern development environment. Are you able to either dig a little deeper for a more focused angle within this topic, or select a new topic that is more in line with previously published articles and approved topics?
