### ISSUE TITLE
Figma for Web Design: A Beginner’s Guide.

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1212]
### Brief Summary: 
Figma is an interface design tool that consists of powerful and exciting features for web design. This tool provides a collaborative and cost-friendly platform for creating exciting web designs. This article introduces readers to this software and guides them on how to get started.

### Key Takeaways: 
1. What is Figma?
2. Why Figma is important to web designers
3. Getting started with Figma (this includes installation and set up)
4. An overview of Figma user interface
5. Using basic Figma tools. 
6. Conclusion

### References: 
https://www.figma.com/design/

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
