### ISSUE TITLE
Introduction to data structure

### ISSUE THREAD

**Issue by manmusa100** [section-io/engineering-education#1213]
### Brief Summary: In this article, we will understand different classifications of data structure and operation on the data structure. we will also look at the difference between different type of data structure
Describe the what, why, and how of your content idea in 2-5 sentences.

### Key Takeaways: 
1. Classification of data structure.
2.  Primitive and non-primitive data structure.
3. Linear and non-linear data structure.
4. Difference between linear and non-linear data structure.
5. Operation on data structure
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: N/A
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @manmusa100, however this seems to overlap too much with quite a bit of existing content that has already been published on [data structures](https://www.section.io/engineering-education/search/?q=data%20structure). Please select a different topic area to explore. Thank you.
