### ISSUE TITLE
A Beginners Guide to Product Management

### ISSUE THREAD

**Issue by ayfolut** [section-io/engineering-education#1219]
### Brief Summary: 
Product management is a field in technology and for us to come up with great products and manage them properly, we must understand the steps and the processes it entails. In this article, we will learn about all we need to get started in product management.  

### Key Takeaways: 
- The reader would have gained a fundamental knowledge of product management
- The Reader would be able to get started with product management
- The Reader would know the different personas of product management 
- The reader would know the job expectation of a product manager

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ayfolut, however this falls outside of our preferred topic areas. We're really looking for topics that address specific challenges that developers face in the modern web technologies ecosystem. Please take a look at previously published articles and approved topics for guidance and feel free to suggest a different topic. Thank you.
