### ISSUE TITLE
Working with Tweepy : Twitter's Python API

### ISSUE THREAD

**Issue by rahulbanerjee26** [section-io/engineering-education#1223]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Tweepy is Twitter's official library for Python. It can be used to tweet statuses, retweet other's statuses, follow people, get tweets based on keywords etc. The article will introduce the reader to the basics of Tweepy. Additionally, it will also teach the user to build a simple Twitter Bot.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- A basic understanding of the Tweepy Library
- Using Tweepy to Scrape Tweets
- Using Tweepy to automate following, unfollowing users
- Using Tweepy to update statuses and retweet statuses

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
cool topic @rahulbanerjee26 - approved
