### ISSUE TITLE
Create Particle Effects With Particles.js

### ISSUE THREAD

**Issue by shuaiboseni** [section-io/engineering-education#1233]
### Brief Summary:
Particle.js is a javascript library for creating particle effects. It's quite easy to set up and can be useful for creating eye-catching backgrounds without the need for illustrations or photography.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Be able to create background effect with particle.js
2. Be able to form different particle effect
3. Be able to create particle animation

### References: 
'N/A'

**Comment by ninjaginja** [comment]
cool topic @shuaiboseni - approved

**Comment by kimkimani** [comment]
@ninjaginja Check this #421

**Comment by ninjaginja** [comment]
Ah, good catch @kimkimani, thanks for calling attention to this. @shuaiboseni please see the comment in the issue referenced above and select a different topic area to explore. Thank you.

**Comment by shosenwales** [comment]
Oh ok.....thanks, will do
