### ISSUE TITLE
String methods in JavaScript.

### ISSUE THREAD

**Issue by mwangiKibui** [section-io/engineering-education#1243]
### Brief Summary: 
Strings are a core data structure in JavaScript. Strings posses different properties and methods which can be applied to manipulate them in different ways. In this article, we shall discuss how to create strings in JavaScript, various string properties and methods that can be applied to JavaScript strings.

### Key Takeaways: 
- Understand how to create strings in JavaScript.
- Understand how to access properties of strings in JavaScript.
- Understand how to manipulate strings using string methods.

### References: 
https://www.w3schools.com/js/js_strings.asp

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @mwangiKibui, but I'm struggling to understand how this content expands on knowledge that is already available through established documentation. Could you please describe the unique angle that you intend to take with this content?

**Comment by mwangiKibui** [comment]
@ninjaginja I would like to focus on giving a beginner guide. This shall clear any complications in the available documentation.

**Comment by ninjaginja** [comment]
Thank you for the response. I'm still not completely sure what the unique angle is that you'll be presenting. What are some of the 'complications in the available documentation' that you intend to clarify? Could you please be more specific?

**Comment by mwangiKibui** [comment]
@ninjaginja I wish to borrow some time to think through this topic. In the mean time, i would wish issue #1286 is opened so that i can work on it. Thanks.

**Comment by mwangiKibui** [comment]
@ninjaginja After some research i noticed there is not so much to tackle with the previous topic. I therefore decided to look into another topic which i have discussed fully. I look forward to hearing from you soon concerning the new adopted topic. Thanks.
