### ISSUE TITLE
Text Recognition (OCR) using Firebase ML in a Non-Expo React Native Application 

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1247]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) to recognize text from an image using Firebase's ML modules.

## Key Takeaways

- Set up Firebase Project for Text Recognition.
- Add a Picker component to select Images or use the camera to take pictures.
- Use Firebase ML to recognize text from the selected image.
- Display the result in the UI.

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved
