### ISSUE TITLE
Image Segmentation Using Machine Learning

### ISSUE THREAD

**Issue by rohanreddych** [section-io/engineering-education#1248]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

I would like to write about what is image segmentation, algorithms and a tutorial on image segmentation using machine learning using TensorFlow.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

https://arxiv.org/ftp/arxiv/papers/1707/1707.02051.pdf

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @rohanreddych. The description that you've provided is rather brief. Could you please expand upon some of the key takeaways that you intend to provide readers with?
