### ISSUE TITLE
Information Systems Security and Control 

### ISSUE THREAD

**Issue by manmusa100** [section-io/engineering-education#1249]
### Brief Summary: The development, implementation, and maintenance of information systems constitute a large and growing part of the cost of doing business, protecting these resources is a primary concern. In this article, we will understand why we need to keep information systems secure. 
Describe the what, why, and how of your content idea in 2-5 sentences.

### Key Takeaways: 
1. System vulnerability /abuse and why systems are vulnerable.
2. Goals of information security.
3. Creating a controlled environment.
4. General controls.
5. Application controls.

What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: N/A
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @manmusa100, however this proposed topic is much too broad for the type of content that we're seeking. Please select a narrower focus area that addresses a specific challenge that engineers face in the modern development ecosystem. Thank you.
