### ISSUE TITLE
Artificial Intelligence and machine learning trends for 2021

### ISSUE THREAD

**Issue by tambastar** [section-io/engineering-education#1252]
### Brief Summary: 
Learn about current trends in machine learning and artificial intelligence
Machine Learning is the ability for systems to automatically learn and improve from experience without being reprogrammed again.
Artificial intelligence is the way machine to simulate human intelligence and mimic their actions.

### Key Takeaways: 
1. what is machine learning and artificial intelligence
2. current trends of machine learning and artificial intelligence in 2021
3. importance of machine learning and artificial intelligence
4. Application of machine learning and artificial intelligence
5.  challenges in Implementation of machine learning and artificial intelligence

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @tambastar, but this topic is a bit more broad than we like to see. Please select a topic that takes a narrower focus on a specific challenge that developers may face in the modern development ecosystem.

On another note, I've just approved a different topic that you suggested, and we always advise focusing on a single piece of content and seeing that article through the review/publication process before suggesting new topics. This allows us to better expedite reviews/payouts for everyone.
