### ISSUE TITLE
Theoretical Introduction to Convolution

### ISSUE THREAD

**Issue by bloodprashure** [section-io/engineering-education#1256]
### Brief Summary: 
Image classification algorithms are practically impossible to be executed with machine learning models. With deep learning on the rise, convolution has proved to be resourceful and more often than not, people do not understand how convolution works. This article aims to demystify convolution.

### Key Takeaways: 
1. What convolution is
2. How integration plays an important role in convolution
3. The math behind convolution explained

### References: 
N/A

**Comment by ninjaginja** [comment]
@bloodprashure I'm going to temporarily close this issue to allow you to focus on seeing your other topic submission through from start to finish before suggesting a new topic. You may request to reopen this issue once you've submitted a draft of your other article.
