### ISSUE TITLE
Image mapping using  HTML.

### ISSUE THREAD

**Issue by Dyrstiu** [section-io/engineering-education#1260]
### Brief Summary: 

Image mapping is the process of creating an image with clickable areas .The clickable areas act as hyperlinks e.g. to  further information about  the area clicked .
Image maps are useful in websites for example car selling  e-commerce sites  images can be mapped thus different parts form one picture explained
This article will guide the reader on how to use the image tag  together with the map tag to create an image map using HTML.
### Key Takeaways: 
* What is image mapping .
* How to accomplish image mapping using HTML.
* Uses of image mapping in websites.

### References: 
 'N/A'.

**Comment by ninjaginja** [comment]
@Dyrstiu Could you please expand on this topic suggestion by providing a 2-3 paragraph sample of a portion of this article? The description that you've provided raised a couple flags around readability and we'd like to better assess before approving.

**Comment by Dyrstiu** [comment]
Thanks @ninjaginja   for the highlight I will expand on the suggestion and resubmit

**Comment by Dyrstiu** [comment]
@ninjaginja   i have  edited the issue kindly check if it is now readable

**Comment by ninjaginja** [comment]
I'm sorry @Dyrstiu, but significant grammar and readability challenges remain in this description. We do not provide editing services and require that all drafts submitted be polished for correct and readable English grammar. I would advise either working with an editing service (there are many sources online) or one of your peers to polish this up and resubmit when ready.
