### ISSUE TITLE
Keyboard Events in Javascript

### ISSUE THREAD

**Issue by Tsanguu** [section-io/engineering-education#1266]
### Brief Summary: 
This tutorial will discuss how to work with Javascript keyboard events. The three keyboard events are keydown, keypress, and keyup.

### Key Takeaways: 
Introduction to Keyboard Events in Javascript
JavaScript Keyboard Events
Handling Keyboard Events in JavaScript
Keyboard Events in JavaScript Demo
Keyboard Events Browser compatibility

### References: 
https://javascript.info/keyboard-events
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

**Comment by ninjaginja** [comment]
@Tsanguu I see that you have several issues open without drafts submitted. Please work through open content suggestions before suggesting new topics. I'm going to close this for now and you can request that it be reopened when ready. Thank you.
