### ISSUE TITLE
Building a simple RESTAPI with Django Rest Framework

### ISSUE THREAD

**Issue by Anitaachu** [section-io/engineering-education#1267]
### Brief Summary: 
API which is an acronym for **Application Programming Interface,**  is a software interface which allows communication between software and services. We'll be looking at RESTAPI  which is the most popular type of API due to its advantages over other types of APIs. In building the RESTAPI, Django rest framework is the best framework to use because it makes serialization easier. 

### Key Takeaways: 
1. A good understanding of what an API means.
2. RESTAPI CRUD request
3. Basic concept of Django rest framework
4. How to build an RESTAPI with Django rest framework

### References: 
https://www.django-rest-framework.org/
https://djangostars.com/blog/rest-apis-django-development/
https://realpython.com/django-rest-framework-quick-start/

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Anitaachu, however I believe this topic has already been sufficiently covered across several published articles (https://www.section.io/engineering-education/search/?q=django). Please select a different topic area to explore.
