### ISSUE TITLE
Integration Challenges and Solutions in Software Development

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#1274]
### Brief Summary: 
Integration problems remain hidden throught the development process and become visible at the end of the project. Problems that come with integration leads to extra cost, delays, lower project quality, and may cause failure of the project. This article will address integration challenges during software development and solutions.

### Key Takeaways: 
1. Software Integration
2. Importance of software integration.
3. Software Integration challenges
4. Success factors for software integration

### References: 
N/A

**Comment by ninjaginja** [comment]
closing until draft of existing content has been submitted.

**Comment by JudyNduati** [comment]
@ninjaginja, Please re-open this issue
