### ISSUE TITLE
Beginner's guide on github: Pushing a project to github

### ISSUE THREAD

**Issue by Anitaachu** [section-io/engineering-education#1279]
### Brief Summary: 
Github is an open source and version control software that allows developers host their projects and collaborate with other developers. Github has so many amazing features, which helps a team of developers work on their files, whilst working on a single repository, files can be edited, uploaded etc. Github features maybe confusing at first to beginners and the aim of this article is to explain some features in github and how project can be pushed to github.

### Key Takeaways: 
1. Understand basic terms and features in github.
2. How github works.
3. How to push a project to github.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://guides.github.com/activities/hello-world/

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Anitaachu. Could you please elaborate on how this content will differ from what is already readily available through the Github documentation?

**Comment by Anitaachu** [comment]
This content will give a detailed explanation of github concepts such as, fork, clone, pull request etc.

**Comment by ninjaginja** [comment]
Yes, this information is already widely available through the GitHub documentation. We're seeking **unique** content that addresses specific developer challenges, such as application of concepts through a practitioner's approach.
