### ISSUE TITLE
Vision Transformer (ViT): Using Transformers for Image Recognition

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#1299]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Convolutional Neural Networks have revolutionized computer vision in the recent past. On the other hand, transformers are revolutionizing natural language processing be it translation or conversational AI.  How about bringing these two promising fields together and answers this simple question, why not use transformers on images? 

In this article, we'll find out how a potentially revolutionary paper uses transformers to replace convolutional neural networks.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, the reader should be able to:
1. Understand Convolutional Neural Networks and how they've been revolutionary in computer vision
2. How transformers are revolutionizing the field of natural language processing
3. How transformers is used to replace convolutional neural networks in image recognition

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

[An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale](https://openreview.net/pdf?id=YicbFdNTTy)

**Comment by ninjaginja** [comment]
@Bayler I noticed that you have a couple open issues without attached PRs. In an effort to keep our pipelines clean, we're asking that students focus on open issues before suggesting new topics. Once you've submitted drafts for previously suggested topics, you may request to reopen this issue. Thank you.

**Comment by Bayler** [comment]
Hi @ninjaginja I would like to request you to reopen this issue.
