### ISSUE TITLE
Understanding Express middleware

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#1307]
### Brief Summary: 
Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications. One most important concept is how middleware works in the Express framework.
### Key Takeaways: 
1. Understanding what is a middleware in Express
2. Various types of middleware in Express 
3.  How to build an authentication middleware in Express

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ReactifyStudio, however this topic has already been sufficiently covered in this [previously published article](https://www.section.io/engineering-education/express/). Please select a different topic to explore. Thank you.
