### ISSUE TITLE
A Beginners Guide to Next.js Framework

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#1308]
### Brief Summary: 
Next.js is an open-source React front-end development web framework that enables functionality such as server-side rendering and generating static websites for React-based web applications. Next.js gives the best developer experience with all the features needed for production such as hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more with no configurations needed. This is an article that I will be discussing this framework.

### Key Takeaways: 
1. Understanding what is Next.js
2. How to set up a Next.js application
3. The benefits that Next.js introduces in React applications

### References: 
https://nextjs.org/

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @ReactifyStudio. We're asking that students work through their open issues before suggesting new topics. This helps us keep the pipeline clean to expedite review processes. I'm going to close this until you have submitted drafts for open issues and you can request that it be reopened once those drafts have been submitted, and we'll evaluate the topic at that time. Thank you.
