### ISSUE TITLE
Designing API Endpoints

### ISSUE THREAD

**Issue by Anitaachu** [section-io/engineering-education#1321]
### Brief Summary: 
API which is an acronym for Application Programming Interface is a software that allows communication between two applications using requests and responses. These applications (client and server) provide data and can also make changes to the data. 
Endpoints in API are very important, they specify where resources can be accessed by the API.  The performance of an API is dependent on its ability to communicate effectively with API Endpoints . In this tutorial, we'll look at what a good API is and how a good API Endpoint is designed.

### Key Takeaways: 
1. What an API is.
2. A good understanding of CRUD operations.
3. How to design API Endpoint.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
closing until draft has been submitted for other open issue

**Comment by Anitaachu** [comment]
Hello, I have submitted the final draft of the previous article which has also been published. I kindly request for a reopening of this issue. 

Thank you.
