### ISSUE TITLE
What is Identity and Access Management? 

### ISSUE THREAD

**Issue by TevinTurner** [section-io/engineering-education#1331]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
- Identity and Access Management, also referred to as IAM is focused on managing the identity and access privileges of users. This field of Information Technology/Cybersecurity is very important due to the fact that gaining privileged access to certain documents at a particular company gives an individual more control and knowledge of the inner workings of that establishment. If the individual is not authorized to view this documentation, it could lead to potential security breaches, negative publicity, and cause the affected company to gain a bad reputation. The content in my article idea will educate individuals on the importance of Identity and Access Management by providing background history of the topic, how it has been implemented in the field of Information Technology/Cybersecurity, its importance, and the skills needed to enter/succeed in the field. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Three to five of the most important things the reader would understand or be able to do after reading this article are: 
1. Understand what Identity and Access Management is and its importance in the Information Technology/Cybersecurity field. 
2. How to learn the skills required to succeed in or enter the field of Identity and Access Management.
3. The benefits of Identity and Access Management in the workspace and how it can help decrease possible security breaches. 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://www.csoonline.com/article/2120384/what-is-iam-identity-and-access-management-explained.html
- https://searchsecurity.techtarget.com/definition/identity-access-management-IAM-system
- https://www.ibm.com/security/identity-access-management

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion and thorough description @TevinTurner. This topic is a little more broad and abstract than we typically prefer. We're really looking for content that takes a practitioner's approach to addressing specific developer challenges vs defining broad concepts. Please take a look at recently published articles and approved topics and try to come up with a more narrowly focused topic suggestion. Thank you.
