### ISSUE TITLE
Setting up CI/CD for Python Packages using GitHub Actions

### ISSUE THREAD

**Issue by edeediong** [section-io/engineering-education#1345]
### Tutorial Format
- Title — Setting up CI/CD for Python Packages using GitHub Actions
- Introduction
- Prerequisites
- Step 1 — Building a Python Package
- Step 2 — Testing Python Package with GitHub Actions
- Step 3 — Deploying Python Package to PyPI
- Conclusion

**Comment by ninjaginja** [comment]
@edeediong Were you attempting to suggest a new article topic when opening this issue? If so, please follow the appropriate format with description, key takeaways, and references.

**Comment by edeediong** [comment]
Oh alright thank you! I wanted to use the Tutorial Format guide but I'll change that now
