### ISSUE TITLE
Evolution of IoT technologies

### ISSUE THREAD

**Issue by RuthAMare** [section-io/engineering-education#1350]
### Brief Summary: 
The evolution of IoT technologies covers the overview of how IoT has progressively grown to adopt newer technologies. This is generally the emergence of IoT with minimal technologies to when it incorporated newer technologies and the major technologies that have been adopted over time. Finally, the anticipated growth of IoT. 

### Key Takeaways: 
1.Trends in IoT technologies. 
2. Major emerging technologies. 
3. The future of IoT technologies.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @RuthAMare. This topic is far more broad and abstract than we typically prefer. We're really looking for content that takes a practitioner's approach to addressing specific developer challenges vs talking about broad concepts. Please take a look at recently published articles and approved topics and try to come up with a more narrowly focused topic suggestion. Thank you.
