### ISSUE TITLE
Fraud Detection in Banks and Financial Institutions using Machine Learning

### ISSUE THREAD

**Issue by ephnjor2021** [section-io/engineering-education#1352]
### Brief Summary: 
Criminal schemes are now becoming more complicated and sophisticated, to protect the businesses and improve on customer experience, banks and financial institutions are adopting the power of Artificial Intelligence. Applying machine learning to detect fraud enables financial firms to identify genuine transactions from fraudulent ones in real-time, and with great accuracy.

### Key Takeaways: 
In this article the reader will learn: 

- The different types of bank frauds and the impact of each

- Pairing a digital problem with a digital solution

- The reason why machine learning matter

- How to predict fraud with machine learning

- Fraud scenarios and their detection

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @ephnjor2021. This topic is far more broad and abstract than we typically prefer. We're really looking for content that takes a practitioner's approach to addressing specific developer challenges vs talking about broad concepts. Please take a look at recently published articles and approved topics and try to come up with a more narrowly focused topic suggestion. Thank you.
