### ISSUE TITLE
Content Idea Suggestion: Verifying Job Postings for Legitimacy and Honesty

### ISSUE THREAD

**Issue by pkalynan** [section-io/engineering-education#1354]
### Brief Summary: 

Constraints from the global pandemic has been an open gateway for fraud and deceit to steal from innocent vulnerable individuals and groups who need employment via the internet. Things can be elaborate and complex. It is not a secret that fraud has been occurring worldwide before the pandemic; it just may have gotten a bit more sophisticated and advanced because of the missing human-to-human interaction component. This suggestion helps job seekers be safe during their tireless search for employment.

### Key Takeaways: 

Performing research is essential in finding consistencies and inconsistencies to determine legitimacy and honesty. Coding and user-friendly technologies can assist to an extent, however, using a combination of human and technological resources can improve searching for employment. Ensure to include human-to-human interactions to prevent financial loss and personal identity theft.

### References: 

https://www.cnbc.com/2020/10/06/job-scams-have-increased-during-the-covid-19-crisis-how-to-one.html
https://www.forbes.com/sites/ashleystahl/2020/05/11/job-hunting-scams-amid-covid-19-pandemic/?sh=242d83623c57

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @pkalynan, however this is outside of our preferred topic areas. In general, we're looking for original content that takes a practitioner's approach to addressing specific challenges that developers face in the web technologies ecosystem. Please take a look at previously published articles and approved topics to get a better idea of the type of content that we are looking for, and feel free to suggest an alternate topic to explore. Thank you.
