### ISSUE TITLE
Understanding ES6 Destructuring

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#1370]
### Brief Summary: 
JavaScript is a programming language that conforms to the ECMAScript specification. In this article, I am going to discuss one of the JavaScript ES 6 specifications, the destructuring syntax. Including on ways to use it efficiently in our code.

### Key Takeaways: 
1. What is the restructuring syntax
2. How to use the restructuring syntax
3. Using restructuring in objects and arrays

### References: 
https://javascript.info/destructuring-assignment

**Comment by hectorkambow** [comment]
@ReactifyStudio  - topic approved.

**Comment by ReactifyStudio** [comment]
@hectorkambow . It's destructuting and not restructuring as I've mentioned in the take aways. Am ready to continue with this topic 👍

**Comment by kimkimani** [comment]
@hectorkambow @ReactifyStudio I think this topic might be rejected during PR review. The topic seem to be covered elsewhere, https://www.section.io/engineering-education/object-arrays-destructuring/

**Comment by ReactifyStudio** [comment]
Should I close it?

**Comment by ReactifyStudio** [comment]
@kimkimani . But hector approved it. And I'm almost done with the topic. This might dive deeper than the one you're providing.

**Comment by hectorkambow** [comment]
@kimkimani  Great catch - thank you. 
@ReactifyStudio  

Please go over the [first article](https://www.section.io/engineering-education/object-arrays-destructuring/) to see how we can tackle this topic from a different perspective. 

Otherwise - yes I would close it. 👍  

And approach a different topic entirely.

**Comment by ReactifyStudio** [comment]
Sorry true . They collide only that I could have used the destructuting to do the RegEx stuffs. @hectorkambow this already exists.

**Comment by hectorkambow** [comment]
@ReactifyStudio  
It good practice and we always recommend for students to go through our older articles to avoid article overlap  and see where we can expand upon older topics.

**Comment by ReactifyStudio** [comment]
I need to open the using web Contacts API and File system. Hoping you'll approve it so that I get something to write this weekend

**Comment by ReactifyStudio** [comment]
Thanks someone has seen it. I'll open one for file system and contacts
browser APIs. I need one to write this weekend

On Jan 16, 2021 07:02, "hectorkambow" <notifications@github.com> wrote:

@ReactifyStudio <https://github.com/ReactifyStudio>
It good practice and we always recommend for students to go through our
older articles to avoid article overlap and see where we can expand upon
older topics.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/section-io/engineering-education/issues/1370#issuecomment-761348048>,
or unsubscribe

**Comment by hectorkambow** [comment]
I'll close this issue now

**Comment by ReactifyStudio** [comment]
https://github.com/section-io/engineering-education/issues/1379
Requesting for a check as I have nothing to write the entire weekend
