### ISSUE TITLE
How to containerize Spring Boot application using Docker

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#1389]
### Brief Summary: 
[Docker](https://docs.docker.com/get-started/overview/), an open-source project launched in 2013, has helped popularize technology and has helped drive the trend towards containerization and micro-services in software development that’s known as cloud-native development. In the article I will be explaining how to containerize the `Todo` application that was created in [this](https://www.section.io/engineering-education/spring-boot-crud-api/) article using Docker.

### Key Takeaways: 
1. What is Docker.
2. What is Dockerfile and how to create it.
3. Creating Docker container from Dockerfile.

### References: 
[Understanding Docker concepts](https://www.section.io/engineering-education/docker-concepts/)
[Getting started with Docker](https://www.section.io/engineering-education/getting-started-with-docker/)

**Comment by hectorkambow** [comment]
Great topic- but we are now asking students to focus on one topic (from start to finish) 

Then we can continue with submitting more topics 👍  
I'll close this one in the mean times since you have another one in the works.
