### ISSUE TITLE
Introduction to Destructors in C++

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#1407]
### Brief Summary: 
Destructors are used to destroy the objects created by constructors when they are no longer needed to release the memory.  By declaring destructors in our program we are able to free memory space and better allocate resources. This article will go through the basic concepts of destructors and how to implement them in programs.

### Key Takeaways: 
1. What is a destructor.
2. When is a destructor called. 
3. Characteristics of destructors.
4. How to declare a destructor.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Dawe-7, but I believe this topic has already been sufficiently covered in this[ previously published article](https://www.section.io/engineering-education/constructors-destructors/). Please select a different topic area to explore.
