### ISSUE TITLE
Google Analytics vs Mixpanel in Web Analytics

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1413]
### Brief Summary: 
Web analytics is a process that measures page hits, clicks and views to provide insights for understanding web user behavior. Google Analytics and Mixpanel are popular web analytics tools that can be used for collecting and analyzing data relating to web usage. This article provides a comparison of these tools.

### Key Takeaways: 
1. What is Google Analytics?
2. What is Mixpanel?
3. Features of Google analytics
4. Features of Mixpanel
5. A comparison between Google Analytics and Mixpanel
6. Advantages and disadvantages of the two tools
7. Summary table 
8. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @mbaabuones, however, I think we'd prefer to steer away from comparisons/reviews of commercial product offerings, like Mixpanel. Please select a different topic area to explore.
