### ISSUE TITLE
Redshift vs. BigQuery

### ISSUE THREAD

**Issue by Ernest715** [section-io/engineering-education#1418]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

The age-old debate on data warehouses in the cloud continues. In the war of database engines, Redshift and BigQuery are the two most popular databases used by enterprises. This article compares the two data warehouses in terms of usability, pricing, scalability and performance.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. An overview of Redshift?
2. An overview of BigQuery?
3. To understand data processing systems.
4. Comparison between Redshift vs BigQuery.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Ernest715. Generally speaking, we try not to position reviews/comparisons of commercial product offerings. Could you please select a different topic area to explore?
