### ISSUE TITLE
Working With Rich Text Editor in Your Flask Web Application 

### ISSUE THREAD

**Issue by corpsgeek** [section-io/engineering-education#1420]
### Brief Summary: 
Building web apps sometimes require users to post or publish content, and they require flexibility on how their contents are displayed to users. The integration of rich text editor gives the user that flexibility to write and style contents and it eases development flow for web developers. 

### Key Takeaways: 
- What a rich text editor is
- Rich text editor options out there
- Summer Note rich text editor 
- Implementing Summer note in your flask web app 

### References: 
N/A

**Comment by ninjaginja** [comment]
@corpsgeek I see that you have two other open issues without attached PRs. Please work through those first, before suggesting new topics. Once you've submitted drafts for outstanding issues, you may request that this issue be re-opened. Thank you.
