### ISSUE TITLE
Introduction to Kotlin 

### ISSUE THREAD

**Issue by Dyrstiu** [section-io/engineering-education#1424]
### Brief Summary: 

Kotlin is a statically typed ,  open source programming language initially designed for Android and the JVM(java virtual machine ) that combines functional and object oriented  programming features. Kotlin offers developers a great perk of reusing existing codes  ,which saves time and energy.
### Key Takeaways: 
By the end of this tutorial the reader will be able to:
* Install and set up the Kotlin plugin.
* Write a Hello World application using Kotlin.
* Understand the basic syntax of Kotlin.

### References: 
 'N/A'.

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @Dyrstiu, however it seems that this topic is already being covered in #901. Please select a different topic area to explore.

**Comment by Dyrstiu** [comment]
Sorry for that I had not seen the same during my search
