### ISSUE TITLE
JavaScript Loops Explained

### ISSUE THREAD

**Issue by jumamiller** [section-io/engineering-education#1443]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Loops are used in JavaScript to perform repeated tasks based on a condition. Conditions typically return true or false when analysed. A loop will continue running until the defined condition returns false.

### Key Takeaways: 
1.Types of loops available in Javascript
2.How to Iterate with JavaScript Do…While Loops
3.How to Iterate with JavaScript While Loops
4.continue and break statement
### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @jumamiller , however this topic has already been sufficiently covered across several previously published articles, including:
- https://www.section.io/engineering-education/javascript-iterations-which-one-is-faster/
- https://www.section.io/engineering-education/event-loop-explained/

Please select a different topic area to explore.
