### ISSUE TITLE
Getting Started With JavaScript Browser Object Model 

### ISSUE THREAD

**Issue by jumamiller** [section-io/engineering-education#1446]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
The Browser Object Model (BOM) allows JavaScript to "talk to" the browser.
The Browser Object Model (BOM) is the core of JavaScript on the web. The BOM provides you with objects that expose the web browser’s functionality.

### Key Takeaways: 
How to use the following objects-
1. Window Object
2. History Object
3. Screen Object
4. Navigator Object
### References: 
N/A

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
