### ISSUE TITLE
How to Build Flutter Applications without starting Android Studio

### ISSUE THREAD

**Issue by wobin1** [section-io/engineering-education#1449]
### Brief Summary: 
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase. Flutter works Better with Android studio which Is a very heavy software that can slow down the performance of PCs most especially those with a low specification when running. This Tutorial will cover how to use an alternative and easy method for building android applications without starting the android studio software on the computer.

### Key Takeaways: 
Learn how to;
1. Write flutter code on VS code text editor.
2. use an alternative android emulator to test your android apps.
3. test your android apps on your mobile phones.

### References: 
https://flutter.dev/docs/get-started/install/windows
https://docs.genymotion.com/desktop/3.0/01_Get_started/012_Installation.html#windows
https://flutter-examples.com/run-test-flutter-apps-directly-on-real-android-device/

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
