### ISSUE TITLE
Comparing Graphical User Interface (GUI) and Command Line Interface (CLI)

### ISSUE THREAD

**Issue by BridgetMwikali** [section-io/engineering-education#1451]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

The operating system of any device is nothing but an interface between user and hardware components of that device. The operating system offers a GUI vs CLI user interface to interact with an electronic device. GUI means a Graphical user interface while CLI means the command line interface.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

What is GUI 
What is CLI
A comparison between GUI and CLI in terms of : 

- Ease of use
- Multitasking
- Remote access 
- Scripting
- Speed 
- Control

## References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
