### ISSUE TITLE
Pointers in C#

### ISSUE THREAD

**Issue by carteblanchemunene** [section-io/engineering-education#1452]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
C# underpins pointers in a restricted degree. A C# pointer is only a variable that holds the memory address of another type. In this article, we will understand the C# pointers and their use.

### Key Takeaways: 
1. What are pointers.	
2. Declaring a pointer type.
2. Unsafe codes.
3. Performing different operations in C# using pointers.

### References: 
N/A

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
