### ISSUE TITLE
How to Create an Automatic Slider in Android Studio

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#1455]
**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 

Sliders are commonly used on cross platforms, i.e., websites and applications. They are mostly implemented on the home page or application main screens to showcase major and key features. Let's take a case of an eCommerce application. You would like to show the new items you have in your shop without interfering with the user app interaction.

Slides would be a perfect way to showcase some of these major new items to the user on your main application screen.

This guide will walk you through how to create an automatic slider using android studio.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
