### ISSUE TITLE
Front End vs Back End in Web Development

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#1457]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Understanding the comparison between front end and back end is important to young developers because it helps them to determine their right career paths. This article provides a comparison of these two concepts in web development. 

### Key Takeaways: 
1. What is front end development?
2. What is back end development?
3. Differences between front end and back end development
4. Understanding full stack development
5. Summary table
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
