### ISSUE TITLE
Kafka vs RabbitMQ

### ISSUE THREAD

**Issue by kabatamwaura** [section-io/engineering-education#1458]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

This topic will review the architectural designs, performance and the usage of the two systems.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. A brief description of Kafka.
2. A brief description of RabbitMQ.
3. What are the architectural differences between Kafka and RabbitMQ.
4. Comparison in performance between Kafka and Rabbit MQ.
5. When is it best to use either Kafka or RabbitMQ?
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
