### ISSUE TITLE
Understanding Carrier-sense Multiple Access in Ethernet Technology

### ISSUE THREAD

**Issue by Bradley8555** [section-io/engineering-education#1459]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Carrier-sense multiple access (CSMA) is a media access control protocol in which a node verifies the absence of other traffic before transmitting on a shared transmission medium, such as an electrical bus or a band of the electromagnetic spectrum.

### Key Takeaways: 

1. What is Ethernet Technology
2. Introduction to CSMA
3. How CSMA works.

### References: 
N/A

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
