### ISSUE TITLE
Techniques to Detect Outliers in Machine Learning 

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#1462]
### Brief Summary: 

When training machine learning algorithms, outliers may be problematic. Outliers, or anomalies, are often a result of variability in measurement or experimental error. They greatly influence the predictive model. As such, it is important to detect outliers, not only in machine learning but in any quantitative discipline. We explore a few outlier detection techniques in this article.  

### Key Takeaways: 

The reader should:

1. Be introduced to outliers, the types of outliers, and the need for outlier detection
2. Understand the causes of outliers
3. 4 detection techniques in the form of z-score, DBSCAN, isolation forest, and numerical outlier method.

### References: 

https://towardsdatascience.com/a-brief-overview-of-outlier-detection-techniques-1e0b2c19e561

https://www.digitalvidya.com/blog/outlier-detection/#:~:text=%20Outlier%20Detection%20Methods%20%201%20Extreme%20Value,approach%2C%20Probabilistic%20and%20Statistical%20Models%20assume...%20More%20

https://machinelearningmastery.com/how-to-use-statistics-to-identify-outliers-in-data/

https://medium.com/@mehulved1503/effective-outlier-detection-techniques-in-machine-learning-ef609b6ade72

https://towardsdatascience.com/outlier-detection-theory-visualizations-and-code-a4fd39de540c

https://www.kdnuggets.com/2018/12/four-techniques-outlier-detection.html

**Comment by ninjaginja** [comment]
Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
