### ISSUE TITLE
ICT support Levels

### ISSUE THREAD

**Issue by ipitah** [section-io/engineering-education#1466]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The modern world business activities performance has greatly improved. Businesses have put more emphasis on customer satisfaction that is monitored by evaluating effectiveness, efficiency, cost, and time for an activity. To better their service, businesses have adopted a couple of ways, the major one is embracing the use of technology with a number of them establishing a support department (ICT or IT department). A common task that can often be taken for granted is user support which is classified in different levels. This article will therefore discuss and classify the ICT support.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
ICT support is mainly a routine activity performed on a daily basis. It takes a lot of time, with some situations requiring 24/7 support. The activity requires skilled staff to handle it from troubleshooting to solving the problem. The technicality of staff is based on the level of education and experience. Therefore, ICT support is handled following a certain protocol, from low to high technical levels. The levels are classified from L0 to L4. Therefore, it is important to note each level and its requirements such as education and expertise. It will guide ICT staff and other members of staff when seeking support and when provided with a response.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. https://www.bmc.com/blogs/support-levels-level-1-level-2-level-3/
2. https://www.greycampus.com/blog/it-service-management/it-support-what-are-the-different-levels
3. https://tss.nmsu.edu/technical-support-center-service-level-agreement/
4. https://medium.com/@harshanacslab/what-is-l1-l2-and-l3-support-engineering-6e9ca20c1dbb#:~:text=They%20have%20more%20knowledge%2C%20more,which%20addresses%20the%20technical%20issues.
5. https://www.quora.com/What-are-the-differences-in-L1-L2-and-L3-support-of-jobs-in-software-engineering
6. https://itsyndicate.org/blog/what-is-l1-l2-l3-support/
7. http://www.greenstech.in/oracle-application-support.pdf
8. https://serverhealers.com/what-is-l1-l2-l3-support/

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @ipitah. Per the message posted in Slack yesterday, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
