### ISSUE TITLE
Introduction to Embedded Systems

### ISSUE THREAD

**Issue by OMONDIELLY** [section-io/engineering-education#1470]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
An Embedded system is a computer system formed from a combination of programmable hardware and software components that are designed for specific functions.
Embedded systems solve problems that are not feasible for classical computers.
In this article, I'll cover the basics of  Embedded Systems.

### Key Takeaways: 
1. What is an Embedded System.
2. Basic Elements of Embedded  Systems.
3. Characteristics of Embedded Systems.
4. Application areas of Embedded Systems.

### References:  
N/A

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion @OMONDIELLY. Per the message posted in Slack, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
