### ISSUE TITLE
How-To test Apollo + Mongo Backend with Jest

### ISSUE THREAD

**Issue by HarishTeens** [section-io/engineering-education#1476]
### Brief Summary
Discuss about the options to test a Apollo + Mongo backend followed by a detailed walkthrough using Jest and MongoDB memory server.

### Prerequisites
Should have knowledge in developing backend applications using Apollo GraphQL and Mongo

### Key Takeaways
- Gain different perspectives to test a Apollo + Mongo Backend
- Pros and Cons of each approach
- detailed walkthrough with code implementation using Jest and MongoDB server
- how this approach is beneficial in certain usecases and when you should use this
- Writing effective tests with minimalistic inputs which focusses on testing just the feature.

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
