### ISSUE TITLE
Create CRUD operation in JavaScript Ajax with PHP and MySQL

### ISSUE THREAD

**Issue by tambastar** [section-io/engineering-education#1480]
### Introduction

Using javascript to run CRUD operation without reloading the web page. PHP is a backend programming language while MySQL is a Relational database. With help of HTML and Javascript, this tutorial will show how one can work on CRUD operation for a web application

###  Goals 

- understand Ajax
- Understand PHP and how it connects to MySQL
- Create Database and Table in MySQL RDMS

### Prerequisites

- PHP Skills
- Javascript Skills
- Database Skills
- HTML Skills
- Good IDE Like Visual Code

### Conclusion
Create an application with Javascript Ajax that can run CRUD Operation

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
