### ISSUE TITLE
An overview of Vim- The text editor that will save you time

### ISSUE THREAD

**Issue by yuyangchee98** [section-io/engineering-education#1481]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Vim is a modal text editor that many older software engineers love for its features and extensibility. A text editor is a fundamental tool write code. It's important and also fun to customize that window. However, not many younger software engineer knows about this, instead opting for commercial applications such as VSCode or Atom.

I plan to introduce what Vim is, how to use it, examples of how it's better and end with some ways the reader can read and learn more about Vim.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Understanding modal vs modeless text editors
- How modal text editor may speed up your workflow
- Use vim or at least learn how to learn how use vim.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
Mostly personal experience.

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
