### ISSUE TITLE
Firebase Email/Password Authentication in a Non-Expo React Native Application

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#1483]
## Brief Summary
In this tutorial, we will develop a React Native application (Non-Expo) and add email/password authentication using Firebase.

## Key Takeaways

- Set up Firebase Project for Email/Password authentication.
- Add Login/Create account screen.
- Use the Firebase Auth module and authenticate users.
- Logout from the authenticated screen.

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.

**Comment by zolomohan** [comment]
@ninjaginja completely forgot about it. Sorry 😅
