### ISSUE TITLE
Breaking-Down the Processor Technology

### ISSUE THREAD

**Issue by kvardhan10** [section-io/engineering-education#1488]
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Processor is one of the key components of a computer. Having the right processor can benefit the user in doing the tasks faster and better. But  it depends on various requirements and processor capabilities. This article will introduce some of the many features to the readers and help them understand how the computing capacity differs with various specifications.

### Key Takeaways: 
After reading this article, the reader will have a clearer concept about different capabilities of processor and will be able to differentiate between various types of Intel and AMD processors. The reader will be introduced to various specifications such as:
-  Socket
-  Cores and its types
-  Clock speed
-  Cache Memory
-  Threading and Hyperthreading

### References: 
https://www.pugetsystems.com/labs/articles/Specs-Explained-CPU-137/
https://techguided.com/7-cpu-specs-explained/

**Comment by ninjaginja** [comment]
Thank you for your topic suggestion. Per the message posted in Slack last week, we are pausing acceptance of new articles until further notice while we work through the backlog of submitted drafts. We will notify you when we are ready to accept new topic suggestions. Thank you for your patience.
