### ISSUE TITLE
MySQL Query Performance Optimizations Tips

### ISSUE THREAD

**Issue by Tsanguu** [section-io/engineering-education#322]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
This article will cover different ways in which we can optimize MySQL queries. The goal is tom to improve performance. As data volume grows, it is important to optimize MySQL database. This will ensure that end-users get a good experience as well as reduce the cost of infrastructure.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Benefits of MySQL Database Query Optimizations 
Tips for MySQL Query Optimizations
- 	Optimizing Your Database Schema
- 	MySQL Query Caching
- 	Use wildcards at the end of a phrase only
- 	Using indexes
- 	Use DISTINCT and UNION only if it is necessary
- 	SELECT fields instead of using SELECT *
- 	Avoid SELECT DISTINCT
- 	Converting OUTER JOINs to INNER JOINs
- 	Subquery optimization

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
[https://www.cloudways.com/blog/mysql-performance-tuning/](https://www.cloudways.com/blog/mysql-performance-tuning/)
[https://dzone.com/articles/how-to-optimize-mysql-queries-for-speed-and-perfor](https://dzone.com/articles/how-to-optimize-mysql-queries-for-speed-and-perfor)
[https://dzone.com/articles/how-to-optimize-mysql-queries-for-speed-and-perfor](https://dev.mysql.com/doc/refman/8.0/en/optimization.html)
[https://medium.com/@shashwat12june/mysql-query-optimizer-fc158b3de623](https://medium.com/@shashwat12june/mysql-query-optimizer-fc158b3de623)

**Comment by ninjaginja** [comment]
published under #334
