### ISSUE TITLE
Introduction to Neural Networks

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#338]
### Brief Summary: 
Neural Networks and Deep Learning are big topics in the technology industry. Neural Networks are a functional unit of Deep Learning. DL uses Neural Networks which mimics the Human Behaviour to provide solutions to problems in Object Recognition, Speech Recognition, etc. This article aims to cover an overview of Neural Networks. 

### Key Takeaways: 
1. Understanding Neural Networks
2. Neural Networks Architecture
3. How Neural Networks Works
4. Main Types of Neural Networks
5. Applications of Neural Networks

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://towardsdatascience.com/a-gentle-introduction-to-neural-networks-series-part-1-2b90b87795bc
https://www.sciencedirect.com/book/9781856171205/introduction-to-neural-networks#book-info
https://www.inf.ed.ac.uk/teaching/courses/nlu/assets/reading/Gurney_et_al.pdf
https://towardsdatascience.com/understanding-neural-networks-19020b758230

**Comment by botahamec** [comment]
You and @collins-a might want to make sure you're not doing the same topic

**Comment by collins-a** [comment]
@botahamec definitely. My GPT-3 topic will strictly deal with transformer language models like GPT and BERT.
