### ISSUE TITLE
Introducing GPT-3

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#343]
### Brief Summary: 

Generative pre-trained transformers are language models that produce human-like text. These models make it easier to develop machine learning applications while also providing a way in for people with little tech background to develop said applications. GPT-2 was massive, with about 1.5 billion parameters. The magnitude of this new model blows its predecessor out of the water boasting of 175 billion parameters. For all the hype surrounding GPT-3, it is necessary to take a closer look. 

### Key Takeaways:
 
The reader should:
1. Be aware of the potential of GPT-3
2. Get to know the uses and applications of the model
3. Understand how GPT-3 compares to previously considered state-of-the-art transformer models
4. Learn the limitations and dangers of GPT-3

### References: 

1. https://arxiv.org/pdf/2005.14165.pdf
2. https://bmk.sh/2020/05/29/GPT-3-A-Brief-Summary/
3. https://gpt3examples.com/

**Comment by ninjaginja** [comment]
sounds like an interesting topic @collins-a

**Comment by botahamec** [comment]
> dangers of GPT-3

I'm glad you're talking about this. I have an article in my backlog about AI safety already, but it's good to at least mention it when talking about GPT-3

**Comment by collins-a** [comment]
@botahamec sure thing. I'd love to read/reference the article on AI safety if applicable to this topic
