### ISSUE TITLE
SQL or NoSQL?

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#345]
### Brief Summary: 
Knowing which database structure to use is critical even before the kickoff between development to deployment of your application. We will jump into these two database structures and explore them deeply and understand how they work. By the end of this topic, learners will understand: what is SQL/NoSQL, key differences, key features, their structures, and application of each with example use cases.

### Key Takeaways: 
1. SQL 
2. NoSQL
3. SQL vs NoSQL
4. The key differences
5. Applications

### References: 
https://www.mongodb.com/nosql-explained/nosql-vs-sql
https://www.thegeekstuff.com/2014/01/sql-vs-nosql-db/
https://www.thorntech.com/2019/03/sql-vs-nosql/

**Comment by ninjaginja** [comment]
good topic @kimkimani
