### ISSUE TITLE
Article - Create and Deploy NPM Packages

### ISSUE THREAD

**Issue by cyberShaw** [section-io/engineering-education#349]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Node modules are packages that are used with web applications. Web frameworks, APIs, libraries are all created as node modules. In this article, let us look at how to create a basic node module and publish it to the npm package repository.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader will be able to understand what a npm package is.
- The reader will get a hands on experience on creating a basic node package.
- The reader will know the workflow of publishing a node module to the npm package repository.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
http://docs.npmjs.com/

**Comment by ninjaginja** [comment]
Great! Thanks for transferring to an issue per the new process.
