### ISSUE TITLE
Contigency and Planning

### ISSUE THREAD

**Issue by KiokoM** [section-io/engineering-education#353]
### Brief Summary: 
In the current world, most organizations operate with no backup plan in their operations. On this article we dive into why contigency plans are needed and some steps to take in implementing them 

### Key Takeaways: 

- what is are Incident response plans(IRP), Disaster recovery plans(DRP) and Business continuity Plans(BCP).
- How to structure the plans
- Implementation of the plans

### References: 
Padilla, V. S., & Freire, F. F. (2019). A contingency plan framework for cyber-attacks. Journal of Information Systems Engineering & Management, 4(2).

**Comment by ninjaginja** [comment]
@KiokoM This topic doesn't really align with our target topic areas. We look for more technical articles related to web technologies. I'd suggest taking a look through the existing content to get other ideas. I'm going to go ahead and close this issue.
