### ISSUE TITLE
Flutter vs React, which is a better cross-platform framework

### ISSUE THREAD

**Issue by Chinmay-KB** [section-io/engineering-education#354]
### Brief Summary: 
A few hours ago Flutter for Windows was released in alpha, which now officially brings it in the range of overtaking react in terms of cross platform. This article will summarize the pros, cons and the current trend of cross platform frameworks
### Key Takeaways: 
* Why cross platform frameworks are the future
* Pros and cons of flutter and react native/electron
* Laymans explanation of how both frameworks approach cross platform
* How flutter is revolutionizing cross platform development
### References: 
[Announcing Flutter Windows Alpha](https://medium.com/flutter/announcing-flutter-windows-alpha-33982cd0f433)

**Comment by ninjaginja** [comment]
sounds like a great topic @Chinmay-KB

**Comment by ninjaginja** [comment]
PR was closed
