### ISSUE TITLE
Objects, Arrays and Destructuring in JavaScript

### ISSUE THREAD

**Issue by geoffrey45** [section-io/engineering-education#357]
### Brief Summary: 
Understanding Objects, arrays and E6 destructuring is a key tip in writing good JavaScript code. Mastering these skills will help prevent common syntax errors.

### Key Takeaways: 
- Object assignment using dots
- Accessing objects using dots
- Arrays
- Array methods
- Difference between  arrays and objects
- The bracket notation
- Value assignment in arrays
- ES6 destructuring
  - variable decralation by use of const, let and var
  - Object and array destructuring
  - Application of destructuring
- Use of non-valid characters in Js 

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @geoffrey45
