### ISSUE TITLE
Implementation of K-Means Clustering Algorithm from Scratch

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#358]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
K-means is an unsupervised learning algorithm. Usually libraries are used to implement K-means algorithm. Implementing from scratch gives us an in-depth understanding of the algorithm and the ability to design better algorithms.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.  Understand the K-means algorithm in detail and develop an intuition for the same.
2. Implement K-means from scratch in R programming language
3. Generate plots and visualize the clusters formed
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
great topic @lalith1403
