### ISSUE TITLE
Introduction to Reinforcement Learning (RL)

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#359]
### Brief Summary: 
Reinforcement Learning (RL) is a branch of machine learning (ML). It is an ML technique that enables an agent to learn in an interactive environment by trial and error using feedback from its own actions and experiences.
As compared to other unsupervised learning algorithms, reinforcement learning is different in terms of its goals. While the goal in unsupervised learning is to find similarities and differences between data points, in RL, the goal is to find an optimal action model that would maximize the total cumulative reward of the agent.

### Key Takeaways: 
1. What is Reinforcement Learning? 
2. Which are the most used Reinforcement Learning Algorithms?
3. What are some of the applications of Reinforcement Learning today?

### References: 
1. Kaelbling, L. P., Littman, M. L., & Moore, A. W. (1996). Reinforcement learning: A survey. Journal of artificial intelligence research, 4, 237-285.
2. Sutton, R. S., & Barto, A. G. (1998). Introduction to reinforcement learning (Vol. 135). Cambridge: MIT press.
3. Szepesvári, C. (2010). Algorithms for reinforcement learning. Synthesis lectures on artificial intelligence and machine learning, 4(1), 1-103.
4. Henderson, P., Islam, R., Bachman, P., Pineau, J., Precup, D., & Meger, D. (2017). Deep reinforcement learning that matters. arXiv preprint arXiv:1709.06560.
5. François-Lavet, V., Henderson, P., Islam, R., Bellemare, M. G., & Pineau, J. (2018). An introduction to deep reinforcement learning. arXiv preprint arXiv:1811.12560.
6. Arulkumaran, K., Deisenroth, M. P., Brundage, M., & Bharath, A. A. (2017). A brief survey of deep reinforcement learning. arXiv preprint arXiv:1708.05866.
7. Arulkumaran, K., Deisenroth, M. P., Brundage, M., & Bharath, A. A. (2017). Deep reinforcement learning: A brief survey. IEEE Signal Processing Magazine, 34(6), 26-38.

**Comment by ninjaginja** [comment]
good topic @Bayler

**Comment by Bayler** [comment]
Thank you @ninjaginja I'll commence writing the article
