### ISSUE TITLE
How to Set up Nginx on an Ubuntu 18.04 Virtual Machine on AWS

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#360]
### Brief Summary: 
This is part one of a series that leads up to covering caching in Node.js using Section's varnish Cache.

### Key Takeaways: 
This article picks up after [setting up a VM on  AWS](https://www.section.io/engineering-education/setup-ssh-ubuntu-vm-aws/)
Guiding you on how to setup an Nginx server.
### References: 
[Nginx documentation](https://nginx.org/en/docs/)

**Comment by ninjaginja** [comment]
closing in favor of focus on 363/364 (consolidated) and 362
