### ISSUE TITLE
How to deploy a Nodejs app on an Ubuntu 18.04 Virtual Machine on AWS with an Nginx server

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#361]
### Brief Summary: 
This article is part two on a series that leads up to caching in Node.js using Section's Varnish cache.
The Nodejs app that will be deployed is covered in [How To Build and Test a Node.js REST API with Express on Ubuntu 18.04](https://www.section.io/engineering-education/building-a-basic-api-with-nodejs/)
### Key Takeaways: 
The reader will understand how to setup Nginx to serve a Nodejs app and work with Git to manage the code in dev environments and production environments..
### References: 
[Nodejs dot dev](https://nodejs.dev/learn)
[Nginx documentation](https://nginx.org/en/docs/)

**Comment by ninjaginja** [comment]
closing in favor of focus on 363/364 (consolidated) and 362
