### ISSUE TITLE
Caching. The theory behind it. 

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#363]
### Brief Summary: 
This article is part four on a series that leads up to caching in Node.js using Section's Varnish cache.
Covering what Caching is, how it is achieved and when it is used.
### Key Takeaways: 
The reader will gain an understanding of Proxys and Reverse Proxys.
The reader will understand what caching is and know caching options in the market.
The reader will understand when it is necessary to cache and where caching sits in application architecture.

### References: 
[Cloudflare documentation](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/)
[Varonis](https://www.varonis.com/blog/what-is-a-proxy-server/)

**Comment by ninjaginja** [comment]
@adrianmurage I think there are opportunities to consolidate some of this series content. For example, this caching theory article could likely serve as an intro to one of your other suggested articles. We try to steer away from extensive series articles to reduce the burden on the reader to click around to find content. All articles need to be able to stand on their own to present clear and complete ideas.

**Comment by adrianmurage** [comment]
@ninjaginja 
I see. I could tie this up with #364 and have it serve as the intro to the article.
Thank you for your input.

**Comment by ninjaginja** [comment]
consolidated into #364
