### ISSUE TITLE
Understanding Node.js Asynchronous  Flows

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#367]
### Brief Summary: 
Async is a utility module that provides straight-forward, powerful functions for working with asynchronous flow control for JavaScript. Async utility has a number of control flows. The article will discuss the most popular ones and their use cases:

### Key Takeaways: 
1.  Serial
2.  Parallel
3.  Waterfall and 
4.  Queues

### References: 
https://caolan.github.io/async/v3/docs.html#controlflow

**Comment by ninjaginja** [comment]
great topic @kimkimani
