### ISSUE TITLE
Kotlin Ranges

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#371]
### Brief Summary: 
Before Kotlin came in to save the day, loops were the best solutions for various iterations solutions. But this proved to be a tedious way to iterate in some cases. This article aims to show how to use Kotlin ranges to perform various actions and show the comparison between using the old ways and using ranges.

### Key Takeaways: 
1. What are Kotlin ranges
2. How to use Kotlin ranges
3. Choosing ranges over loops
4. Other uses for ranges

### References: 
N/A

**Comment by ninjaginja** [comment]
sounds like an interesting topic @LinusMuema

**Comment by ninjaginja** [comment]
linked to #426
