### ISSUE TITLE
Differences between Artificial Intelligence, Machine Learning and Deep Learning explained

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#373]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
These three terms, Artificial Intelligence, Machine learning and Deep Learning often overlap and are easily confused by readers.

**Artificial Intelligence (AI)** refers to the ability of computers to think and mimic actions displayed in humans. 
**Machine Learning (ML)** is a sub-field of AI that gives computers the capability to learn without being explicitly programmed.
**Deep Learning (DL)** is a sub-field of ML which uses neural networks to identify patterns within a structure. 
In this article, we will be able to explore further each of this terminologies and provide a little more background.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
By the end of this article, the reader should be able to answer these 3 questions:
1. What is AI?
2. What is Machine Learning?
3. What is Deep Learning?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
1. Michie, D., Spiegelhalter, D. J., & Taylor, C. C. (1994). Machine learning. Neural and Statistical Classification, 13(1994), 1-298.
2. Goodfellow, I., Bengio, Y., Courville, A., & Bengio, Y. (2016). Deep learning (Vol. 1). Cambridge: MIT press.
3. Russell, S., & Norvig, P. (2002). Artificial intelligence: a modern approach.

**Comment by ninjaginja** [comment]
good topic @Bayler

**Comment by Bayler** [comment]
Thank you
