### ISSUE TITLE
Graph Data Structure in Python - Part 1

### ISSUE THREAD

**Issue by cyberShaw** [section-io/engineering-education#375]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Graphs are non-linear data structures. Graph Theory is the theory of the properties and applications of the graph data structure. Graphs can be used to represent almost any problem, which makes them extremely versatile. 
In this article, we'll be looking at an overview of graphs, the different types of representation of graphs, various graph algorithms and more.

_**Note: I'll be splitting this article into two parts where**_
- **Part 1** - Basics of Graph Theory, Graph Representation in Python & Applications of Graphs
- **Part 2** - Graph Algorithms - Breadth-First Search, Depth-First Search and Detecting Cycles

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will be able to understand the graph data structure and its different types.
- The reader will be able to realize the importance of graphs and their applications.
- The reader will be able to implement Graphs in Python through various representations like Edge List, Adjacency List, Adjacency Matrix, etc.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.cpp.edu/~ftang/courses/CS241/notes/graph.htm
https://www.hackerearth.com/practice/algorithms/graphs/graph-representation/tutorial/

**Comment by ninjaginja** [comment]
good topic @cyberShaw
