### ISSUE TITLE
Types of Styling in CSS

### ISSUE THREAD

**Issue by KiokoM** [section-io/engineering-education#378]
### Brief Summary: 
Here we look at the different methods of styling in CSS and how they affect a project during development or in production.

### Key Takeaways: 
The different types of styling
Advantages of each style
Disadvantages of each style
When to apply a specific style

### References: 
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @KiokoM. The summary that you've provided is rather vague, so it's difficult for us to determine whether your article is expected to have sufficient depth and value for readers. Could you expand a bit upon the key takeways that you've listed?

**Comment by KiokoM** [comment]
Hi,
For the CSS styling, I'll be covering
- local styles; where you define your CSS within the HTML element
- Page-Level styles; The stying if defined on the page's header area
- External styles; The styling is defined in a separate document and linked
to the page.

After diving into this different styling methods, I'll expand on the best
advantages of each and the best use scenario for each style.

Thank you. Regards

**Comment by ninjaginja** [comment]
Thanks for expanding on what you intend to cover in the article. Sounds like a good topic 👍

**Comment by KiokoM** [comment]
Does that mean I can proceed with it?

**Comment by ninjaginja** [comment]
yep, all good!
