### ISSUE TITLE
Advanced Programming Concepts in R

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#380]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Having discussed the basics of R programming in the first article, I will be discussing some advanced topics of R and their applications.  This article will give a complete working knowledge of R and will help the reader write and understand code on their own. It will also help in implementing various machine learning algorithms. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or do after reading this article?
Some of the topics that will be discussed are as follows:
1. Dataframes
2. TypeCasting
3.Reading and Writing Data
4. Working with inbuilt Datasets in R
5. Conditional statements and loops in R
6. Functions 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A.')
N/A

**Comment by ninjaginja** [comment]
great topic @lalith1403  - I see that you've already linked a PR to this suggestion 👍

**Comment by lalith1403** [comment]
I finished writing the article... Forgot to create the suggestion. Hence, have linked it.
