### ISSUE TITLE
Handling Machine Learning Bias

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#383]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

We are increasingly dependent on machine learning in our daily lives. An example is in the every-day products we use. However, these algorithms are created by human beings. As a result, algorithms may contain the same biases humans possess. An algorithm displaying say, sexist or racist bias has potential to cause more harm than good.  It is therefore important for algorithms to make predictions that are accurate and fair. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

The reader should understand:

1. What is bias in machine learning
2. Why they should care about bias in machine learning algorithms. (impact and consequences of bias) 
3. Types of bias.
4. Techniques to handle bias.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. E. Sengupta, D. Garg, T. Choudhury and A. Aggarwal, "Techniques to Eliminate Human Bias in Machine Learning," 2018 International Conference on System Modeling & Advancement in Research Trends (SMART), Moradabad, India, 2018, pp. 226-230, doi: 10.1109/SYSMART.2018.8746946.
2. https://towardsdatascience.com/preventing-machine-learning-bias-d01adfe9f1fa
3. https://blog.insightdatascience.com/tackling-discrimination-in-machine-learning-5c95fde95e95

**Comment by ninjaginja** [comment]
Excellent (and very relevant) topic @collins-a

**Comment by collins-a** [comment]
Thanks @ninjaginja! I'll give it my best
