### ISSUE TITLE
Deciphering the Various Roles in Data Science Industry

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#386]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The data science industry has been expanding rapidly. The job roles that exist today did not exist five years ago. Therefore, a lot of disambiguity exists in roles description. This article aims to define the various positions and their specific roles.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
I will cover the following roles in the data-science industry:
1. Machine learning engineer
2. Machine learning scientist
3. Data scientist and analysts
4. Machine learning architect: 
Understanding the various roles helps one get an overview of the field and better understand the direction in which research and industry are headed towards.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A.')
N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403
