### ISSUE TITLE
An absolute beginner guide on NPM

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#389]
### Brief Summary: 
The whole ecosystem of Node.js is based on tools such as NPM. This will be a complete guide on how to use Node Package Management (NPM). The guide will be very beginner-friendly with key points to get started with NPM as well as advanced points such as npm auditing and npx.

### Key Takeaways: 
•	Using NPM
•	NPM init
•	Node_modules
•	Installing Modules in Local Mode and Global Mode
•	Uninstalling, delete, update, and install a specific version of a package
•	Understanding Project Dependencies in package.json
•	Package auditing
•	NPM cache
•	npx

### References: 
https://docs.npmjs.com/

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @kimkimani. We've published some NPM-related articles previously. Please make sure that your article presents unique content that has not yet been covered within the EngEd community. You can access a quick search of these articles [here](https://www.section.io/engineering-education/search/?q=npm).

**Comment by kimkimani** [comment]
Thank you Molly. 
Every Node.js article will at point direct to NPM primarily to install frameworks and libraries. But there isn't that guide on how to use NPM and I instead to dig on how to use NPM

**Comment by ninjaginja** [comment]
Thanks for the follow-up @kimkimani . Based on your last message, I just want to be sure that you're delivering original content and not simply repeating what already exists in NPM documentation. Assuming that's the case, please proceed as intended.
