### ISSUE TITLE
How TEAM Work or Collaboration Influences the Productivity of Developers

### ISSUE THREAD

**Issue by domitechnshimba** [section-io/engineering-education#398]
### Brief Summary: 
In this article, we are going to be looking at "How to build a team that Collaborates". Building a successful team is more than finding a group of people with the right mix of professional skills.

### Key Takeaways: 
1. You Have to Create a Clear Map.
2. You Need to Have a Shared Scoreboard.
3. You Have to Create Your Team's Culture.

**Comment by ninjaginja** [comment]
Thanks for the topic suggestions @domitechnshimba . This content doesn't align with the technical content that the program is geared around. If you need some ideas or guidelines, please peruse the [EngEd articles](https://www.section.io/engineering-education/) and/or check out our [contribution guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md). I'm going to close this issue.
