### ISSUE TITLE
Understanding Differential Privacy

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#407]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Differential privacy is a system for publicly sharing information about a dataset by describing the patterns of groups within the dataset while withholding information about individuals in the dataset. In this article, we will be looking at an overview of what privacy is, concept of differential privacy, various types of differential privacy and how it is useful.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

* The reader will be able to understand the importance of privacy while deploying Deep learning algorithms
* The reader will get an insight of how privacy can be maintained in remote devices, while dealing with personal data
* The reader will be able to implement differential privacy

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

https://medium.com/sap-machine-learning-research/client-sided-differential-privacy-preserving-federated-learning-1fab5242d31b 
https://towardsdatascience.com/ai-differential-privacy-and-federated-learning-523146d46b85

**Comment by ninjaginja** [comment]
great topic @srishilesh , but we would prefer this article as a single, consolidated piece. Please combine this, along with #408 into a single article.

**Comment by srishilesh** [comment]
> great topic @srishilesh , but we would prefer this article as a single, consolidated piece. Please combine this, along with #408 into a single article.

Alright @ninjaginja , I will combine them as a single article
