### ISSUE TITLE
Implementing Differential privacy using Federated learning - Part 2

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#408]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Continuation of Issue #407 
Federated learning (also known as collaborative learning) is a machine learning technique that trains an algorithm across multiple decentralized edge devices or servers holding local data samples, without exchanging them. In this article, we will looking at an overview of what federated learning is and implement federated learning using PyTorch

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand the concept of Federated learning
- The reader will be able to code his own Federated deep learning model

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://ai.googleblog.com/2017/04/federated-learning-collaborative.html
- https://medium.com/@ODSC/what-is-federated-learning-99c7fc9bc4f5
- https://towardsdatascience.com/preserving-data-privacy-in-deep-learning-part-1-a04894f78029

**Comment by ninjaginja** [comment]
combine with #407

**Comment by srishilesh** [comment]
Combining this issue with #407
