### ISSUE TITLE
Explainable AI (XAI): An Introduction

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#410]
### Brief Summary: 

AI-powered systems have a lot of influence on our daily lives. A number of these systems are so sophisticated that little to no human intervention is required in their design and deployment. These systems make a lot of decisions for us every single day. In fact, they make a lot of crucial decisions that affect human lives (e.g in medicine, finance, law, defense) but the manner in which they do is often not explained. In order to trust the decisions they make, there is a growing need to understand how these systems make decisions. We explore the need for explainable AI. 

### Key Takeaways: 

Readers should:
1. Be able to define the concept of explainable AI
2. Understand the need and importance of explainable AI (compared to black-box systems)
3. Get to know the use cases of explainable AI
4. Be aware of the challenges to achieving explainable AI

### References: 

1. Explainable Artificial Intelligence (XAI): Concepts, taxonomies, opportunities and challenges toward responsible AI https://doi.org/10.1016/j.inffus.2019.12.012
2. https://www.infoq.com/articles/explainable-ai-xai/

**Comment by ninjaginja** [comment]
good topic @collins-a . Would also be great if you could cover some of the approaches/methods in your article.

**Comment by collins-a** [comment]
@ninjaginja noted. Will definitely do so
