### ISSUE TITLE
Information Gathering : Foot Printing

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#411]
### Brief Summary: 
“Information is power,” as the saying goes,, in Cyber Security industry **information gathering** is the first step to take during the earlier stages of any hacking activity, if it is ethical hacking or even cracking, it is used when a researcher needs to gain as much information as possible about the desired target.

**Note: I'll be splitting this article into two parts where**
- **Part 1** - Foot Printing
- **Part 2** -  Network Scanning
In this article, we'll be looking at an overview of foot printing, how to collect data about a target, what are tools/sites etc.. we can use, and more.

### Key Takeaways: 
- The reader will be able to understand the foot printing method , how it is working and which tools are better for using.
- The reader will be able to collect the following information about a target : 
   - Domain name Info(Owner, date of registration , etc..)
   - IP Addresses
   - location(Region & City)
   - Phone numbers/email etc..
    and a lot more.

### References: 
https://en.wikipedia.org/wiki/Footprinting

**Comment by ninjaginja** [comment]
@ahmadmardeni1 This topic is does not align with our areas of focus. Footprinting is largely associated with unethical hacking, and we do not wish to broach any subjects which could be considered as guiding malicious activity. Please feel free to suggest another topic area.
