### ISSUE TITLE
Integrating a Bottom Navigation View in Android Applications. 

### ISSUE THREAD

**Issue by BrianaNzivu** [section-io/engineering-education#412]
### Brief Summary: 
A Bottom Navigation bar in Android Applications is used to navigate through  different fragments of an application. Most applications use bottom navigation bars in order to ease the development process and to make an application more User friendly in that user's can explore and switch between top-level views in a single tap. 

### Key Takeaways: 
1.The reader should be able to understand how to integrate a bottom navigation bar in an android application. 
2.The reader should be a able to understand what a fragment is and how to create a new fragment. 
3.The reader should be able to understand how to change icons and the text in a bottom navigation bar. 

### References: 
N/A

**Comment by ninjaginja** [comment]
sounds like a cool tutorial @BrianaNzivu
