### ISSUE TITLE
Job scheduling in node.js using node-cron

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#413]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Node-cron is an npm package used to schedule tasks to run at specific time either once or repeatedly. This article is going to give the reader a basic understanding of the package and a tutorial on how to schedule some common tasks in node.js. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.  Understand the basics of node-cron pachage.
2.  Know how to schedule tasks in node.js using node-cron.
3.  Know various use cases of job scheduling.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

N/A

**Comment by ninjaginja** [comment]
great topic @kayere . (Just one small note - please be sure to reference 'Node.js' with a capital 'N' in your article.)
