### ISSUE TITLE
How to make a Command Line Interface (CLI) using NodeJS

### ISSUE THREAD

**Issue by katungi** [section-io/engineering-education#414]
### Brief Summary: 
CLI's are a vital part of modern development. They are used to make interactive terminal interfaces for a wide range of technologies and products.
In this article, the aim is to introduce the basics of making a CLI application and some useful npm packages that help in the development of CLI's. The reader will also build a simple application to get started.

### Key Takeaways: 
By the end of the article, the reader will be able to:

1. Understand the basics of CLI applications
2. Set up a node JS environment for CLI applications.
3. Use some popular npm packages like [chalk](https://www.npmjs.com/package/chalk), [ora](https://www.npmjs.com/package/ora), and [inquirer](https://www.npmjs.com/package/inquirer)
4. Build a simple CLI application

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @katungi

**Comment by katungi** [comment]
Thanks @ninjaginja. I will bear that in mind
