### ISSUE TITLE
List transformations in JavaScript

### ISSUE THREAD

**Issue by geoffrey45** [section-io/engineering-education#415]
### Brief Summary: 
Transforming objects and arrays is common in software development. We'll look at looping, extracting and filtering objects and arrays in JavaScript.

### Key Takeaways: 
The reader will understand:
- nesting objects and arrays
- Looping through objects and arrays using for loop
- Looping with _.each()
- looping and extracting arrays using _.map()
- _.map() vs _.each()
- using _.filter()

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @geoffrey45
