### ISSUE TITLE
Getting started and understanding Materialize CSS

### ISSUE THREAD

**Issue by CodeLeom** [section-io/engineering-education#418]
### Brief Summary: 
Materialize CSS is a UI component library that is created with CSS, JavaScript, and HTML. It is created and designed by Google. Materialize CSS is also known as Material Design. It is a design language that combines the classic principles of successful design along with innovation and technology. Google's goal is to develop a system of design that allows for unified user experience across all their products on any platform.

### Key Takeaways: 
You will learn how to write fewer CSS codes, achieve responsive design, and turn your UI design into a world-class functional code.

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @CodeLeom . Please be sure to include some hands-on examples.

**Comment by CodeLeom** [comment]
Sure, I will include

**Comment by CodeLeom** [comment]
@ninjaginja can this issue be reopened? while I start working on the article
