### ISSUE TITLE
Ransomwares and how you can protect yourself

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#420]
### Brief Summary: 

Ransomware is malicious software that threatens to publish the victim's data or to encrypt important, predetermined files with a password unless a ransom is paid.
Starting from around 2012 the use of ransomware scams has grown internationally very fast.
In this article, the aim is to introduce the concept of a Ransomware, how it works, talk about its history, and how to protect yourself against it. 

### Key Takeaways: 

- the reader will learn how Ransomware works and the attack method.
- he will have an overview of popular attacks.
- the best solutions to protect himself against Ransomware.
and a lot more.

### References: 

https://en.wikipedia.org/wiki/Ransomware

**Comment by ninjaginja** [comment]
@ahmadmardeni1 This topic has already been covered in previous articles. Please be sure to cross-reference the content library so we can ensure that each article brings unique value.

**Comment by ahmadmardeni1** [comment]
I saw that one but he was talking about anti-malware and he didn't deep into ransomware, how it works etc..

**Comment by ahmadmardeni1** [comment]
@ninjaginja I saw that one but he was talking about anti-malware and he didn't deep into ransomware, how it works etc..

**Comment by ninjaginja** [comment]
Yes, it's also mentioned in [this article](https://www.section.io/engineering-education/industry-4.0-and-cybersecurity/). If you feel that you can bring an original perspective to the content beyond what users can find on Wikipedia (or other sources), then please feel free to proceed.

**Comment by ahmadmardeni1** [comment]
@ninjaginja  Okay, Thank you.
