### ISSUE TITLE
Particle Effect With Particle.js

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#421]
### Brief Summary: 
In this tutorial, I’m going to talk about particles.js, a javascript library that let you create a dynamic particle effect on your webpage.

### Key Takeaways: 
1. Installation and Usage
2. Setup
3. Coding
4. Moving some particles
5. Output
### References: 

'N/A'.)

**Comment by ninjaginja** [comment]
great topic @kimkimani

**Comment by kimkimani** [comment]
Replaced [Particle.js](https://github.com/VincentGarreau/particles.js/) with [Tsparticles](https://github.com/matteobruni/tsparticles). they kind of do almost the same effect.
Particle.js haven't been maintained and got some bugs. Tsparticles has more cool features.
Hope that will be fine.
