### ISSUE TITLE
Bitdefender Antivirus plus

### ISSUE THREAD

**Issue by gitau40** [section-io/engineering-education#429]
### Brief Summary: 
Bitdefender is an Antivirus Software that is useful for only windows devices. It can cover a maximum of 3 devices. Furthermore, it is very helpful for safety from ransomware. You can also get privacy tools and a VPN. It is very helpful and has several features for the users. You can also manage passwords with the help of Bitdefender.
### Key Takeaways: 
By the end of the article the reader will be able to:
1.	Know the associated devices 
2.	User can also know a few features of this software
3.	It also enables the availability of privacy tools. 
4.	User can get info about password protection
5.	User can also know the VPN availability

### References: 
https://www.pcmag.com/reviews/bitdefender-antivirus-plus
https://www.tomsguide.com/reviews/bitdefender
https://www.techradar.com/reviews/bitdefender-2020

**Comment by ninjaginja** [comment]
@gitau40 Thank you for the topic suggestion. We prefer not to publish reviews/opinion pieces on commercial software products. If there's a particular technology in this area that you'd like to take a deeper dive into, please feel free to make a new suggestion. I'm going to close this issue.
