### ISSUE TITLE
Python Database Programming : SQLite

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#430]
### Brief Summary: 

**SQLite** is a lightweight database that can provide a relational database management system with zero-configuration, In general, it is a server-less database that you can use within almost all programming languages including Python.
In this tutorial, I will cover everything about SQLite using Python.

### Key Takeaways: 

- Installation and usage
- Setup 
- Creating tables 
- Insert/Select/Update/Delete Records

### References: 

N/A

**Comment by ninjaginja** [comment]
great topic @ahmadmardeni1
