### ISSUE TITLE
Deeper understanding on the Border Gateway Protocol (BGP)

### ISSUE THREAD

**Issue by faith601** [section-io/engineering-education#433]
### Brief Summary: 
BGP (Border Gateway Protocol) is the protocol that is the basic principle of the global routing system of the Internet. Without it, we will not be able to do a Google search or send an email. The BJP has created network stability by guaranteeing that routers can adapt to route failures: when one route goes down, a new route is found quickly. Internally, the BJP has a huge set of criteria for determining the best path.

### Key Takeaways: 
By the end of the article the reader will be able to:
1.	Know about what is BGP
2.	How does BGP work
3.	Importance of BGP
4.	Why we use BGP in MPLS?
5.	How does BGP choose the best path?

### References: 
https://blog.stackpath.com/border-gateway-protocol/
https://www.networkcomputing.com/networking/bgp-fundamentals
https://www.imperva.com/blog/bgp-routing-explained/

**Comment by ninjaginja** [comment]
@faith601 thanks for the topic suggestion. We already have a couple [articles published on BGP](https://www.section.io/engineering-education/search/?q=bgp). Please be sure to cross-reference against existing articles, in progress articles, and approved topic suggestions. 

I'm going to close this issue.
