### ISSUE TITLE
5 Real Life Use Cases of Natural Language Processing (NLP)

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#441]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The world is moving towards automation. Automated things such as self driving cars and Google Assistant are coming in out lives to make live easier. Natural Language Processing is key to this development, and it involves the manipulation of Text, Speech etc through computational power by using various software. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understanding Natural Language Processing
2. Natural Language Processing (NLP) vs. Natural Language Understanding (NLU) vs. Natural Language Generation (NLG
3. Application of NLP in:
a) Grammar Checkers
b) Chatbots 
c) Search Autocorrect and Autocomplete
d) Language translator
e) Analytics Dashboards

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.tutorialspoint.com/natural_language_processing/natural_language_processing_applications_of_nlp.htm
http://www.ai.mit.edu/courses/6.034b/language.pdf
analyticsvidhya.com/blog/2020/07/top-10-applications-of-natural-language-processing-nlp/

**Comment by ninjaginja** [comment]
good topic @EKahuha . I might suggest refining the title to be a bit more pinpointed on what you intend to cover - perhaps something like '5 Real Use Cases Using NLP'

**Comment by EKahuha** [comment]
Suggestion noted.
