### ISSUE TITLE
Tableau Vs. Power BI

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#450]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Microsoft Power BI and Tableau are the two front-runners in the data visualization and business intelligence (BI) software industry. Both offer advanced reporting and visualization capabilities. Each has its own strengths and weaknesses when it comes to use in business intelligence. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1) Overview of Tableau
2) Overview of Power BI
3) Key Differences 
       a) Integration
       b) data visualizations and dashboard
       c) data connectivity 
       d)Analytics 
       e)Data Sources
4) Which is better for business intelligence?  

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.smetricinsights.com/wp-content/uploads/2019/05/Tableau-VS-QlikView-VS-Power-BI-2019-Update.pdf
https://technologyadvice.com/blog/information-technology/power-bi-vs-tableau/#:~:text=Power%20BI%20comes%20at%20a,intelligence%20to%20enhance%20their%20analytics.
https://www.selecthub.com/business-intelligence/tableau-vs-qlikview-vs-microsoft-power-bi/

**Comment by ninjaginja** [comment]
@EKahuha Good topic. The only caveat is to make sure that your content is different enough from the cited sources (where users can already get some of this information). Be sure that you're providing unique value  to the reader.
