### ISSUE TITLE
Basics of Transfer Learning 

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#451]
### Brief Summary: 

When we as human beings learn new things, we do not always learn from scratch. We often transfer past knowledge and apply it to new tasks. For example, knowing how to ride a bike makes it easier to learn how to ride a motorcycle. 
In the quest to achieve artificial general intelligence, transfer learning can be applied to machine learning models. We look at the theoretical concepts of transfer learning.

### Key Takeaways: 

Reader should be able to:

1.  Understand the theory behind transfer learning
2. Appreciate the need for transfer learning
3. Learn a few transfer learning approaches 
4. Explore a few applications of transfer learning

### References: 

1. https://towardsdatascience.com/a-comprehensive-hands-on-guide-to-transfer-learning-with-real-world-applications-in-deep-learning-212bf3b2f27a

2. https://machinelearningmastery.com/transfer-learning-for-deep-learning/

**Comment by ninjaginja** [comment]
good topic @collins-a
