### ISSUE TITLE
Kotlin collections

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#452]
### Brief Summary: 
Kotlin has a rich and wide variety of collections. All of them have their own special properties and this article aims to demystify them. It will help new learners get familiar with them and some of their basic methods.

### Key Takeaways: 
1. What are Kotlin collections
2. Properties of Kotlin  Collections
3. Differences between various collections
4. Examples of Collection methods

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @LinusMuema
