### ISSUE TITLE
A Tutorial on OpenShift

### ISSUE THREAD

**Issue by jimmykimani26** [section-io/engineering-education#456]
### Brief Summary: 
Red Hat OpenShift offers automated installation, upgrades, and lifecycle management throughout the container stack—the operating system, Kubernetes and cluster services, and applications—on any cloud
Red Hat OpenShift helps teams build with speed, agility, confidence, and choice. Code in production mode anywhere you choose to build. Get back to doing work that matters.
Red Hat OpenShift is focused on security at every level of the container stack and throughout the application lifecycle. It includes long-term, enterprise support from one of the leading Kubernetes contributors and open-source software companies.

### Key Takeaways: 
1.	Readers will learn about “Super simple management in the cloud or anywhere.”
2.	Readers will learn about “Build Fast, Ship Fast, and Deploy everywhere with OpenShift.”
3.	Readers will learn about “Building with Kubernetes trusted by Red Hat.”
4.	Readers will learn about the “Benefits of OpenShift for Developers.”
5.	Readers will learn about the “Benefits of OpenShift for IT Operations.”
6.	Readers will learn about the “Benefits of OpenShift for Business Leaders.”

### References: 
https://www.openshift.com

**Comment by ninjaginja** [comment]
@jimmykimani26 Thank you for the topic suggestion, but we'd prefer not to publish an article on a commercial product that is somewhat competitive to Section. If you'd like to go a layer deeper and do a tutorial on Kubernetes, that would be okay :)

**Comment by jimmykimani26** [comment]
@ninjaginja Thank you for the insights, sure I can focus on writing a tutorial on Kubernetes. I will change my focus and emphasize more on Kubernetes.
