### ISSUE TITLE
IBM WebSphere application server

### ISSUE THREAD

**Issue by jimmykimani26** [section-io/engineering-education#457]
### Brief Summary: 
The article will be a How-To Guide on how the IBM WebSphere application server works. 
IBM WebSphere Application Server supports microservices and standards-based programming models. This design help users modernize at their own pace, gain greater visibility across workloads, analyze enterprise applications, and advance the journey to Kubernetes.  
### Key Takeaways: 
1.	Readers will learn about “How to use Visibility Feature?” to get real-time visibility and application awareness across multi-cloud workloads.
2.	Readers will learn about “How to use Application Analysis Feature?” to use the administrative console for analyzing applications and generating detailed reports.
3.	Readers will learn about “How to use Logging & Monitoring Feature?” to see cloud-ready log analysis and monitor actionable insights in real-time, at cloud scale.
4.	Readers will learn about “How to move to Containers with IBM WebSphere Application Server advanced feature?” to learn new ways to get to containers.

### References: 
https://www.ibm.com/cloud/websphere-application-server

**Comment by ninjaginja** [comment]
@jimmykimani26 Please see comment on #456. The same applies here.
