### ISSUE TITLE
Stochastic Gradient Descent Optimized Linear Classifier in Python

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#462]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Stochastic gradient descent is an optimization algorithm used extensively across the field of machine learning and deep learning. We will build a linear classifier from scratch and understand the optimization process using the SGD optimizer.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Build linear classifier from scratch using SGD optimizer
2. Build SGD optimizer from scratch
3. Understand linear classifiers and their applications
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
cool topic @lalith1403
