### ISSUE TITLE
Android Custom Views - Part 2(Extending a View Subclass)

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#464]
### Brief Summary: 
This article covers the second approach of creating custom views in android. This is by extending a View Subclass such as button.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Learn how to extend View subclasses.
2. Understand how to add functionality to existing views.
3. Understand how to manipulate methods related to a particular view to meet one's needs.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
consolidated under #463
