### ISSUE TITLE
Bitnami Application Catalog

### ISSUE THREAD

**Issue by minnehnjeri** [section-io/engineering-education#465]
### Brief Summary: 
The article reviews the Bitnami Application Catalog software.
Bitnami is the leader in application packaging providing the largest catalog of click to deploy applications and development stacks.  The Bitnami Application quickly and easily launch your favorites on your servers or deploy to every major cloud environment. This allows the application to choose from local installers, single VMs, multi-tier VMs, container images, or Kubernetes Helm charts.

### Key Takeaways: 
1.	Readers will explore and compare various Developer Tools.
2.	Readers will explore and compare integrated development environments among various Infrastructures.
3.	Readers will explore and compare different kinds of website builders among various Applications.

### References: 
https://bitnami.com/stacks

**Comment by ninjaginja** [comment]
@minnehnjeri  Thank you for the topic suggestion, but we'd prefer not to publish an article on a product that has competing elements to Section's offerings. If you'd like to go a layer deeper and dive into a tutorial on any of the underlying applications or how to make infrastructure decisions, that would be okay :)
