### ISSUE TITLE
A Push Towards More Sustainable AI with Tiny Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#473]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Tiny machine learning (TinyML) is at the intersection of embedded devices and machine learning. It is being touted as "the next AI revolution". However, the carbon footprint of AI has been increasing with the evolution of AI. There is a need for more energy-efficient computing. This is one of the challenges TinyML can address. In this article, we aim to dissect TinyML. 

### Key Takeaways: 

Reader should:
1. Understand what Tiny ML is and how it works 
2. Grasp the motivation and need for Tiny ML
3. Explore the potential and benefits of tiny machine learning
4. Understand the fundamentals of tiny machine learning
5. Be aware of examples/ real-world applications of Tiny ML

### References: 

1. R. Sanchez-Iborra and A. F. Skarmeta, "TinyML-Enabled Frugal Smart Objects: Challenges and Opportunities," in IEEE Circuits and Systems Magazine, vol. 20, no. 3, pp. 4-18, thirdquarter 2020, doi: 10.1109/MCAS.2020.3005467.

2. https://towardsdatascience.com/tiny-machine-learning-the-next-ai-revolution-495c26463868

**Comment by ninjaginja** [comment]
good topic @collins-a . Rather than taking a vague approach with the title, I'd recommend taking a more targeted approach. For example, if you're focusing in on sustainability, perhaps the title could be something like, "A Push Towards More Sustainable AI with Tiny Machine Learning"
