### ISSUE TITLE
House price prediction using Linear Regression

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#474]
### Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

House price prediction is an interesting problem to work with. We will use scikit learn library to predict the prices of houses based on multiple features. Solving this problem gives an insight into solving various ML problems using the scikit learn library.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
The outcomes of the article are:
1. Create a linear regression model using scikit learn and understand the machine learning pipeline involved.
2. Perform exploratory data analysis for the dataset and understand the dataset statistically.
3. Preprocessing of dataset and converting categorical values into integers using the labelEncoder function in scikit-learn.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
Boston Housing Dataset: https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

**Comment by ninjaginja** [comment]
very cool @lalith1403 . Look forward to reviewing :)
