### ISSUE TITLE
Building a python package and publishing on PyPi

### ISSUE THREAD

**Issue by jamessandy** [section-io/engineering-education#475]
### Brief Summary: 
This tutorial will give readers a detailed guide on packages in python and how to build one, it will take them through on how to write and structure their code, structure and package it, and finally how to publish it on PyPI for their general python community. It will help developers know how to push as their efficient chunk of codes so other devs can use it too. 

### Key Takeaways: 
Understand Python Packages better
Build their package
Publish it on PyPI

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @jamessandy

**Comment by jamessandy** [comment]
thanks @ninjaginja is this like an approval?

**Comment by ninjaginja** [comment]
yes, it is an approval :)

**Comment by ninjaginja** [comment]
merged under #579
