### ISSUE TITLE
How to control dark mode in React Native using Redux

### ISSUE THREAD

**Issue by Worawat101** [section-io/engineering-education#485]
### Brief Summary: 
This tutorial aims to demonstrate the use of the Redux mechanism to toggle dark mode on React Native. The dark mode configurations will be applied to React Navigation as well as components from the React Native Paper and React Navigation.
### Key Takeaways: 
- Better understanding of Redux.
- Learn how to use dark mode theme on components from react native paper library
- Learn how to add dark mode theming configuration to React Navigation.

### References: 
https://callstack.github.io/react-native-paper/
https://reactnavigation.org/docs/themes/

**Comment by ninjaginja** [comment]
sounds like a great tutorial @Worawat101

**Comment by Worawat101** [comment]
@ninjaginja thank will start soon
