### ISSUE TITLE
How to prepare for coding interviews

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#490]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Tech comanies usually have a rigorous hiring process over multiple rounds of interviews and tests. This tutorial will be a guide on how to prepare for software engineer/SDE interviews in these tech companies. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand the recruitment process followed by tech companies.
2. Understand how to prepare and do well in the first round(coding test)
3. Understand how face-to-face interviews are conducted and how to prepare for them.
4. A list of resources to help prepare for coding interviews.  

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
@adithbharadwaj good topic. As you're developing this content, might be worth looking for opportunities to link to existing EngEd articles, as I know there have been several mentions of prep for coding interviews across various articles.

**Comment by adithbharadwaj** [comment]
> @adithbharadwaj good topic. As you're developing this content, might be worth looking for opportunities to link to existing EngEd articles, as I know there have been several mentions of prep for coding interviews across various articles.

Sure @ninjaginja
