### ISSUE TITLE
Basics of Convolution Neural Networks (CNNs)

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#493]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Convolutional Neural Networks (CNN) is a technique in deep neural networks commonly applied to analyzing visual images. 
CNNs have been applied in:
1. Image and Video recognition.
2. Image classification.
3. Natural Language Processing
4. Medical image analysis.
5. Recommender Systems

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of the article, the reader should be able to understand:
1. The architecture of Convolutional Neural Networks.
2. Convolutional Neural Networks Optimization methods.
3. Applications of Convolution Neural Networks

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. Murphy, J. (2016). An overview of convolutional neural network architectures for deep learning. Microway Inc.
2. Bambharolia, P. (2017). Overview of Convolutional Neural Networks. In Conference: International Conference on Academic Research in Engineering and Management (pp. 25-31).

**Comment by ninjaginja** [comment]
good topic @Bayler. I did reopen the issue for your other topic suggestion on a related topic. I'd suggest focusing on one at a time so that we can ensure that all feedback is applicable to subsequent articles.

**Comment by Bayler** [comment]
Noted @ninjaginja 

Let me work finish on the reopened issue then start writing on this issue
