### ISSUE TITLE
CSS-IN-JS Solutions

### ISSUE THREAD

**Issue by CodeLeom** [section-io/engineering-education#497]
### Brief Summary:
This article will cover various techniques a developer can use in defining styles within app components during development than maintaining multiple stylesheets for a single app component.

### Key takeaways:
CSS and CSS-in-JS Comparison
CSS-IN-JS Solutions
JSS
Styled Components
Styletron
Emotion
Material UI

### Refrences:
https://www.npmjs.com/package/@material-ui/styles
https://emotion.sh/docs/install
https://5bb1495273f2cf57a2cf39cc--emotion.netlify.com/
https://www.styletron.org/getting-started
https://github.com/styled-components/styled-components#example
https://www.styled-components.com/docs/basics#installation
https://codesandbox.io/s/z21lpmvv33
https://cssinjs.org/setup

**Comment by ninjaginja** [comment]
good topic @CodeLeom, but please be sure that the draft that you submit for approval has been properly proofed for grammar and readability. The phrasing of this topic suggestion does not make sense, although I understand the topic that you intend to cover. We do not provide editing services, so we ask that all articles be submitted in a final, publish-able state.
