### ISSUE TITLE
Top 7 Open Web Application Security Vulnerabilities

### ISSUE THREAD

**Issue by CodeLeom** [section-io/engineering-education#498]
### Summary:
This article will cover topics on common security vulnerabilities on web applications according to the Open Web Application Security Project

### Key takeaway:
At the end of this article, the readers will be able to understand the various security vulnerabilities to their web apps and how to prevent them:
Injection flaws 
Broken Authentication
Broken Access control
Security Misconfiguration
Cross-Site Scripting
Components with vulnerabilities
Sensitive Data Exposure

### References:
https://owasp.org/www-project-top-ten/
External sources from google

**Comment by ninjaginja** [comment]
This is not a topic that we're looking for additional coverage on at this time.
