### ISSUE TITLE
Prototyping Machine learning models with streamlit

### ISSUE THREAD

**Issue by jamessandy** [section-io/engineering-education#499]
### Brief Summary: 
Most times machine learning engineers build models and will need to build a web or mobile app to prototype their models which is another stress on its own, this tutorial will show readers how to quickly prototype their ML models on web applications easily.

### Key Takeaways: 
1. Introduction to streamlit
2. Setting up and installation of streamlit
3. Building an app with streamlit

### References: 
https://www.streamlit.io/

**Comment by ninjaginja** [comment]
cool topic @jamessandy
