### ISSUE TITLE
Breaking Down Apache Pulsar vs Kafka 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#502]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The options for application-to-application communication have grown exponentially, including the addition of several very powerful open source solutions. Apache Pulsar is an open-source multi-tenant, high-performance messaging solution. Apache Pulsar is a fast-growing alternative to Kafka. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Overview of apache pulsar
2. Architecture 
3. Geo-Replication
4. Use cases 
5. Apache Pulsar or Apache Kafka: which is better? 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha . My only suggestion would be to make the article more practitioner focused, or take a specific angle with the content. For example, perhaps you focus in on the "Breaking Down Apache Pulsar vs Kafka" arguments? Try to approach your content from the perspective of real challenges that engineers are facing, and hence content they are seeking out.

**Comment by EKahuha** [comment]
Thank you @ninjaginja. I Have noted the suggestion.
