### ISSUE TITLE
Making Simple API Requests using Volley in Android.

### ISSUE THREAD

**Issue by BrianaNzivu** [section-io/engineering-education#506]
### Brief Summary: 
Volley is a HTTP library that makes networking in Android Applications easy. Most developers use APIs to obtain information that is constantly changing or large in size rather than having to write their own information. This makes it easy for developers in that it saves time, effort, and space.

### Key Takeaways: 
1.The reader should be able to understand what is Volley and how it works.
2.The reader should be able to understand what is an API and how it works.
3.The reader should be able to understand what a Rest API and JSON file are.
4.The reader should be able to make API calls using Volley.

### References: 
https://www.geeksforgeeks.org/volley-library-in-android/

**Comment by ninjaginja** [comment]
good topic @BrianaNzivu
