### ISSUE TITLE
Choosing between Firebase and MongoDB

### ISSUE THREAD

**Issue by kenny98dev** [section-io/engineering-education#508]
### Brief Summary: 
Developers usually have problems when selecting the right  database for their applications or website. There are various databases which can be integrated  to applications or websites and the developer should have full knowledge of each database before integrating on the application. In this article, I am going to discuss about Firebase and MongoDB databases.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.Features of both MongoDB and Firebase databases.
2.Advantages and disadvantages of both MongoDB and Firebase databases.
3.Differences between MongoDB and Firebase.

**Comment by ninjaginja** [comment]
Good topic @kenny98dev . We do have some existing content around MongoDB and Firebase, but not a direct comparison of the two. There should be opportunities for you to link to this content within your article :)

**Comment by kenny98dev** [comment]
so should i continue writing the article?

**Comment by hectorkambow** [comment]
> so should i continue writing the article?

@kenny98dev Yes that was an approval - we were just asking to take in mind the existing (relating articles) to see where you could reference them in your article and to make sure to avoid any major overlap. 🚀

**Comment by kenny98dev** [comment]
okay. Thanks

**Comment by ninjaginja** [comment]
PR closed due to inactivity
