### ISSUE TITLE
Android Recycler Views

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#513]
### Brief Summary: 
In almost every android application, we need to display a list of data dynamically. While this has been simplified by using a `ListView,` it is impossible to add custom layouts to it. This is a problem when we want to add images to the list. That is where RecyclerViews come in handy. This article goes through how to get started with RecyclerViews and the other solutions they offer.

### Key Takeaways: 
1. What is a RecyclerView
2. The components of a RecyclerView
3. How RecyclerViews work
4. How to create a RecyclerView

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @LinusMuema
