### ISSUE TITLE
How Ansible Playbook Works 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#515]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Ansible is an open-source automation tool that handles application deployment, configuration management, intra-service orchestration, and provisioning. It is an incredibly useful tool for DevOps, since it saves on time and eliminates repetitive tasks. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
What is Ansible Playbook
Benefits of Ansible Playbook
How Ansible Playbook Works 
Ansible Playbook Examples

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
This topic has already been covered in this article - https://www.section.io/engineering-education/it-automation-using-ansible/.

**Comment by hectorkambow** [comment]
Lets try to find a different topic or tweak this one enough to add new sufficient value to the community. 🚀 
@EKahuha
