### ISSUE TITLE
Perceptron Algorithm: A Hands-On Introduction

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#520]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The perceptron algorithm was the first algorithm to introduce weights. It played a crucial role in shaping the direction of neural networks. In this article, I will discuss the structure of a neuron, the activation function used, and finally, we will implement the perceptron algorithm from scratch using Python.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Perceptron algorithm in depth
2. Weight updation rule
3. Code using the basic library numpy.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A.')
N/A

**Comment by ninjaginja** [comment]
very cool topic @lalith1403

**Comment by lalith1403** [comment]
It is called the Perceptron algorithm. Let me know if any modifications are required in the title.

**Comment by ninjaginja** [comment]
Ah, sorry. I saw the first sentence in the description spelled as 'perception' and just assumed a typo in the title.

**Comment by lalith1403** [comment]
Sorry about that. Autocorrect did that.
