### ISSUE TITLE
Logging with Winston

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#525]
### Brief Summary: 
Logging is the process of writing information into log files. Log files include information about various events that happened in an operating system, software, or communication. Structuring application logging in Node.js is critical for monitoring and troubleshooting your project. A great use case for logging would be if, for example, you have a bug in your system, and you want to understand the steps that led up to its occurrence. This article will talk about logging within the context of Winston.

### Key Takeaways: 
- Why bother with logging
- Winston vs Morgan vs Bunyan vs Log4js
- How to Use The Winston Logger

### References: 
https://www.npmjs.com/package/winston

**Comment by ninjaginja** [comment]
great topic @kimkimani

**Comment by ninjaginja** [comment]
@kimkimani are you still working on drafting this article?

**Comment by ninjaginja** [comment]
@kimkimani Could you please elaborate on the 'issue' with the PR process? We're actively working to streamline things and looking for all feedback that could help improve processes. cc @hectorkambow
