### ISSUE TITLE
Javascript Higher-order Functions

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#526]
### Brief Summary: 
Higher-order functions are functions that take other functions as arguments or return functions as their results. Often referred to as a callback function, because it is called back by the higher-order function. This is a concept that Javascript uses a lot.

### Key Takeaways: 
To understand high order functions well, I'll discuss a short concept of functional programming, arrow functions
 and first-class functions such as declaring a function, assigning functions to variables, and functions as parameters

Then dive into higher-order functions (explained with examples).
They include:
- `.map`
- `.filter`
- `.reduce` and
- `.forEach`

### References: 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by ninjaginja** [comment]
@kimkimani  - good topic, but please be sure that your examples are sufficiently unique from the docs.
