### ISSUE TITLE
Getting started with Data Visualization using Pandas

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#530]
### Brief Summary: 
**Data Visualization** is the process of placing data into patterns in order to understand it better, **Pandas** library is powerful because it is built on **Matplotlib** and it allows us to do data manipulation and analysis.
Basically, this tutorial will be for beginners who are interested in **data science** and I will use **Pandas** with **Python**.

### Key Takeaways: 
- An overview of **data science** and **Pandas** library.
- How to handle the datasets and importing them.
- The different types of **plots** and **charts** and how to implement them (line chart/Scatter Plot/Bar Chart/...).

Note: the article about pandas [here](https://www.section.io/engineering-education/data-analytics-using-pandas/) talks about the basics of **Analysis**, mine will be about **Visualization** after analyzing data, and the points I'm going to write about does not exist in that article.

Note: I'm thinking of writing part 2 of this tutorial which will be about **Plotly** but I'm not sure yet.
### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Note: the article about pandas [here](https://www.section.io/engineering-education/data-analytics-using-pandas/) talks about the basics of **Analysis**, mine will be about **Visualization** after analyzing data, and the points I'm going to write about does not exist in that article.

**Comment by ninjaginja** [comment]
Great topic @ahmadmardeni1 , and thanks for including the note that explains how your article will differ from reference content 👍
