### ISSUE TITLE
INTRODUCTION TO AVL TREES IN C++

### ISSUE THREAD

**Issue by bloodprashure** [section-io/engineering-education#531]
### Brief Summary: 
AVL trees are self-balancing binary search trees where the difference between heights of the left and right subtrees are not more than one. Binary search trees have a comparable complexity to linear search. This has led to the need for AVL trees. This article will portray the implementation of AVL trees in C++ and how it has reduced the complexity for many problems.

### Key Takeaways: 
•  Need for AVL Trees
•  Tri-node restructuring
•  Insertion in AVL Trees in C++
•  Deletion in AVL Trees in C++

### References: 
•  Data Structures and Algorithms in C++ by Michael T Goodrich

**Comment by ninjaginja** [comment]
Sounds like an interesting topic @bloodprashure . Please open a new PR for review once you have your article in a polished, publishable state.

**Comment by bloodprashure** [comment]
I shall @ninjaginja, thanks!
