### ISSUE TITLE
Cost Optimization and Use Cases of Amazon S3 Intelligent Tiering 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#535]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
S3 Intelligent Tiering automatically optimizes storage costs for data with unknown or changing access patterns. It is the perfect solution for optimizing storage costs for dynamic data without introducing operational overhead or impacting performance. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What is Intelligent Tiering
2. Why S3 Intelligent Tiering?
3. Use Cases of Intelligent Tiering
  Unpredictable Workloads
  Changing Data Access Patterns 
  Managing Storage Patterns
4.  Cost Optimization

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
apologies for the delay @EKahuha , I must have missed this one earlier. This sounds like an interesting topic that could bring value to our audience :)
