### ISSUE TITLE
How JavaScript Promises Work Under The Hood.

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#536]
### Brief Summary: 
This guide takes the reader through:
- Why asynchronous Programming is needed in JavaScript.
- How promises fulfil this need.
- How promises are implemented under the hood.

### Key Takeaways: 
- Event Loop in JavaSctipt.
- The Callback Queue.
- The Job Queue.
- Promise Objects and their implementation.

### References: 
Front End Masters.
MDN Web Docs

**Comment by ninjaginja** [comment]
@adrianmurage I'd suggest holding off on this article until you've gone through the review process on your other article. This will help ensure that you're incorporate any/all feedback into your next article and should help to reduce review time and revision rounds.

**Comment by adrianmurage** [comment]
@ninjaginja 
I will. I was opening this to get the go ahead.
To allow me to do preliminary planning, research and thought organization in preparation for the actual writiting.

**Comment by ninjaginja** [comment]
Sounds good

**Comment by HarishTeens** [comment]
Hey @adrianmurage , are you still working on it. It sounds like a really exciting topic.

**Comment by adrianmurage** [comment]
Yes, I am.
It really is! It's particularly challenging because the method I choose to use to explain the concepts is visual and so I have to come up with my own flow charts. It has taken some time but I should be done by next week : )

**Comment by HarishTeens** [comment]
That's so thoughtful, waiting for the article :raised_hands:

**Comment by ninjaginja** [comment]
@adrianmurage are you still working on this article?

**Comment by adrianmurage** [comment]
@ninjaginja Yes I am
I broke it down to 
1. [What Happens When JavaScript Runs My Code?](https://www.section.io/engineering-education/js-execution-under-the-hood/)
2. [How JavaScript Uses Web Browser APIs To Achieve Asynchronisity](https://github.com/section-io/engineering-education/issues/742)

And now finally How JavaScript Promises Work Under The Hood.
I realized it would be a pretty long article if I covered all those build up topics in the same article 
Hence the delay.

**Comment by adrianmurage** [comment]
>
> @adrianmurage are you still working on this article?

I should have a PR up in the course of the week

**Comment by ninjaginja** [comment]
ok, so is it okay to go ahead and close this issue since we've already published one and the other is contained under #742?

**Comment by adrianmurage** [comment]
No, this is
No.3 How JavaScript Promises Work Under The Hood.

The last bit
Hence my next PR will reference this issue

**Comment by ninjaginja** [comment]
ah, okay. I see. thank you

**Comment by ninjaginja** [comment]
@adrianmurage. Are you still planning to submit a PR for this article?

**Comment by adrianmurage** [comment]
Yes 
However we can close it until I do
