### ISSUE TITLE
The Role of Artificial Intelligence for Smarter Cybersecurity 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#540]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Artificial intelligence (AI) and machine learning (ML) are playing an increasing role in cybersecurity. Security tools are analyzing data from millions of cyber incidents, and using it to identify potential threat. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. How machine learning and artificial intelligence improve cybersecurity through:
 a)Network security
 b)Data centers
c) Threat hunting
d) Vulnerability management 
2. Negative effect of AI on cybersecurity 
3. The future of AI and Cybersecurity 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @EKahuha
