### ISSUE TITLE
Building a To-Do list web application using Flask and Firebase

### ISSUE THREAD

**Issue by keerthivarumbudy** [section-io/engineering-education#541]
### Brief Summary: 
This article will be a tutorial to build a simple interactive To-Do list web application using Flask server and Firebase database. It will explore the CRUD operations which are fundamental to building any dynamic website.
### Key Takeaways: 
User will be able to understand -
1. how to use flask server to develop a website
2. how to incorporate firebase database into a website
3. how to perform CRUD operations on firebase
4. how to use Jinja to display flask variables on the front-end
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://firebase.google.com/docs/reference/admin/python

**Comment by ninjaginja** [comment]
good topic @keerthivarumbudy

**Comment by HarishTeens** [comment]
Hey @keerthivarumbudy , are you still working on this topic? seems like a really useful topic

**Comment by keerthivarumbudy** [comment]
Yes, I'm currently working on it

Regards,
Keerthi V

**Comment by ninjaginja** [comment]
PR was closed due to inactivity
