### ISSUE TITLE
Deciding between Cloud Spanner and Microsoft CosmosDB

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#542]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
With the advancements that are already happening within cloud computing, tons of improvements are bound to happen in the future. One such development includes the initiation of SQL based databases that provide the users with a customized experience of storing, sorting, and processing heavy bounds of raw data. There are many database providers out there and most of them work on various nodes of the SQL database engines such as Google Spanner and Microsoft CosmosDB. Deciding on which cloud database to use is usually an uphill task. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Salient features of Cloud Spanner and Microsoft CosmosDB 
2. Merits and Demerits of Cloud Spanner and Microsoft CosmosDB
3. Differences between Cloud Spanner and Microsoft CosmosDB
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
@EKahuha Sounds like a good topic, but please be mindful of grammar and readability. The description and bullet points that you've provided here suggest that you might want to run your draft through peer edit (or external editing service) prior to submitting a PR for this article. We do not provide extensive editing services and require that all drafts submitted are in a ready-to-publish state. I just want to provide this feedback upfront to avoid potential rejection of any drafts that you may submit.
