### ISSUE TITLE
Creating Command Line Interface (CLI) applications using React.Js

### ISSUE THREAD

**Issue by katungi** [section-io/engineering-education#546]
### Brief Summary: 
CLI applications using Node.js are amazing and very easy to make. I did an article on how to do that [here](https://www.section.io/engineering-education/create-a-nodejs-cli/). The more CLI applications become popular, the more the need for them to be better, more responsive and contain more detail. With react, you can create good looking CLI's with styling and even render images. In this article, that is exactly what we will look at. 

### Key Takeaways: 

- The core difference between using Node.js and React.js. 
- Getting started with building good looking components and rendering them to the terminal.
- Why you should use React.js 
- Examples of popular applications and companies already using React.js for their CLI apps
- Using React INK to render components on the terminal.
- Build a simple application with React.js and React INK

### References: 
1. Vadimdemedes/ink. Retrieved October 28, 2020, from https://github.com/vadimdemedes/ink
2. Couriol, B. (2020, August 05). Interactive Terminal Apps with Ink 3 - New Built-In Hooks, Suspense and React Dev Tool Support. Retrieved October 28, 2020, from https://www.infoq.com/news/2020/08/ink3-hooks-devtool-terminal-apps/

**Comment by ninjaginja** [comment]
Great topic @katungi, and I really like how it builds on your previous content!
