### ISSUE TITLE
Introduction to Tiny AI: A New Revolution in Artificial Intelligence

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#548]
### Brief Summary: 
Tiny AI is a new revolution of artificial intelligence that focuses on reducing the computational power and amount of data used in building AI algorithms. This article aims at introducing readers to this emerging concept that can potentially shape the future of industries. 

### Key Takeaways: 
The following are important things that the reader should understand;
1. Overview of Tiny AI
2. Why we need Tiny AI
3. How Tiny AI works
4. Applications of Tiny AI
5. Challenges of the new revolution

### References: 
https://www.technologyreview.com/technology/tiny-ai/
https://www.itpro.co.uk/technology/artificial-intelligence-ai/355716/what-is-tiny-ai

**Comment by ninjaginja** [comment]
@mbaabuones this topic is already being covered in #547. Please explore a different topic area.
