### ISSUE TITLE
Transfer Learning for Deep Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#549]
### Brief Summary: 

Deep learning models need a lot of data. They may be trained on millions of data points before making predictions. This makes training very expensive. Furthermore, such models often perform only a single task. We look at how deep transfer learning can deal with these challenges. 

### Key Takeaways: 

The reader should:
1. Understand the relationship between transfer learning and deep learning.
2. Know the difference between transfer learning in traditional machine learning and deep learning.
3. Be aware of why and when to use deep transfer learning.
4. Understand the types of deep transfer learning. 

### References: 
A Survey on Transfer Learning https://www.cse.ust.hk/~qyang/Docs/2009/tkde_transfer_learning.pdf

https://towardsdatascience.com/what-is-deep-transfer-learning-and-why-is-it-becoming-so-popular-91acdcc2717a

https://towardsdatascience.com/a-comprehensive-hands-on-guide-to-transfer-learning-with-real-world-applications-in-deep-learning-212bf3b2f27a

https://machinelearningmastery.com/transfer-learning-for-deep-learning/

**Comment by collins-a** [comment]
This suggestion builds upon my previous submission on the Basics of Transfer Learning.

**Comment by ninjaginja** [comment]
Sounds good @collins-a .

**Comment by ninjaginja** [comment]
closed via #596
