### ISSUE TITLE
Using RxJava in Android

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#553]
### Brief Summary: 
RxJava has been widely adopted in Android to perform asynchronous tasks and improve the application's efficiency. This article aims to help the reader get a basic understanding of the operators in RxJava and how to integrate them into an Android application.

### Key Takeaways: 
1. What is RxJava
2. Some basic RxJava operators
3. How to use these operators in Android

### References: 
N/A

**Comment by hectorkambow** [comment]
Sounds very helpful looking forward to reviewing 🚀 
✔️
