### ISSUE TITLE
Introduction to Extended Reality (XR)

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#555]
### Brief Summary: 
Extended Reality (XR) is an immersive technology that is growing in terms of advancement and application. This concept has the potential of shaping the future of digital transformation. This article aims at providing readers with a broad understanding of this important concept.

### Key Takeaways: 
The following are important things that readers should understand;
1. Overview of Extended Reality (XR)
2. Pillars of Extended Reality-Virtual, Augmented and Mixed Reality
3. Benefits of Extended Reality
4. Extended Reality Applications
5. Challenges of Extended Reality

### References: 
https://medium.com/predict/extended-reality-is-the-frontier-of-the-digital-future-a2c05785fc72

**Comment by hectorkambow** [comment]
Very interesting topic - I think as long as we keep a developer focus in mind it should be very helpful. 
Perhaps including the types of programming languages being used in these fields. 
Current limitations.
Maybe going a bit into how it all works while explaining what it is, is seen as helpful to the audience. 
Examples of tech we have seen in the past - while setting the reader up for whats to come 🚀 
✔️  
Looking forward to it.

**Comment by mbaabuones** [comment]
@hectorkambow Thank you. I will include these aspects in the article.
