### ISSUE TITLE
Django Restful Crud API

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#557]
### Brief Summary: 
Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
This article aims to teach the reader how to create various crud APIS with django and django rest framework.

### Key Takeaways: 
Basic Django knowledge is required to understand the concept covered in this article.
1. What is Django and Django rest framework.
2. Basics of django models, urls and serializers.
3. How to create crud API using django rest generic views.
4. Serializing data using django rest serializers.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
1. Django documentation - https://docs.djangoproject.com/en/3.1/
2. Django rest framework documentation - https://www.django-rest-framework.org/
3. Inroduction to Rest APIS -  https://www.section.io/engineering-education/rest-api/

**Comment by hectorkambow** [comment]
Seems like a very helpful topic. 
Please be sure to include any prerequisites the reader would need before diving in. Any terminology needed to help the reader follow along.
Also, see if there are any EngEd articles you can link to as references.
Looking forward to it ✔️ 
@paulodhiambo
