### ISSUE TITLE
Python Generators

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#558]
### Brief Summary: 
Python generators were introduced with [PEP 255](https://www.python.org/dev/peps/pep-0255/). Generator functions are a special kind of function that return a lazy iterator. Python generators are objects that you can loop over like a list. However, unlike lists, lazy iterators do not store their contents in memory.

### Key Takeaways: 
The reader should have basic python knowledge to understand the concepts presented in this article.
1. What python generators are and how they are used.
2. How to create python generator functions and expressions.
3. How to use the python yield statement.
4. Building data pipelines with multiple generators.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
1. [Python Wiki](https://wiki.python.org/moin/Generators)

**Comment by hectorkambow** [comment]
🤔  Very interesting - seems like a very helpful article on Python Generators. 
Let please be sure to go through any past EngEd Python article to see where we can provide helpful resources for the audience. ✔️ 
Any prerequisites listed before the reader jumps in would be extremely helpful 🚀 
Looking forward to reviewing
