### ISSUE TITLE
Implementing MVVM Architecture in Android using kotlin

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#559]
# Brief Summary: 
MVVM or Model-View-Viewmodel is an architectural pattern that allows developers to separate their business logic from the user interface. It makes it easy to perform CRUD (create, read, update, and delete) functions. Adopting MVVM architecture can help in the creation of high quality apps. The article provides a detailed example to help you understand MVVM architecture.

# Key Takeaways: 

Understand the MVVM architecture
Incorporate MVVM architecture in their future apps
Debug errors resulting from the MVVM architecture

# References: 
https://developer.android.com/jetpack/guide

**Comment by hectorkambow** [comment]
🤔 
Very cool topic suggestion - it seems like it would be a very helpful article. 
Lets be sure to include what pain point we are solving for the readers. 
What alternatives exist - what is the problem MVVM is solving. 
Looking forward to reviewing. 
Please be sure to review any relevant EngEd articles to be able to include them as a resource 🚀
