### ISSUE TITLE
Deep dive into RxJava Operators

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#564]
### Brief Summary: 
With RxJava observables, many operators aid in data transformation and how we receive the data. This article aims at checking most of the common RxJava operators and how they are grouped.

### Key Takeaways: 
1. What are RxJava operators
2. Some of the RxJava operators
3. How RxJava operators work

### References: 
N/A

**Comment by ninjaginja** [comment]
approved - thanks @LinusMuema
