### ISSUE TITLE
How Does Mining Cryptocurrency Work?

### ISSUE THREAD

**Issue by Manley12** [section-io/engineering-education#565]
### Brief Summary: 
Mining cryptocurrency is a complex mathematical system. These such systems proves, without a doubt, that a computer generated the correct key to the cryptocurrency coin within a block, but also owns said coins. Mining pools allows user to pool together their mining power to find coins faster and more efficiently.

### Key Takeaways: 
- Basic understanding of hashing
- Basic understanding of how a hash proves ownership
- How mining pools utilize multiple computers to find a key
- How mining provides a distributed, decentralized governance

### References: 
https://bitcoin.org/en/how-it-works

**Comment by ninjaginja** [comment]
good topic @Manley12 . Please be sure that the content you develop is sufficiently different from the reference article that you've listed.
