### ISSUE TITLE
Building a documentation website from scratch using Hugo

### ISSUE THREAD

**Issue by Quadrisheriff** [section-io/engineering-education#566]
### Brief Summary: 
Documentation is a must in every software development project. In this tutorial, we will build a technical documentation website with Hugo-extended and the Docsy theme.

### Key Takeaways: 
1. Learn the importance of documentation in a software development project
2. Learn how to install and set up Hugo.
3. Learn how to install and setup the Docsy theme.
 

### References: 
- https://gohugo.io/
- https://www.docsy.dev/

**Comment by ninjaginja** [comment]
approved - thanks @Quadrisheriff
