### ISSUE TITLE
Android ViewPager2 with TabLayout

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#568]
### Brief Summary: 
Slide transition between screens is very common in android applications. This is often used together with tabs to display and navigate through screens. This article will show how to use the `viewpager2` library and `TabLayout` to implement this feature in an android application.

### Key Takeaways: 
1. Understand the `ViewPager2` library.
2. Understand how to use fragments in `ViewPager2`.
3. Understand how to integrate `TabLayout` with `ViewPager2`.

### References: 
N/A

**Comment by ninjaginja** [comment]
approved - thanks @kayere
