### ISSUE TITLE
Understanding JavaScript functions

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#569]
### Brief Summary: 
Functions are one of the fundamental building blocks in JavaScript; a function is a set of statements that performs a task or calculates a value. It can be called anywhere in your program. A function is invoked by something that calls it. They are subprograms, and they allow you to divide your program into more manageable tasks.

This guide will talk about function, including some essential key takeaways such as:

### Key Takeaways: 
-  Declaring a function
-  Naming a function
-  Calling a function
-  Function parameters and arguments
-  Function as variable
-  Returning a value
-  Function Hoisting

### References: 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions
- https://developer.mozilla.org/en-US/docs/Glossary/First-class_Function

**Comment by ninjaginja** [comment]
@kimkimani I'm having a hard time seeing how this article will differ from what is already readily available through the docs that you've listed. We need to be sure that the content that we publish is original and not readily available through other sources. I'd suggest exploring a topic that is more unique.

**Comment by kimkimani** [comment]
@ninjaginja . Yes, the key points look similar to the provided docs. I wanted to explain the function concept in a more non-docs way. Just trying to draw the concept in a more concise way and of course, explaining with examples to make the content stand out.

**Comment by ninjaginja** [comment]
ok, if you feel that you can deliver unique value with your content, then go ahead. Please be sure that you use a title that is more specific to the content that you develop. The current suggestion is far too vague and generic.

I'm just trying to reduce the possibility of your article being rejected after you expend energy into it, in the case that we deem it's too redundant with existing content out there.
