### ISSUE TITLE
Atom vs. Visual Studio Code: Functionality and Features Comparison

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#570]
### Brief Summary: 
Atom and VScode have much in common. This article will give a review of both text editors. Also, It will compare the performance, functionality, and features of Atom and VScode.

### Key Takeaways: 
1. Atom vs. VSCode: Similarities
2. Atom vs. VSCode: Differences
3. Atom vs. VSCode: Functionality
4. Atom vs. VSCode: Features
5. Atom vs. VSCode: Pro and Cons

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.slant.co/versus/48/5982/~atom_vs_visual-studio-code
https://stackshare.io/stackups/atom-vs-visual-studio-code#description
https://www.g2.com/compare/atom-vs-visual-studio-code
https://www.quora.com/How-does-Visual-Studio-Code-compare-to-Atom

**Comment by ninjaginja** [comment]
@JudyNduati It doesn't seem that your suggested content intends to cover anything different than what is already readily available in the articles that you've cited in your references list. Perhaps a different spin on this article could be walking through a comparison of the two editors based on a practical coding example that you walk through?

**Comment by JudyNduati** [comment]
@ninjaginja, I will use practical coding examples to show a comparison of the two editors. Also, I will display unique content.

**Comment by JudyNduati** [comment]
@ninjaginja, how about this topic suggestion? May I go ahead

**Comment by ninjaginja** [comment]
Yes, please go ahead and proceed with this content, keeping in mind the notes that I passed along yesterday on #576
