### ISSUE TITLE
Machine Teaching to Improve Artificial Intelligence

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#572]
### Brief Summary: 

We provide machine learning models with volumes of data with the expectation that they shall identify patterns or learn relationships in the data. This can be an expensive and time-consuming process. However, there exists an approach that leverages human abilities and expertise to guide machine learning models to find solutions to problems much faster. This is called machine teaching. We explore this approach in this article.

### Key Takeaways: 

Reader should:
1. Comprehend the concept and need for machine teaching
2. Be able to differentiate machine teaching and machine learning 
3. Understand the benefits of machine teaching
4. Be aware of the applications of machine teaching

### References: 

https://blogs.microsoft.com/ai/machine-teaching/

https://www.intheblack.com/articles/2019/10/01/machine-teaching-is-the-next-generation-of-machine-learning

https://analyticsindiamag.com/machine-learning-vs-machine-teaching-a-whole-new-approach-to-imparting-human-skills/

https://searchenterpriseai.techtarget.com/definition/machine-teaching

**Comment by ninjaginja** [comment]
approved @collins-a . Please be sure that your content is sufficiently different from the articles cited in your references list.

**Comment by collins-a** [comment]
Noted. I'll definitely make sure
