### ISSUE TITLE
Remove banner ads with watch video ads in React Native

### ISSUE THREAD

**Issue by Worawat101** [section-io/engineering-education#574]
### Brief Summary:

The main aim is to control the display of ads using the React Hooks. The idea is to make users watch the short video ads so that they can disable the ads display for a certain amount of time. 

### Key Takeaways:

- Learn how to use React Hooks.
- Learn how to integrate and implement Admobs in the Expo React Native ecosystem.
- Learn how to control the display of video ads.
- Learn how to monetize the app using Admobs.

### References:

[https://docs.expo.io/versions/latest/sdk/admob/](https://docs.expo.io/versions/latest/sdk/admob/)

[https://blog.expo.io/adding-admob-to-your-expo-project-aa4e48ac848](https://blog.expo.io/adding-admob-to-your-expo-project-aa4e48ac848)

**Comment by ninjaginja** [comment]
@Worawat101 Thank you for the topic suggestion. I'm having a difficult time understanding exactly what specific developer challenge you are looking to address in this article. The wording in your summary is very confusing. Are you able to further develop this summary with an extended outline to give us a better idea of what your article will include?

**Comment by Worawat101** [comment]
Hi, @ninjaginja Thank you, for giving feedback. I will update the summary here.

### Brief Summary:

It is high time where most mobile applications use Admobs to monetize their app and make a profit out of it. This tutorial will address the solution to displaying sustainable video ads that will reappear after a certain time while using different features in an app. Thus, make a profit out of it as well.

- The tutorial will demonstrate how to control the locations where ads are to be displayed using the Redux mechanism.
- It will also demo the feature for the users that will allow them to pause the ads after watching the video ads.

![ezgif-2-8d5f8b793bb0](https://user-images.githubusercontent.com/26838504/98088547-280fc200-1eb4-11eb-95a8-8f12a2a35ee9.gif)

**Comment by ninjaginja** [comment]
Thank you for clarifying @Worawat101 - approved
