### ISSUE TITLE
Internet of things(IoT)

### ISSUE THREAD

**Issue by Charity-Njeri** [section-io/engineering-education#577]
### Brief Summary: 

Internet of Things (IoT) has changed the traditional way of living into a high tech lifestyle. The article discusses key issues and different challenges of IoT

### Key Takeaways: 
Overview 
Brief history 
Advantages and disadvantages 
Security and privacy

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.computerweekly.com/opinion/The-internet-of-things-an-overview?amp=1
https://www.networkworld.com/article/3542891/the-internet-of-things-in-2020-more-vital-than-ever.html
https://www.sciencedirect.com/science/article/pii/S0007681315000373

**Comment by ninjaginja** [comment]
@Charity-Njeri This topic is far too broad for the type of content that we're seeking. We're looking for unique content that takes a practitioner's approach to addressing a developer challenge or area of interest. Please take a look at some of the recently published articles and open PR and issue lists for examples and comments around best practices. Tutorials are always a good way to deliver unique value.
