### ISSUE TITLE
Minecraft Plugin Development - A Hands On Crash Course

### ISSUE THREAD

**Issue by john-amiscaray** [section-io/engineering-education#580]
### Brief Summary: 
In this tutorial, we will be going over how to code Minecraft plugins in a fun, hands-on way. We will be doing so by creating fun (or frustrating) challenges, and a couple of potentially useful commands. This includes, but is not limited to: coding it so that stepping on grass blocks triggers explosions, making all creepers spawn invisible, and creating a command to spawn Withers on a set interval. The reader is encouraged to have fun and experiment, using this as a way to get into or practice coding in an enjoyable way.

### Key Takeaways: 
1. Project structure
2. Events and Event Listeners
3. Getting information about the player environment and reacting accordingly
4. Creating scheduled in-game occurrences. 
5. Tricks/Tools the reader can use creatively in their own plugins

### References: 
N/A

**Comment by ninjaginja** [comment]
very cool topic @john-amiscaray  - approved :)
