### ISSUE TITLE
React Native Livestream Application using Agora

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#583]
## Brief Summary

In this tutorial, we'll be going over how to create a simple React Native App using Agora to create a Livestream and sharing a room code for other users to join. This includes, but is not limited to: coding the app from scratch and **Add Event Listeners** on the Livestream to listen to audio and video state changes on the host to notify the audience in the Livestream.

## Key Takeaways

- Project Structure
- Create/ Join Livestream
- Livestream Events and Event Listeners

**Comment by ninjaginja** [comment]
Sounds like a cool tutorial @zolomohan  - approved :)

**Comment by zolomohan** [comment]
I'll create a PR ASAP then :)
