### ISSUE TITLE
Group Chat App with Socket.io

### ISSUE THREAD

**Issue by HarishTeens** [section-io/engineering-education#593]
### Brief Summary: 

This guide would cover :
 - Build a chat app with the following features:
     - one to many conversations
     - User join, leave notification
     - User typing notification.
 - Deploy the app to Heroku

### Key Takeaways: 

- How to use socket.io to build real-time applications.
- Build chat apps from scratch.
- Workflow of Socket events, so that one could build their own events.

### References: 
https://www.youtube.com/playlist?list=PL4cUxeGkcC9i4V-_ZVwLmOusj8YAUhj_9
P.S. This is the place where I got to know about Sockets. I really liked the idea of demonstrating the concept of sockets with a simple chat application.

**Comment by HarishTeens** [comment]
My bad, I didn't check properly. Sure I would solely focus on the Chat application then. Thought of keeping it all simple to demonstrate the concept. I'll add some more details and features.

**Comment by HarishTeens** [comment]
Hey @ninjaginja , I've updated the contents of the issue, Could you take a look at it once?

**Comment by ninjaginja** [comment]
Thanks for the update @HarishTeens . I just want to be sure that your tutorial will be sufficiently different from the example tutorial that you provided? I might recommend choosing a different type of application for your example, since the chat app has already been covered.

**Comment by HarishTeens** [comment]
Yea sure @ninjaginja , I get your point. How about a Rock Paper Scissor Multiplayer Game?
Basic features could be,
- one creates a room, other joins with room ID
- after both the users have made their choice, we display who won
- even a leaderboard to keep track of the scores.

**Comment by ninjaginja** [comment]
Great idea @HarishTeens ! ... approved!
