### ISSUE TITLE
Dive into Batch scripting language

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#599]
### Brief Summary: 

**Batch** is a native programming language for windows, it can execute certain commands automatically at the level of an operating system ", it can be classified as an interpreter-based scripting language.
Also, it can be used for server installations.
This tutorial will be a "dive into" from the basics to the advanced points.

### Key Takeaways: 

- What is **Batch** programming 
- **Batch** variables/loops/ etc..
- How to manipulate files in the system (copy, move, delete, etc..)
- I will create 2 or 3 advanced apps to take the reader from the beginner side to the advanced one.

### References: 
N/A

**Comment by ninjaginja** [comment]
Good topic @ahmadmardeni1 . Please be sure to thoroughly check your grammar and readability before submitting your article for review. (I noticed several awkward phrasings within your summary description.)
