### ISSUE TITLE
Securing of Artificial Intelligence from Adversaries

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#600]
### Brief Summary: 
Artificial intelligence represents just how powerful and impactful technology has become. It is present in all aspects of our daily lives, from basic tasks to very critical implementations. However, AI systems may cause devastating damage if used by malicious actors. We often focus on how AI can be used to improve cybersecurity, but it is important to consider how to secure AI systems.

### Key Takeaways: 

The reader should:
1. Be aware of the basic existing cybersecurity solutions 
2. Understand the challenges of securing AI
3. Be informed of the threats and consequences of attacks
4. Understand the approaches to secure AI

### References: 

P. Bhattacharya, "Guarding the Intelligent Enterprise: Securing Artificial Intelligence in Making Business Decisions," 2020 6th International Conference on Information Management (ICIM), London, United Kingdom, 2020, pp. 235-238, doi: 10.1109/ICIM49319.2020.244704.

K. Sadeghi, A. Banerjee and S. K. S. Gupta, "An Analytical Framework for Security-Tuning of Artificial Intelligence Applications Under Attack," 2019 IEEE International Conference On Artificial Intelligence Testing (AITest), Newark, CA, USA, 2019, pp. 111-118, doi: 10.1109/AITest.2019.00012.

https://www.fintechnews.org/how-to-be-cyber-secure-while-using-artificial-intelligence-ai/

https://www.brookings.edu/research/how-to-improve-cybersecurity-for-artificial-intelligence/

https://futureoflife.org/2017/09/21/safety-principle/?cn-reloaded=1

**Comment by ninjaginja** [comment]
Good topic @collins-a . However, from your description, it seems a bit vague and generic. I think this article would be stronger as a practical guide 'How to Secure AI Systems', where you dive into tactical methods.

**Comment by collins-a** [comment]
Noted. I'll take that perspective and focus on the various approaches and methods to secure AI systems.
