### ISSUE TITLE
Types of Artificial intelligence (AI)

### ISSUE THREAD

**Issue by manmusa100** [section-io/engineering-education#605]
### Brief Summary: Artificial intelligence (AI) refers to the simulation of human intelligence in machines that are programmed to think like humans and mimic their actions. Types of Artificial intelligence (AI) help us to develop program suitable for a specific purposes.
Describe the what, why, and how of your content idea in 2-5 sentences.

### Key Takeaways: what is Artificial intelligence (AI).The main types of Artificial intelligence (AI)The purposes of each type of Artificial intelligence (AI)
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

### References: N/A 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion. This topic is far too broad and has already been sufficiently covered across previously published articles. Please choose another area, with narrower focus to explore.
