### ISSUE TITLE
All you have to know about inheritance using c#

### ISSUE THREAD

**Issue by mohamedgh16** [section-io/engineering-education#606]
### Brief Summary: 

**C#** is a general object-oriented programming (OOP) language for networking and Web development.
 it's primarily used on the Windows .NET framework, It is specified as a common language infrastructure (CLI) language.
**C#** is designed to improve developers’ productivity, It saves a lot of money by reducing development time and maintenance costs.
Inheritance allows you to define a base class that provides specific functionality and to define derived classes that either inherit or override that functionality.

### Key Takeaways: 

- Introduction to inheritance with **C#**
- Difference between base classes and derived classes
- Protected and internal members
- Relationship between base classes and derived classes
- Constructors and destructors in derived classes

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @mohamedgh16 - approved!

Note: The phrasing of the title is a bit awkward. I'd suggest improving the readability.
