### ISSUE TITLE
An Overview of Drone Technology (Unmanned Aerial Vehicles (UAVs))

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#608]
### Brief Summary: 
Unmanned Aerial Vehicles (UAVs), commonly known as drones, have gained popularity in the recent past because of their importance in aerial photography, surveillance and delivery. This article aims at providing readers with a broad understanding of this important technology. The information provided in the article will be resourceful to developers and users (existing and potential ones). 

### Key Takeaways: 
The following are important aspects that readers should understand;
1. What are drones?
2. Types of Drones
3. How Drones Work
4. Drone Programming (Programming Languages for Drones)
5. Application of Drones
6. Limitations of UAVs 
7. The Future of Drone Technology

### References: 
https://internetofthingsagenda.techtarget.com/definition/drone

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @mbaabuones ! I'd suggest narrowing the focus of this article to address a specific challenge that developers might be seeking out within this particular topic area. For example, perhaps you could hone in on the programming languages with some practical examples?

**Comment by mbaabuones** [comment]
@ninjaginja Thank you for that suggestion. I actually wanted the article to focus on the programming languages used in drones. However, i did not get adequate resources that can help me build a 750-word article on drone programming. This explains why i added other aspects relating to drone technology.

**Comment by ninjaginja** [comment]
In that case, I'd suggest exploring another topic. We're not seeking content that repeats concepts/definitions that are already widely available through other sources.
