### ISSUE TITLE
A Review of 5G Wireless Technology

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#609]
### Brief Summary: 
5G is a new generation network that is gaining momentum because of its advanced features that enhance high speed and improved connectivity. This technology will supersede the 4G technology, which is currently used in many parts of the world. This article aims at providing a review of this new technology that may shape the global telecommunication industry. 
### Key Takeaways: 
The main areas covered in the review include;
1. Overview of 5G Technology
2. How 5G Technology Works
3. Applications of 5G Technology
4. Benefits of 5G Technology
5. Limitations of 5G Technology
6. Conclusion

### References: 
https://www.qualcomm.com/invention/5g/what-is-5g

**Comment by ninjaginja** [comment]
@mbaabuones This topic is far too broad and has already been covered across several previously published articles.
