### ISSUE TITLE
React Native Agora Video Conference App

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#610]
## Brief Summary

In this tutorial, we'll be going over how to create a Video Conferencing app with React Native and Agora. You can share a room code for other users to join the conference.

## Key Takeaways

- Project Structure
- Start/ Join Video Conference
- Mute Local/ Remote Video and Audio Streams

**Comment by ninjaginja** [comment]
Sounds like a cool tutorial @zolomohan  - approved!
