### ISSUE TITLE
Generating a Word Cloud using Python

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#612]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this fun experiment with NLP in Python, we will be generating word clouds. Word clouds are efficient means to convey summaries of websites pictorially. Varying the font sizes ensures the importance of keywords is highlighted.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. A fun programming experiment in python. Given a paragraph of text, a word cloud is generated.
2. Understanding the process of tokenization and stopword removal using nltk
3. Using matplotlib to plot the word cloud generated.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/a

**Comment by ninjaginja** [comment]
This is a really great idea @lalith1403 - approved!
