### ISSUE TITLE
Introduction to Cassandra

### ISSUE THREAD

**Issue by rohanreddych** [section-io/engineering-education#614]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Apache Cassandra™ is a distributed NoSQL database that is highly scalable. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Introduction to NoSQL database and Cassandra and setup.
- The Cassandra Query Language, data modelling and architecture.
- Building an application in nodejs.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://cassandra.apache.org/doc/latest/

**Comment by ninjaginja** [comment]
Great topic @rohanreddych! I think the title could be a bit stronger with 'A Hands-On Introduction to Cassandra'
