### ISSUE TITLE
Implenting Linear Discriminant Analysis in Python

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#616]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
We will be implementing a Linear Discriminant Analysis (LDA) algorithm from scratch. It is used extensively as a dimensionality reduction technique. We will understand the theory behind the algorithm and implement it from scratch. Finally, we plot the dimensionally reduced data.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand LDA through an in-depth review
2. Code it from scratch
3. Observe the advantages of the algorithm pictorially,
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Great topic @lalith1403  - approved!
