### ISSUE TITLE
Clustering in Unsupervised Machine Learning

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#625]
### Brief Summary: 
Unsupervised learning is a technique in machine learning (ML) that does not require supervision of models by users. This article introduces readers to unsupervised machine learning and why it is needed. It will mainly focus on advancing knowledge in clustering and various clustering types in unsupervised ML.

### Key Takeaways: 
The following are key concepts that readers should understand;
1. Introduction to unsupervised machine learning
2. Why Unsupervised Learning is important
3. Clustering Analysis
4. Types of Clustering in Unsupervised ML (including algorithms, advantages and disadvantages of each type)
5. Conclusion

### References: 
https://www.datarobot.com/wiki/unsupervised-machine-learning/

**Comment by ninjaginja** [comment]
good topic @mbaabuones  - approved
