### ISSUE TITLE
Autoscaling in Amazon Web Services (AWS): An Overview

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#626]
### Brief Summary: 
Amazon Web Services (AWS) are cloud computing services that provide Application Programming Interfaces (APIs) and platforms for cloud computing to governments, individuals and companies. This article aims at providing readers with a broad understanding of autoscaling in AWS, which is an important concept for developers.

### Key Takeaways: 
The following are important concepts that readers should understand;
1. What is autoscaling? 
2. How AWS autoscaling works
3. Types of AWS autoscaling
4. Components involved in AWS autoscaling
5. Benefits of AWS Autoscaling
6. Conclusion

### References: 
https://www.whizlabs.com/blog/amazon-web-services/#:~:text=Introduction%20to%20Amazon%20Web%20Services%20Amazon%20Web%20Services,a%20private%20scalable%20infrastructure%20and%20network%20for%20themselves.

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
