### ISSUE TITLE
Evaluating Machine Learning Model Performance

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#633]
### Brief Summary: 

Machine learning models are expected to provide accurate and trustworthy predictions. In order to confidently trust their predictions, it is important to assess how machine learning models generalize on test data. We look at how to evaluate model performance. 

### Key Takeaways: 

The reader should:
1. Understand the need to evaluate model performance
2. Get to learn the main model evaluation techniques
3. Explore a few model evaluation metrics (both regression and classification)

### References: 

https://heartbeat.fritz.ai/introduction-to-machine-learning-model-evaluation-fa859e1b2d7f#:~:text=The%20above%20issues%20can%20be%20handled%20by%20evaluating,accuracy%20of%20a%20model%20on%20future%20%28unseen%2Fout-of-sample%29%20data.

https://towardsdatascience.com/various-ways-to-evaluate-a-machine-learning-models-performance-230449055f15

https://www.jeremyjordan.me/evaluating-a-machine-learning-model/

https://towardsdatascience.com/machine-learning-how-to-evaluate-your-model-1dabbdc849a4

https://machinelearningmastery.com/how-to-evaluate-machine-learning-algorithms/

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
