### ISSUE TITLE
Android Room

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#637]
### Brief Summary: 
Most android applications require local data storage. In the past years, this has been achieved through the use SQLite database. Room is a persistent library that is part of the android jetpack. It is built on top of SQLite. This article goes through using the library in an android application.

### Key Takeaways: 
1. Understand what Room persistent database is.
2. Understand how to use Room in an application.
3. Understand various advantages of using Room.

### References: 
N/A

**Comment by ninjaginja** [comment]
Good topic @kayere . Please be sure that you make the title of your article more specific to the challenge that you are addressing. The current title is very generic and doesn't describe what you intend to cover in the content.

**Comment by kayere** [comment]
Noted @ninjaginja
