### ISSUE TITLE
Build a real-time chat application using socket.io and node.js

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#643]
### Brief Summary: 

The tutorial will help semi beginners to build a real-time chat application using node.js and socket.io. Both of these platforms are in high demand. Therefore, the skills acquired from this tutorial can be used to develop more complex applications in the future.

### Key Takeaways: 

- The user will have a greater understanding of node.js or JavaScript.
- The read will be able to add real-time chat functionalities in their applications.
- The reader will be able o debug their code more effectively.

### References: 

https://nodejs.org/en/docs/
https://socket.io/

**Comment by ninjaginja** [comment]
@WanjaMIKE This topic has already been suggested with comments on #593 . Please select a different topic area to explore.
