### ISSUE TITLE
Secured Deep Learning in Remote Devices

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#644]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

In this article, we will understand how Secured deeplearning models can be deployed in Remote devices using Federated learning. We will also be going over a step by step guide for implementation.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader will understand how deeplearning models are deployed in remote devices
- The reader will be able to code a simple deeplearning model, which can be deployed on remote devices
- The reader will understand the importance of Federated learning

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

- https://www.udacity.com/course/secure-and-private-ai--ud185
- https://ai.googleblog.com/2017/04/federated-learning-collaborative.html
- https://blogs.nvidia.com/blog/2019/10/13/what-is-federated-learning/

**Comment by ninjaginja** [comment]
good topic @srishilesh - approved
