### ISSUE TITLE
Handling Imbalanced Data in Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#645]
### Brief Summary: 

Data powers machine learning algorithms. It is important to have balanced datasets in a machine learning workflow. Imbalanced datasets mean that the number of observations differ for the classes in a classification dataset. This imbalance can lead to inaccurate results. This motivates us to explore techniques to handle imbalanced data. 

### Key Takeaways: 

The reader should:
1. Appreciate the need for balanced datasets
2. Understand the difference between balanced and imbalanced datasets
3. Learn a few techniques to handle imbalanced data

### References: 

https://analyticsindiamag.com/5-important-techniques-to-process-imbalanced-data-in-machine-learning/

https://towardsdatascience.com/handling-imbalanced-datasets-in-machine-learning-7a0e84220f28

https://heartbeat.fritz.ai/dealing-with-imbalanced-data-in-machine-learning-18e45fea7bb5

**Comment by ninjaginja** [comment]
great topic @collins-a - approved
