### ISSUE TITLE
Implementing scoped model in your Flutter application

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#648]
### Brief Summary: 
The ScopedModel refers to the framework that allows data to flow from the parent widget down to its children or descendants. It allows users to build creative and highly interactive applications. Flutter is increasingly becoming popular today. It is, therefore, important for you as a developer to understand how the application receives and consumes data 

### Key Takeaways: 
- Understand the ScopedModel.
- Identify the required dependences to use the ScopedModel
- Know how to implement the ScopedModel in your Flutter application.

### References: 
https://pub.dev/packages/scoped_model#:~:text=A%20set%20of%20utilities%20that,when%20the%20model%20is%20updated.

**Comment by ninjaginja** [comment]
great topic @WanjaMIKE  - approved
