### ISSUE TITLE
The Basics of GIS Software

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#649]
### Brief Summary: 
A Geographic Information System (GIS) software is a system or application that enables people, organizations or governments to store, analyze, visualize and manipulate spatial and geographic data. This software is important because it enhances monitoring and planning in areas such as agriculture, fire response, surveying and disaster management. This article provides readers with important information regarding the features, workflow and types of GIS software. 

### Key Takeaways: 
The following are key aspects that readers should understand;
1. What is GIS?
2. Introduction to GIS software
3. Features of a GIS software
4. How a GIS software works
5. Types of GIS Software
6. The Future of GIS Software

### References: 
https://www.gisresources.com/fundamentals-of-gis/

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @mbaabuones. GIS software is on the periphery of topics that are relevant for our audience. At this time, I think we'll steer away from this topic area.
