### ISSUE TITLE
Backward Chaining in Artificial Intelligence

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#650]
### Brief Summary: 
Backward chaining is a concept in artificial intelligence (AI) that involves backtracking from the endpoint or goal to steps that led to the endpoint. This goal-driven algorithm is important to developers that want to design effective solutions in complex database systems. This article provides meaningful information regarding this important aspect.

### Key Takeaways: 
The following are the key issues that readers need to understand;
1. What is backward chaining?
2. Why backward chaining is needed in AI 
3. How backward chaining in AI works (with examples)
4. Applications of backward chaining in artificial intelligence
5. Advantages and disadvantages of backward chaining
6. Conclusion

### References: 
https://study.com/academy/lesson/backward-chaining-in-ai-definition-uses-efficiency.html

**Comment by ninjaginja** [comment]
this is a good topic @mbaabuones - approved
