### ISSUE TITLE
Introductions to time series

### ISSUE THREAD

**Issue by jamessandy** [section-io/engineering-education#653]
### Brief Summary: 
This article will give users an introduction to what time series is in machine learning. It is fast rising deep learning concepts with a wide scope of projects and It will also give a detailed overview and  basic implementations, 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What is time series
2. Time series forecasting methods
3. Types of forecasting models
4. Popular time series ML problems

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @jamessandy - approved. Please be sure to put your article through a thorough grammar/readability review prior to submitting for review. (I noticed several grammatical errors in your topic summary.)
