### ISSUE TITLE
Using Tuples in Python

### ISSUE THREAD

**Issue by cyberShaw** [section-io/engineering-education#655]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A tuple is a data structure in Python which are ordered and immutable. They are similar to lists and vary by the fact that they are immutable. That is, they cannot be changed. This article would be a quick introduction to tuples and would be a tutorial on how to use tuples in Python.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- The reader would be aware of the tuple data structure in Python.
- The reader will be able to differentiate between lists and tuples.
- The reader will be able to get a hands-on introduction to using tuples and various in-built tuple functions in Python.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://docs.python.org/3.3/library/stdtypes.html?highlight=tuple#tuples

**Comment by ninjaginja** [comment]
good topic @cyberShaw - approved
