### ISSUE TITLE
Implementing Public-key cryptography in JavaScript

### ISSUE THREAD

**Issue by mwangiKibui** [section-io/engineering-education#661]
### Brief Summary: 
Public-key cryptography is an encryption system which comprises of private and public key pairs. The private keys are known only to the sender and receiver whereas public keys are disseminated widely. The encryption system solves the key distribution problem which involves keeping keys secret from being tampered by third parties.This article highlights implementation of public-key cryptography in JavaScript using the relevant libraries.

### Key Takeaways: 
- Understand public-key cryptography
- Understand third party libraries used for public-key cryptography in JavaScript
- Coming up with a working public-key encryption algorithm in JavaScript

### References: 
- https://medium.com/sharenowtech/high-speed-public-key-cryptography-in-javascript-part-1-3eefb6f91f77
- https://github.com/dchest/tweetnacl-js/blob/master/README.md#documentation

**Comment by ninjaginja** [comment]
good topic @mwangiKibui  - approved
