### ISSUE TITLE
Getting started with WorkManager

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#662]
### Brief Summary: 
Performing background tasks in Android has always been a challenge. Jetpack introduced the WorkManager library to make this process easier for developers. This article aims at giving the reader a basic understanding of what the library is and it's pros.

### Key Takeaways: 
1. What is WorkManager
2. How to use WorkManager
3. The advantages of using WorkManager

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @LinusMuema - approved
