### ISSUE TITLE
Basics of The Object Model

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#665]
### Brief Summary: 
An object model sees information systems as sets of objects. Object models use various diagrams to show how objects behave and how they perform real-world tasks. In this article, we will look into the basic concepts of object models.

### Key Takeaways: 
1. Defining the object model
2. Explaining OOP, OOD, and OOA
3. Elements of the Object Model
4. Applications of the Object Model

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @JudyNduati - approved

**Comment by hectorkambow** [comment]
Article merged
