### ISSUE TITLE
Understanding Document Object Model in JavaScript

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#670]
### Brief Summary: 
Document Object Model (DOM) is an API for HTML and XML. Every Html element in a document is an object. In this article, you will learn about DOM in JavaScript

### Key Takeaways: 
1. What is DOM
2. DOM as a hierarchy of nodes
3. DOM - JavaScript View
4. Types of Nodes
5. Understanding Node and Element

### References: 
https://www.w3schools.com/js/js_htmldom.asp
https://www.tutorialspoint.com/javascript/javascript_html_dom.htm
https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

**Comment by ninjaginja** [comment]
@JudyNduati I think there's too much overlap with this previously published article - https://www.section.io/engineering-education/document-object-model/

Please select a different topic area to explore.
