### ISSUE TITLE
Forward Chaining in Artificial Intelligence

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#671]
### Brief Summary: 
Forward chaining is a method of reasoning in artificial intelligence in which inference rules are applied on existing data to extract additional data until an endpoint (goal) is achieved. This type of chaining is important to developers that want to use data-driven algorithms to develop effective computer-based systems. This article provides readers with a broad understanding of this important concept. 

### Key Takeaways: 
The following are key aspects that readers should understand;
1. What is forward chaining?
2. Properties of forward chaining
3. The process of forward chaining in AI (with examples)
4. Uses of forward chaining in artificial intelligence
5. Advantages and disadvantages of forward chaining
6. Conclusion

### References: 
https://www.javatpoint.com/forward-chaining-and-backward-chaining-in-ai

**Comment by ninjaginja** [comment]
@mbaabuones could this be combined with your previous article suggestion - 'Forward and Backward Chaining in AI'?

**Comment by mbaabuones** [comment]
@ninjaginja Yes, i can do that.

**Comment by ninjaginja** [comment]
Cool, I'm going to close this. (Consolidated into #650 )
