### ISSUE TITLE
Introduction to the Dark Web

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#672]
### Brief Summary: 
The dark web refers to internet content (worldwide web) that has not been indexed by standard search engines. The hidden content is accessible through special configurations, authorization or software. This article takes readers through important aspects regarding the dark web. 

### Key Takeaways: 
Readers should gain knowledge in the following aspects;
1. What is the dark web?
2. Dark web features: browser, search engine and website
3. How the dark web works
4. Important applications of dark web
5. Content hosted in the dark web that poses threat to users
6. Advantages and disadvantages of Dark Web
7. Conclusion

### References: 
https://www.thedarkwebsites.com/

**Comment by ninjaginja** [comment]
While this is an interesting topic @mbaabuones . As a reputable brand, I don't think we want to host any content that's associated with the dark web. Please select a different topic area to explore.

**Comment by mbaabuones** [comment]
@ninjaginja Alright. Noted.
