### ISSUE TITLE
Implementing secret key cryptography in JavaScript

### ISSUE THREAD

**Issue by mwangiKibui** [section-io/engineering-education#673]
### Brief Summary: 
Secret key cryptography is an encryption system that involves using only one secret key. The key is shared between the communicating pairs. It is considered faster than public key cryptography and therefore applied to bulk messages. In this article we shall go through secret key cryptography algorithms, its libraries in JavaScript and implement an example application.

### Key Takeaways: 
- Understand secret key cryptography algorithms.
- Understand libraries for implementing secret key cryptography in JavaScript.
- Understand how to implement secret key cryptography in JavaScript using crypto library.

### References: 
https://medium.com/@spatocode/symmetric-encryption-in-javascript-bcb5fd14c273

**Comment by ninjaginja** [comment]
good topic @mwangiKibui - approved
