### ISSUE TITLE
Conditional Automation in Driving: Level 3 Autonomous cars 

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#674]
### Brief Summary: 
Autonomous driving is gaining momentum in the automobile industry. This area has gained interest among developers because of the application of artificial intelligence and augmented reality (AR) in autonomous driving. This article aims at providing readers with meaningful information regarding the third level of autonomous driving.

### Key Takeaways: 
1. What is an autonomous car?
2. Introduction to conditional automation in driving
3. Key features of a level 3 autonomous car
4. How level 3 autonomous cars work
5. The future of autonomous driving

### References: 
https://interestingengineering.com/how-do-self-driving-cars-work

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
