### ISSUE TITLE
Implement Android Application Update

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#678]
### Brief Summary: 
Once an application is deployed to the production environment, the first release becomes the first version of that application. But in the future, the application may require enhancements, and more features will be added to it. These features are updates that will frequently be used to improve the application. Every time a new update is made, that triggers a new version. 

Suppose an android user has your application installed on their mobile phone. In that case, the only way to get the new updated features is by updating the installed application to the latest version. 

Google notifies android use that some applications need updates ( some users turn auto-update on), which is excellent, but you want to keep all your users up to date with the latest new released version.

As a developer, we always want our users to update the latest version as soon as we release new features. You want everyone to have the latest version installed, and you want them to use the latest features you’ve developed.

This guide will walk the reader on how to implement that using android studio. 

### Key Takeaways: 
This guide will go over two main streams to implement application updates.

- Force the user to update the application. I.e., a case where an update dialog will always show up whenever the user opens the application until the user updates the newly released version.

- Using google in-app update API.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
great topic @kimkimani - approved
