### ISSUE TITLE
Data Lake vs Data Warehouse vs Database

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#682]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Every industry needs to process data. But the kind of data, its scope, and its use will
illustrate if a data warehouse, database, or a data lake will be best solution for your enterprise. This article will compare these three data management systems. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. An overview of data lake, data warehouse, and database. 
2. Industrial use cases of data lake, data warehouse, and database. 
3. The future of data lakes, data warehouses, and databases. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
