### ISSUE TITLE
Express Server to Generate Authentication Token for Agora Applications

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#683]
## Brief Summary

In this tutorial, we'll be going over how to build an Express server to generate an Agora Authentication Token for Agora Applications.

## Key Takeaways

- Project Structure
- Setup an Endpoint to Request Token
- Generate an Agora Authentication Token

**Comment by zolomohan** [comment]
I hope this clarifies things. 🙂
I'll be going over both actually, what it is, and how to set it up.

**Comment by ninjaginja** [comment]
okay, thanks

**Comment by zolomohan** [comment]
Will have a PR ASAP :)
