### ISSUE TITLE
Robotic Process Automation (RPA) Use Cases in the Healthcare Industry

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#684]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

The present day advanced automation solutions such as Robotic Process Automation (RPA), can help the healthcare industry increase operational efficiency, lower costs, and limit the possibility of human error when processing information. This article explains how RPA automates various complex tasks for medical professionals and administrators in hospitals and clinics. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. An Overview of RPA in healthcare 
2. How RPA automates Patients’ scheduling
3. How RPA automates Insurance Claims Management
4. How RPA Improves the healthcare cycle
5. How RPA Ensures Optimal Care Delivery
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
