### ISSUE TITLE
Physical Security and how to protect your facility

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#686]
### Brief Summary: 
Physical Security is the protection of hardware, software, networks, and data from physical actions and events that could cause serious loss or damage to an enterprise, agency, or institution.

### Key Takeaways: 
- What is Physical Security?
- Information Security vs. Physical Security.
- The layers of Physical Security.
- How to protect your facility against physical hackers.
### References: 
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @ahmadmardeni1 . This is outside of our preferred topic areas. Please choose another area to explore, using our published content library as a guide.
