### ISSUE TITLE
Dataset Shift in Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#688]
### Brief Summary: 
Dataset shift manifests when there is a change in the distribution of data. In the real world, data distribution may be influenced by socioeconomic factors, varying consumer habits among other factors. These factors can alter the underlying relationships between input and output data. As a result, the performance of a model is degraded. It is worth exploring how to handle dataset shift. 

### Key Takeaways: 
The reader should:
1. Understand dataset shift
2. Explore the causes of dataset shift
3. Learn the types of dataset shift
4. Be aware of how to handle dataset shift

### References: 
https://towardsdatascience.com/understanding-dataset-shift-f2a5a262a766

https://www.analyticsvidhya.com/blog/2017/07/covariate-shift-the-hidden-problem-of-real-world-data-science/

https://gsarantitis.wordpress.com/2020/04/16/data-shift-in-machine-learning-what-is-it-and-how-to-detect-it/

**Comment by ninjaginja** [comment]
Good topic @collins-a - approved. Please be sure that the title of the article is reflective of what you intend for the reader to get out of the content. For example: 'Understanding Dataset Shift in Machine Learning'

**Comment by collins-a** [comment]
@ninjaginja thank you, noted. I'll restructure the topic accordingly 😁
