### ISSUE TITLE
Array operators in JavaScript

### ISSUE THREAD

**Issue by mwangiKibui** [section-io/engineering-education#690]
### Brief Summary: 
Arrays are variables that can be used to store different elements in a program. They are coupled with methods to perform traversal and mutation operations. This article shall highlight the elements that can be stored in an array and the operations that can be done on them.

### Key Takeaways: 
- Understand the elements that can be stored in an array.
- Understand the various operations that can be done to elements stored in an array.
- Understand how you can implement this operations.

### References: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by ninjaginja** [comment]
good topic @mwangiKibui - approved. I think the title could be stronger by clearly indicating what the reader should expect to get out of the content. For example: 'How to use array operators in JavaScript'
