### ISSUE TITLE
Introduction to Digital Twin Technology

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#694]
### Brief Summary: 
Digital twin technology is a concept that integrates software analytics, artificial intelligence and special network graphs to create digital simulation models that replicate physical assets (physical twin). It performs important functions such as optimization of operations in manufacturing processes and driving business value. This article gives readers meaningful information regarding this new technology. 

### Key Takeaways: 
1. What is a Digital Twin?
2. Why is Digital Twin Technology Important?
3. Characteristics of Digital Twin Technology
4. How Digital Twin Technology Works
5. Applications of Digital Twin Technology
6. The Future of Digital Twin Technology

### References: 
file:///C:/Users/ADMIN/AppData/Local/Temp/an-introduction-to-digital-twin-development.pdf

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved. Could you please upload the pdf file that you listed as a reference to this issue?

**Comment by mbaabuones** [comment]
@ninjaginja Sure. Find attached.
[an-introduction-to-digital-twin-development.pdf](https://github.com/section-io/engineering-education/files/5574387/an-introduction-to-digital-twin-development.pdf)
