### ISSUE TITLE
Intelligent Agents in Artificial Intelligence

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#695]
### Brief Summary: 
An intelligent agent is an entity that makes decision, which enables artificial intelligence to be put into action. This article introduces readers to various aspects regarding intelligent agents in AI. It will help in expanding their knowledge in how AI works.

### Key Takeaways: 
1. What is an intelligent agent in artificial intelligence?
2. Characteristics of intelligent agents
3. The structure of AI agents
4. Categories of intelligent agents
5. Applications of intelligent agents

### References: 
https://www.javatpoint.com/agents-in-ai

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved. Please be sure that the title is descriptive of what the reader should expect to get out of the content (e.g. understanding, how to, comparison, etc.)
