### ISSUE TITLE
Django user registration using Google Oauth

### ISSUE THREAD

**Issue by geoffrey45** [section-io/engineering-education#696]
### Brief Summary: 
User registration in Django has been made easier by Google Oauth APIs. Users won't have to type their details to sign up in your Django app. All they need is a Google account. We'll look at setting up "Sign up with Google" in your app.

### Key Takeaways: 
The readers will be able to:
- install and set up required Oauth package/s
- create a Google Oauth interface using Django templates
- configure Oauth urlconfs
- Create a Google APIs project
- Test Google Oauth in Django.
### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @geoffrey45  - approved
