### ISSUE TITLE
Securing Django Rest endpoints

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#701]
### Brief Summary: 
Authentication makes it possible to control how users interact with our restful API endpoints. Django supports a number of ways of authenticating users. In the article we will be securing our Todo rest API endpoints that we created [here](https://www.section.io/engineering-education/python-generators/).

### Key Takeaways: 
- Adding a custom User model to Django.
- Securing Rest API endpoints using tokens.
- Securing Rest API endpoints using JSON Web Tokens (JWT)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Great topic @paulodhiambo - approved
