### ISSUE TITLE
How to use object operations in JavaScript

### ISSUE THREAD

**Issue by mwangiKibui** [section-io/engineering-education#703]
### Brief Summary: 
JavaScript as a language is based on a simple object-based paradigm. An object in JavaScript can be defined as a collection of properties about an entity where a property is a key value pair. This article shall highlight objects as a whole in JavaScript, how you can implement objects in JavaScript and the various methods that can applied on the objects.

### Key Takeaways: 
- Understand objects in JavaScript.
- Understand how objects can be implemented in JavaScript.
- Understand methods that can be implemented in JavaScript objects.

### References: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects

**Comment by ninjaginja** [comment]
good topic @mwangiKibui . I would advise holding on developing this article until you've submitted and received feedback on #690 to be sure you incorporate all feedback/learnings into this article.

**Comment by mwangiKibui** [comment]
okay, thank you.
