### ISSUE TITLE
Getting started with operator overloading in C++

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#705]
### Brief Summary: 
Operator overloading provides the ability to a mathematical operator to perform other manipulation operations other than its original operation.

For example, the '+' operator is used for arithmetic addition purpose, but with the help of operator overloading, we can use ‘+’ operator to concatenate two strings at runtime efficiently.

Thus, C++ has the ability to make operators work into different dimensions to perform various operators other than the designated operation of its own.

### Key Takeaways: 
1. General rules of operator overloading
2. Types of operator overloading
3. Operator overloading at a glance

### References: 
https://en.m.wikibooks.org/wiki/C%2B%2B_Programming/Operators/Operator_Overloading

**Comment by ninjaginja** [comment]
great topic @Dawe-7 - approved
