### ISSUE TITLE
How CSS works behind the scenes?

### ISSUE THREAD

**Issue by sardug10** [section-io/engineering-education#715]
### Brief Summary: 
Normally, people don't know what happens behind the scenes of CSS. With this article I would like to give information to the people about how CSS works behind the scenes, starting from the very first thing i.e, initialization of CSS-Object Model to the very end i.e, Visual Formatting Model

### Key Takeaways: 
1. CSS-Object Model
2. Parsing of CSS including cascading and resolving conflicts
3. Formation of render tree
4. Formation of the visual formatting model

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @sardug10 - approved.

As a side note, I noticed some readability challenges in your topic summary. Please be sure that you put your article through a thorough grammar and readability check prior to submitting for review, as we do not offer extensive editing services and want to be sure that we're able to publish your article and maximize your payout.
