### ISSUE TITLE
Graph Traversals: Depth First Search vs Breadth First Search (Java)

### ISSUE THREAD

**Issue by tensoncai** [section-io/engineering-education#716]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

This article will teach students what graphs are and how to traverse graphs with a depth first search algorithm and a breadth first search algorithm. It will explain the idea behind each algorithm and show code examples of each. It will go over recursive and iterative implementations. The language used will be Java.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand what graphs are and how they're represented in code
2. DFS vs BFS and how to code each one
3. Recursive and iterative implementations of DFS and BFS

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @tensoncai - approved
