### ISSUE TITLE
Getting started with Flask web framework 

### ISSUE THREAD

**Issue by corpsgeek** [section-io/engineering-education#717]
### Brief Summary: 
Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. In this article, a step by step guide will be provided on how to install flask, and building a mini project.
### Key Takeaways: 
You will learn:
- how to setup and install a virtual environment 
-how to install and run flask
- how to structure your flask web app
- building a one page static website with flask. 

### References: 
- Flask Documentation
- Onepagelove

**Comment by ninjaginja** [comment]
good topic @corpsgeek - approved. Please be sure that the implementation example that you provide is unique (i.e. not taken from a previous example or documentation)

**Comment by corpsgeek** [comment]
Alright. I’ll make sure to take note of that.

**Comment by corpsgeek** [comment]
Hello @ninjaginja, I am currently writing a draft of this article and it is quite lengthy. For the purpose of readability and delivery of quality content I would like to propose to have this article split into two different articles:
- Getting Started with Flask Web Framework 1, which covers the installation process, structuring of the web application, and running the application to display "Hello World" in the browser, which is much detailed than existing articles online.

- The second phase on the other hand would be focused on building a static website with a simple but attractive UI as an extension of the first, while also explaining the concepts used or rather I record a YouTube video explaining the rest of the process and linking it to the article.

I would also like to mention that I am very much interested in covering articles on the Flask web framework for section.io for a long period of time.

**Comment by corpsgeek** [comment]
@ninjaginja I am yet to receive a response from you.

**Comment by ninjaginja** [comment]
Apologies @corpsgeek, I missed your previous message. I think that's okay to split the article, but we ask that each article have a specific focus and that the title reflects that. For example, rather than titling articles Part 1, Part 2, etc, please make sure that the title accurately summarizes what the reader can expect to learn in the content. Please also note other articles currently in process to ensure that there's no overlap.

**Comment by corpsgeek** [comment]
Okay @ninjaginja. However, do I need to close this issue and create a new one for the first series, then tag you? Or how do you suggest I go about this?

**Comment by ninjaginja** [comment]
You can just link this issue to your first PR, then open new issues/PRs for subsequent articles in the series

**Comment by corpsgeek** [comment]
Alright ma, I will be doing that today alongside the draft.

**Comment by corpsgeek** [comment]
@ninjaginja i've submitted my draft and linked the issue.

**Comment by ninjaginja** [comment]
Thank you @corpsgeek. Your article has entered our review queue, and you will receive any feedback/requested edits once our review committee has had a chance to review.

**Comment by corpsgeek** [comment]
You mentioned the above issue @ninjaginja ??

**Comment by ninjaginja** [comment]
Yes, I mentioned it to another author who suggested a similar topic to make sure that there wasn't overlap.

**Comment by corpsgeek** [comment]
Ohh alright, I understand.
