### ISSUE TITLE
Software Testing Part 1 - Introduction to Unit Testing

### ISSUE THREAD

**Issue by Quadrisheriff** [section-io/engineering-education#718]
### Brief Summary: 
Software Testing is a very important software development process. It improves the quality of your software and also ensures you don’t ship bad bug-filled products to your users. 

In this article, we will talk extensively about unit testing, how to run unit tests, the benefits of running unit tests, and the limitations. This article is the first part of our software testing series, where we discuss popular software testing techniques.

### Key Takeaways: 
After reading this article, you should
- Understand what unit testing is, the benefits, and limitations.
- Know when to run unit tests and when not to use unit testing.
- Understand the importance of testing frameworks and how to run unit testing with a testing framework.

### References: 
'N/A'

**Comment by ninjaginja** [comment]
good topic @Quadrisheriff - approved.
