### ISSUE TITLE
Software Testing Part 2 - Introduction to Test Driven Development(TDD)

### ISSUE THREAD

**Issue by Quadrisheriff** [section-io/engineering-education#719]
### Brief Summary: 
This is the second article of our Software testing series, where we talk about popular software testing techniques. 

In this article, we will talk about Test Driven Development(TDD), the benefits, and the limitations.

### Key Takeaways: 

After reading this article, you should 

- Understand what TDD is all about, the rules of TDD, know when to use TDD, the benefits of TDD, and the limitations of TDD.
- Understand the RED - GREEN - REFACTOR cycle.
- Know how to use TDD with a testing framework.

### References: 
-  https://cleancoders.com/episode/clean-code-episode-6-p1
-  http://agiledata.org/essays/tdd.html
-  https://www.guru99.com/test-driven-development.html

**Comment by ninjaginja** [comment]
good topic @Quadrisheriff - approved.
