### ISSUE TITLE
Introduction to Android Views and Viewgroups

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#720]
### Brief Summary: 
Android makes use of Views to create UI components that the user can interact with. This article is a beginner-friendly introduction to the various Views and the related classes. It will guide readers on how to create various widgets and layouts in an Android application.

### Key Takeaways: 
1. What are views and viewgroups
2. Which are the common views and viewgroups
3. What attributes are associated with the views
4. How to create views in Android

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Dawe-7 - approved
