### ISSUE TITLE
Deep dive into the Android Navigation Components

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#721]
### Brief Summary: 
The Jetpack Navigation library brought in many functions with the Navigation drawers being the most common. However, most developers do not know of the other deep functions of the Navigation components and how they work. This article aims to guide developers on how to maximize the power of the Navigation Library.

### Key Takeaways: 
1. What is the use of a NavGraph
2. Navigation using menu actions
3. Navigation using UI views
4. Deep links in Navigation

### References: 
[Bottom Navigation in Android](https://www.section.io/engineering-education/bottom-navigation-bar-in-android/)

**Comment by ninjaginja** [comment]
good topic @LinusMuema - approved
