### ISSUE TITLE
An introduction to Neural Networks

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#722]
### Brief Summary: 
**Neural networks** is a subfield of machine learning, where the structure of the human brain inspires the algorithms.
Neural networks take the input data and train itself to recognize patterns and spot trends.
This tutorial will be an introduction for future tutorials about using the different algorithms of neural networks to predict stock prices/build a trading bot, and a lot more (All about trading with python).

### Key Takeaways: 
- What is neural network
- What are the layers of a neural network 
-  Long short-term memory (LSTM) is an artificial recurrent neural network (RNN) architecture I will use in future tutorials.

### References: 
N/A (maybe Wikipedia)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @ahmadmardeni1. However, this topic has already been substantially covered in previous articles - https://www.section.io/engineering-education/search/?q=neural. Please select a different area to explore.

**Comment by ahmadmardeni1** [comment]
![Screenshot_2020-11-24-20-02-05-725_com android chrome](https://user-images.githubusercontent.com/63211822/100133910-0d67b200-2e90-11eb-99df-2556b312e4ef.jpg)

The Link is empty @ninjaginja

**Comment by ninjaginja** [comment]
if you do a search on 'neural' in the EngEd article library, you'll find several articles that come up, including an 'Introduction to Neural Networks' article
