### ISSUE TITLE
Stock prices prediction using Python

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#724]
### Brief Summary: 
“Fintech” is one of the most prominent use cases of machine learning.
In this tutorial, I'm going to build a neural network model (LSTM) to predict stock prices with high accuracy.

### Key Takeaways: 
- What is LSTM.
- Choosing data.
- Building the long short term memory model.
- Training the model on our data.
- Plotting results ( I will refer to my "Getting started with data visualization" tutorial for those who don't know it.)

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @ahmadmardeni1 - approved.
