### ISSUE TITLE
Creating a Content Delivery Network (CDN) in Microsoft Azure

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#725]
### Brief Summary: 
A content delivery network (CDN) is a network of data centers and proxy servers that is geographically distributed. CDN in Azure enables developers to save bandwidth, reduce load times and to improve responsiveness. This article provides a tutorial for creating and configuring a CDN in Microsoft Azure. 

### Key Takeaways: 
1. What is a CDN?
2. Introduction to CDN in Microsoft Azure
3. Creating a CDN in Azure (Prerequisites and steps)
4. Creating CDN for specific types of origin (storage, cloud services, web app and custom origin)
5. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @mbaabuones, however we prefer not to publish content that is competitive in nature to the Section product offering. Please select a different topic area to explore.
