### ISSUE TITLE
Amazon Web Services (AWS) vs Google Cloud

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#726]
### Brief Summary: 
This article provides a broad comparison of two giant cloud computing giants: Amazon Web Services (AWS) and Google Cloud.

### Key Takeaways: 
1. Definition of AWS and Google Cloud
2. Features of these services
3. Key differences between AWS and Google Cloud
4. Advantages and disadvantages of these cloud computing services

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones  - approved.
