### ISSUE TITLE
Web Scraping in Nodejs using axios and cheerio

### ISSUE THREAD

**Issue by rohanreddych** [section-io/engineering-education#727]
- Introduction to web scraping
-Making requests with Axios
- HTML parsing using cheerio.js

Example of building a web scraping site to scrape classifieds sites such as craigslist. Please let me know if this topic is acceptable.

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @rohanreddych , but web scraping is a topic area that we prefer not to publish content around, as we actively employ solutions aimed at preventing web scraping technologies. Please select a different topic area to explore.
