### ISSUE TITLE
Ensemble Learning Techniques to Improve Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#728]
### Brief Summary: 

We build machine learning models to provide the best possible predictions to a given problem. However, a single model may not make the best predictions and may be subject to errors such as variance and bias. To reduce these errors and improve the predictions, we may combine multiple models into a single model. This is what is known as ensemble learning. We explore ensemble learning techniques that can be used to improve the machine learning process.

### Key Takeaways: 

Reader should:

1. Receive an introduction to ensemble learning.
2. Explore why ensemble learning is beneficial to the machine learning process.
3. Understand at least 3 advanced ensemble learning techniques in detail.
4. Understand a couple of basic ensemble techniques.

### References: 

https://blog.statsbot.co/ensemble-learning-d1dcd548e936

https://towardsdatascience.com/ensemble-methods-in-machine-learning-what-are-they-and-why-use-them-68ec3f9fef5f

https://towardsdatascience.com/ensemble-learning-techniques-6346db0c6ef8

https://heartbeat.fritz.ai/a-guide-to-ensemble-learning-390027fe38b8

https://www.analyticsvidhya.com/blog/2018/06/comprehensive-guide-for-ensemble-models/

**Comment by ninjaginja** [comment]
good topic @collins-a - approved.
