### ISSUE TITLE
How developers can leverage advanced features in Google Sheets

### ISSUE THREAD

**Issue by ipitah** [section-io/engineering-education#729]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

1. Google has provided apps for use by users. 
2. Google sheet is a spreadsheet that is available for every user with a google email. 
3. The spreadsheet offers added capabilities that are not available in other spreadsheets like 

- offer data collection tool, 
- web app, 
- develop a mobile app, 
- storage, 
- collaboration, 
- ease of use, availability, 
- cost, functions, 
- add-ons, 
- APIs support, etc.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. Using google sheet is easy and the user friendly.
2. Google sheet add more functionality thus enhancing service delivery
3. Google sheet is available for all users with a google email and has offline access.
4. Data can be accessed through a web app, mobile app, and the spreadsheet itself.
5. Data can be fed by the use of google forms.

### References: 

1. https://www.wallstreetmojo.com/excel-vs-google-sheets/
2. https://helpdeskgeek.com/office-tips/google-sheets-vs-microsoft-excel-what-are-the-differences/
3. https://tallyfy.com/microsoft-excel-vs-google-sheets/
4. https://www.tillerhq.com/the-ultimate-excel-vs-google-sheets-comparison/
5. https://spreadsheetpoint.com/excel-vs-google-sheets/
6. https://www.ionos.com/digitalguide/online-marketing/online-sales/google-sheets-vs-excel/
7. https://blog.tcea.org/mobile-app-from-google-sheets/
8. https://www.appsheet.com/HowItWorks/DataSource/google-drive
9. https://developers.google.com/apps-script/guides/web
10. https://developers.google.com/gsuite/add-ons/editors/sheets
11. https://support.google.com/docs/answer/2917686?hl=en

Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Interesting topic @ipitah. From your summary description, it sounds as if you intend to focus more on how developers can leverage advanced features in Google Sheets, which is a great topic area to explore. I'd suggest updating the title to reflect this.

**Comment by ipitah** [comment]
Great, will change it. Do I proceed?

**Comment by ninjaginja** [comment]
Yes, you can go ahead and proceed with drafting the article.

**Comment by ipitah** [comment]
Hi, I have my article ready, How do I submit the draft?
