### ISSUE TITLE
Introduction to JUnit and Mockito

### ISSUE THREAD

**Issue by john-amiscaray** [section-io/engineering-education#730]
### Brief Summary: 
JUnit is an incredibly popular framework used to write unit tests for your java applications. Learning to use it as a Java developer is an important skill that helps you increase the quality of your code. Along with JUnit, we will also have a look at using Mockito, a framework to help us create mock objects for our unit tests. To learn how to use these frameworks, we will be creating tests for a java class that performs basic math operations.

### Key Takeaways: 
- What is JUnit
- How to write unit tests with JUnit
- Why we would need to create mock objects
- Creating mock objects for our unit tests with Mockito
- Best practices/tips for writing unit tests (ex. display names for your unit tests, what types of tests to write, structure of your tests)

### References: 
N/A

**Comment by ninjaginja** [comment]
great topic @john-amiscaray - approved
