### ISSUE TITLE
Breaking Down PaaS vs SaaS vs IaaS

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#733]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

IaaS, PaaS, and SaaS stand for the three main categories of cloud computing. Cloud computing is the practice of using a network of different servers that host, store, manage, and process data online. Many business owners do not know the difference between these offerings and are therefore unaware of which option is best for their company. In this article, I'll break down the difference between these three models to help you decide which fits your needs best. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. An overview of PaaS, SaaS, and IaaS
2. Examples of SaaS, PaaS, and IaaS
3. Pros and Cons of PaaS, SaaS, and IaaS
4. Key Differences 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @EKahuha, however we've already covered this exact topic on our blog (even using the same title) - https://www.section.io/blog/comparing-paas-saas-iaas/. Please select a different topic area to explore.
