### ISSUE TITLE
Understanding the LAMP Stack

### ISSUE THREAD

**Issue by kvardhan10** [section-io/engineering-education#736]
### Brief Summary: 
Solution Stacks are combination of software or application programs used to form a computing platform. This article will discuss about one such stack - the LAMP Stack. The article will include a brief description about its components, usage and applications.

### Key Takeaways: 
The readers will be able to understand the 4 main parts of LAMP Stack and how they can be used to create web applications. The readers will also learn about the importance of each part:
1)**L**inux - OS
2)**A**pache - Web layer
3)**M**ySQL - Database layer
4)**P**HP and its alternatives - Scripting layer 

### References: 
https://en.wikipedia.org/wiki/LAMP_(software_bundle)

**Comment by ninjaginja** [comment]
good topic @kvardhan10 . Please be sure that your content is sufficiently unique from the definitions and descriptions already supplied in readily available resources.

**Comment by kvardhan10** [comment]
Sure. Will definitely keep that in mind👍
