### ISSUE TITLE
 Google Play In-App Review using Android Studio

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#737]
### Brief Summary: 
A user would typically launch the google play store to review or rate your application. Chances are, not many users got the interest to launch the google play store every time they need to do a review. 

However, you can prompt users to submit Play Store ratings and reviews within your application without leaving the application. Users can leave a review without opening google playstore. These encourage users to give feedback on your application.

In this guide, we'll discuss how to implement "Rate this app" functionality within the android application context using Google Core API. We will check how a user can make the application in 1 to 5 stars and leave a comment. This review/rating will eventually be displayed in the google play store. 

### Key Takeaways: 

 - When to show in-app review
 - Setting in-app review 
 - Implementing in-app review
 - Testing in-app reviews

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @kimkimani - approved
