### ISSUE TITLE
Introduction to Greedy Algorithms

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#738]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this article, I discuss the greedy approach of solving problems, the use cases and consider the example of optimising profit given a list of stock prices. The author will be able to appreciate the advantages of greedy approach and understand its limitations.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Introduction to greedy approach 
2. Optimising profit given a list of stock prices using greedy approach. Code in Python
3. Analysis of the code and output.
4. Advantages and limitations of greedy approach.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
