### ISSUE TITLE
Introduction to Divide and Conquer Algorithms

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#739]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this article, we discuss the divide and conquer paradigm. Understand the use cases and solve the problem of optimising the profit given a list of stock prices. The reader will observe the rise in accuracy and rise in computational complexity when compared with greedy method. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Divide and conquer approach : introduction and use cases 
2. Code to optimise profit given a list of stock prices.
3. Analysis of the output. We observe the lack of ability of divide and conquer to generate negative profits.
4. Advantages and limitations of divide and conquer algorithms.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
another good topic @lalith1403 - approved
