### ISSUE TITLE
Introduction to constructors in C++

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#741]
### Brief Summary: 
Each time when you write a program you create a function, which is responsible for initializing the variable and before the end of the program you call a function to destroy the allocated variables. To automate this feature, C++ provides the concept of constructors and destructors . In this article, I’m going to explain all about constructors and constructor functions in C++.

### Key Takeaways: 
1. Concept of constructor
2. Types of constructors
3. Implementation of constructors in C++ programs

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Dawe-7 - approved
