### ISSUE TITLE
How JavaScript Uses Web Browser APIs To Achieve Asynchronisity 

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#742]
### Brief Summary: 
JS is a Synchronous Language. However, today asynchronous functionality is the backbone of the web. In this guide, we go over how JS uses Web Browser APIs to achieve asynchronous functionality.

### Key Takeaways: 
Understanding primitive callbacks in JS
Understanding one way JS achieves asynchronicity.

### References: 
[MDN docs](https://developer.mozilla.org/en-US/)

**Comment by ninjaginja** [comment]
good topic @adrianmurage - approved
