### ISSUE TITLE
React Native Razorpay Integration

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#743]
### Brief Summary
Razorpay is a payments solution in India that allows businesses to accept, process, and disburse payments with its product suite.
In this tutorial, we'll be going over how to build a React Native app with Razorpay to accept payments. 

### Key Takeaways
- Project Structure
- Setup Razorpay to Accept Payments
- Payment Verification

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved
