### ISSUE TITLE
Getting started with C#

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-io/engineering-education#746]
### Brief Summary: 
C# is a modern object-oriented programming language which is designed for developing web and  networking applications. It is portable and requires .NET framework on a machine for it to run. 
The performance of c# is exceptional in terms of speed and it has the ability to cheaply use resources.
### Key Takeaways: 
By the end of this tutorial the reader will be able to:

- install and set up .NET framework
- write a `hello world` application using C#
- understand the basic syntax of a C# application
- add two numbers using C#
### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Jeff-mwangi - approved.
