### ISSUE TITLE
Introduction to Data Integration in Talend Open Studio

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#751]
### Brief Summary: 
Talend Open Studio is an application that provides solutions for big data, data quality, data preparation and data integration. In this application, data from various sources is combined to provide meaningful information. This article provides an overview of data integration in this application.. 

### Key Takeaways: 
1. Introduction to Talend Open Studio
2. What is Talend Data Integration
3. Benefits of Talend Data Integration
4. Components of Talent Data Integration
5. Application of Talend Data Integration

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
