### ISSUE TITLE
Understanding MapReduce in Hadoop

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#752]
### Brief Summary: 
MapReduce is a Hadoop framework that is used for writing applications that can process huge amounts of data. This article provides an understanding of this framework, and how it works. 

### Key Takeaways: 
1. Introduction to MapReduce
2. How MapReduce works
3. The Algorithm used 
4. Phases of the MapReduce model
5. Benefits of MapReduce

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
