### ISSUE TITLE
Capsule Networks (CapsNet) : An Enhancement to Convolution Neural Networks (CNNs)

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#755]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A Capsule Neural Network (CapsNet) is an Artificial Neural Network (ANN) that is used to model better hierarchical relationships. These networks are an improvement to Convolutional Neural Networks (CNNs). They were built to solve the orientation problem in CNNs. 
The intution behind this network is to add structures referred to as "capsules" to a Convolutional Neural Network (CNN), and to reuse the outputs from several of those capsules to form more stable representations for higher capsules.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, you should be able to understand:

1. The Orientation Problem in Convolutional Neural Networks (CNNs)
2. The Pooling problem in CNNs 
3. How Capsule Networks work?
4. The CapsNet Architecture

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. Dynamic Routing Between Capsules https://www.cs.toronto.edu/~hinton/absps/DynamicRouting.pdf

**Comment by ninjaginja** [comment]
good topic @Bayler - approved
