### ISSUE TITLE
Addressing Underspecification in Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#756]
### Brief Summary: 

It is common to have machine learning models perform well after training but offering poor performance after being deployed. A possible cause of this is known as underspecification. Models are supposed to simulate the real world. However, a challenge that manifests is that there is no guarantee that the model one selects is the absolute best for one's intended application or reflects best the logic of the application. Underspecification undermines the credibility of machine learning models. This article sheds light on the challenge of underspecification and how to address it. 

### Key Takeaways: 

Reader should:
1. Understand the theory behind underspecification 
2. Be aware of the challenges underspecification poses
3. Take away 5 detailed methods to address/prevent/fix underspecification

### References: 

https://www.technologyreview.com/2020/11/18/1012234/training-machine-learning-broken-real-world-heath-nlp-computer-vision/

https://blog.roboflow.com/google-paper-underspecification-machine-learning/

https://deepai.org/publication/underspecification-presents-challenges-for-credibility-in-modern-machine-learning#:~:text=Underspecification%20Presents%20Challenges%20for%20Credibility%20in%20Modern%20Machine,return%20many%20predictors%20with%20equivalently%20strong%20held-out%20

https://medium.com/making-ai-make-money/ai-hype-what-does-googles-underspecification-bombshell-mean-for-machine-learning-credibility-4c8d6594b5f6

https://medium.com/intuitionmachine/deep-learning-underspecification-and-causality-bf762f118780

https://www.datascienceexamples.com/underspecification-in-ai/

**Comment by ninjaginja** [comment]
cool topic @collins-a - approved
