### ISSUE TITLE
Introduction to Android Application Development in Visual Basic and Basic4Android (B4A) Part I

### ISSUE THREAD

**Issue by Tsanguu** [section-io/engineering-education#757]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Basic4Android is a rapid application development (RAD) tool for native Android applications. B4A language is similar to Visual Basic and Visual Basic .Net and uses an object-based and event-driven approach. Currently, B4A is 100% free. This article will be the ultimate beginner's guide to B4A.

### Key Takeaways: 
Introduction to B4A
Getting the tools ready
Using B4A-Bridge
Using B4A Visual Designer
Example App 1: Hello World App
Example App 2: 
Conclusion

### References: 
https://www.b4x.com/android/documentation.html

**Comment by ninjaginja** [comment]
good topic @Tsanguu - approved
