### ISSUE TITLE
Firebase password and email authentication in Android using Kotlin

### ISSUE THREAD

**Issue by Ericgacoki** [section-io/engineering-education#760]
### Brief Summary: 
Firebase authentication is one of the most secure ways of controlling access to your app. Authenticated users can easily sync data between devices and analyze their app usage. This article will walk you through every step involved in setting up an Authentication system.

### Key Takeaways: 
By the end of this tutorial the reader should be able to:

1. Create a firebase project
2. Implement Firebase APIs
3. Control users accounts from firebase console

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Ericgacoki - approved
