### ISSUE TITLE
IoT Deployments with SD-WAN 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#769]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Internet of things (IoT) devices require adequate network resources once they are up and running. If left unchecked, IoT devices can place a tremendous strain on a network and lead to a host of performance issues. SD-WAN comes in to support advanced IoT deployments. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is SD-WAN
2. SD-WAN vs. traditional WAN 
3. SD-WAN as IoT enabler 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
