### ISSUE TITLE
Public Cloud vs. Hybrid Cloud vs. Private Cloud

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#774]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Cloud computing covers a range of categorizations and architecture models that can be classified into three main types: public cloud, hybrid cloud, private cloud. The cloud environment provides an easily accessible online portal that makes it suitable for the user to manage the compute, storage, network, and application resources. This article will explore public, private, and hybrid cloud environments, their benefits and drawbacks, and help users decide on the best cloud solution according to their needs.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1.  Benefits of public cloud, hybrid cloud, and private cloud
2. Drawbacks of public cloud, hybrid cloud, and private cloud
3. When to use public cloud, hybrid cloud, and private cloud

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
great topic @EKahuha - approved
