### ISSUE TITLE
Cost Optimization with Cloud Bursting 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#775]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Cloud bursting is defined as a configuration set up between the public cloud and the private cloud to deal with the peaks in IT demands with the advantage of saving on costs. When resource requirements exceed what can be provided by the on-premise or collocated data center, the cloud bursting application will temporarily shift data into a public cloud to free up space in the primary data center.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

What is Cloud Bursting 
Benefits of Cloud Bursting
Challenges of Cloud Bursting 
How to save money with cloud bursting
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved.

As a side note, I noticed that you have several open issues/topics. We try to focus on seeing articles through from idea to published state as quickly as possible, and working simultaneously across several articles can have the effect of slowing these processes. We try to advise working on a single article from start to finish before suggesting new topics. This also allows you to incorporate feedback into subsequent articles.
