### ISSUE TITLE
Microsoft Azure For Business

### ISSUE THREAD

**Issue by tambastar** [section-io/engineering-education#776]
Brief Summary: 
How Microsoft Azure can be used for business. Some of the services that are offered by Microsoft Azure to help in business development and growth

Key Takeaways: 

1. What is Microsoft Azure
2. Microsoft Azure Services
3. How business can use the Microsoft Azure for business development
4. Case Studies using Microsoft Azure

References: 
https://azure.microsoft.com/en-us/

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @tambastar, however this topic is too vague and general for the type of content that we seek to publish. Please select a topic area that is more targeted to a specific challenge or use case that a software engineer might be looking to solve.
