### ISSUE TITLE
TensorFlow vs PyTorch: Which one to pick?

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#783]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

TensorFlow and PyTorch are both deep learning frameworks used actively for research and development of deep learning application. In this article, we'll be exploring which one is the best to use and why? 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, the reader should understand:

1. What is TensorFlow?
2. What is PyTorch?
3. What are the differences between these two frameworks?
4. Which one to pick?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Bayler - approved
