### ISSUE TITLE
How To Deploy A Django App To Heroku

### ISSUE THREAD

**Issue by twish-254** [section-io/engineering-education#788]
### Brief Summary:
Deploying a Django app to Heroku is not as straight-forward as it sounds as it requires additional package installation and setup. You can make work easier by using Heroku pipelines to build your application automatically.
### Key Takeaways:
By the end of this tutorial, the reader will be able to:
- configure Heroku environmental variables
- setup white noise to support serving static assets
- set up a Postgresql database in Heroku
- Build Django code from GitHub
- set up Heroku pipelines
### References:
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @twish-254. This is a bit of a gray area for us right now, as Heroku has become more of a competitor to Section. I think we'd prefer to steer away from Heroku-related content at this time. Please select a different topic area to explore. Thanks.
