### ISSUE TITLE
An Introduction to Activation Functions

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#789]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Understand what activation functions are, why are they needed, and the various types. We will also code the classes for each of these activation functions and therefore understand them better.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. What are activation functions?
2. Why are they needed and their types.
3. Code to explain the same. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
