### ISSUE TITLE
Understand Exception Handling in JavaScript

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#793]
### Brief Summary: 
Errors are common in programming. An exception signifies that the code has a problem that requires to be solved. Also, it breaks the normal flow of the code. When a JavaScript statement generates an error, it is said to throw an exception.  Instead of proceeding to the next statement, the JavaScript interpreter checks for exception handling code. This article will give developers an in-depth understanding of Exception Handling in JavaScript.

### Key Takeaways: 
1. What is Exception Handling
2. JavaScript Error types
3. How to handle exception in JavaScript

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @JudyNduati  - approved
