### ISSUE TITLE
Is Node.js a good choice to create an App based on Micro-services?

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#795]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

The connection between Node.js and micro-services is very deep. Node was created to make building apps based on micro-services easier and it's supposed to bring the idea that Node apps should be made up of small distributed nodes that communicate with each other to make the application work.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article the reader should:
     1. Able to explain the philosophy behind micro-services 
      2. Know the reason why Node.js is a good technology to consider when implementing this architecture
      3. Know the benefits micro-services offer

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
great topic @Pius1991  - approved. (One small note, please be sure to consistently refer to 'Node.js' throughout the article, not Node or NodeJS.)
