### ISSUE TITLE
Exception handling using c#

### ISSUE THREAD

**Issue by mohamedgh16** [section-io/engineering-education#797]
### Brief Summary: 
Programmers should be able to create an application that can handle or resolve exceptions, they should also enable clear, robust, and more fault-tolerant programs. *Exception handling* is used to make sure nothing goes wrong when running a program, and we should always cover all the possible errors using the tools of exception handling.

### Key Takeaways: 
1. Definition of exception handling.
2. Exception handling keywords (Try - Catch - Finally).
3. All the possible cases in exception handling.
4. Examples

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @mohamedgh16. There's already another article in the works around exception handling, and while I understand that you're suggesting covering this topic from the perspective of a different programming language, it is more repetitive than we like. Please select a different topic area to explore.
