### ISSUE TITLE
An Introduction to Question-Answering Systems

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#798]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Question answering systems are an interesting example of information retrieval, information extraction, and NLP systems. We will understand the key components of a question answering system and how they work. Reading this article should give the reader a thorough understanding of the architecture and the modules that build up this architecture.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Question- answering systems
2. Architecture
3. Analysis of the components involved
4. Applications
5. Scope of research
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
great topic @lalith1403  - approved
