### ISSUE TITLE
How to use local storage with JavaScript

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#802]
### Brief Summary: 

Local storage allow web applications to store temporary data on the browser. This information helps to improves the site's functionality. For instance, the data can help track users as they navigate across different pages. Local storage is cleared once the user closes the web page.

### Key Takeaways: 

 - What is local storage
 - How to perform CRUD functionalities on local storage
 - Debug errors showing up in the console.

### References: 

https://javascript.info/localstorage

**Comment by ninjaginja** [comment]
good topioc @WanjaMIKE - approved. You may also want to discuss when it's appropriate to use local storage and when it isn't.
