### ISSUE TITLE
Introduction to Active Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#804]
### Brief Summary: 

By nature, machine learning models are data-hungry. They require a lot of data in order to make decisions. However, always having high quality labeled data to train models is often a costly task. An answer to this would be to use an approach that can reduce the amount of training data needed to train a model. Active learning is such an approach. We dissect active learning in this article.

### Key Takeaways: 

Reader should:
1. Get an introduction to the theory and motivation behind active learning
2. Understand the steps to use active learning on unlabelled data
3. Learn three active learning frameworks

### References: 

https://blog.roboflow.com/what-is-active-learning/

https://towardsdatascience.com/active-learning-in-machine-learning-525e61be16e5

https://towardsdatascience.com/introduction-to-active-learning-117e0740d7cc

https://becominghuman.ai/accelerate-machine-learning-with-active-learning-96cea4b72fdb

https://towardsdatascience.com/active-learning-tutorial-57c3398e34d

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
