### ISSUE TITLE
HuggingFace: Understanding the Library

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#805]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
HuggingFace is an amazing company working on bringing massively trained language models to the masses. Therefore, they have built a considerable amount of tools in the past 2-3 years.  Getting an overview of the tools offered shall help beginners steer in a clear direction. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Why HuggingFace?
2. Understand the components of the library: Transformers, Tokenizers, and Datasets 
3. Some interesting applications built using the library
4. Scope of research using the PyTorch based library.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @lalith1403 - approved
