### ISSUE TITLE
Regular Expressions in Python

### ISSUE THREAD

**Issue by bloodprashure** [section-io/engineering-education#806]
### Brief Summary: 
Regular Expressions are known to be a tad bit complex owing to their syntax while writing code. Adding to this, the moving parts behind the scene are crucial in knowing why string comparisons are much faster while using regexes. This article aims to demystify regexes and help the reader understand how to match types of strings using regexes.

### Key Takeaways: 
1. Understand the role of FSMs in regexes
2.  Syntax of regexes
3. Reason behind performance boost

### References: 
https://www.w3schools.com/python/python_regex.asp

**Comment by ninjaginja** [comment]
good topic @bloodprashure - approved
