### ISSUE TITLE
Advances in Transfer Learning in Natural Language Processing

### ISSUE THREAD

**Issue by lalith1403** [section-io/engineering-education#811]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Transfer learning has been rapidly advancing the computer vision field. Everyone can implement classification, segmentation, detection algorithms without training them. A similar advance took place in the field of NLP when transformers were introduced. In this article, we will study the attempts made to solve tasks and how transformers solved the problem of language modeling. Going through this article should help the reader understand the transformer in detail.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Transfer learning in NLP
2. RNNs and LSTMs: Machine language translation 
3. Transformers and attention mechanism
4. Applications
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://arxiv.org/pdf/1706.03762.pdf

**Comment by ninjaginja** [comment]
We've already got several articles on transfer learning (https://www.section.io/engineering-education/search/?q=transfer%20learning), so I think it would be best to explore a new topic area.

**Comment by lalith1403** [comment]
None of them cover transformers and attention mechanism. I have endured there is minimal overlap. Actually I enter into transformers and language modelling using attention mechanism. I can assure you that it is completely different than the ones published.

**Comment by ninjaginja** [comment]
Ok, perhaps that can be better conveyed in the title? When I think of someone seeking out this content, I'm looking for what would make them click on this article.
