### ISSUE TITLE
Digital Assistants vs. Digital Companions

### ISSUE THREAD

**Issue by Pius1991** [section-io/engineering-education#813]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

In the recent past, the reliance on digital assistants has been enormous, and the number is still expected to grow tremendously over the coming years.
Almost everyone relies on digital assistants such as Siri, Alexa, and Google Assistants in our day to day lives as they make work easier, faster, and simple.
Digital assistants are convenient and easy to use, but the technology that is rapidly evolving and advancing is making us yearn for more convenience, dynamism, and more efficiency in our day to day life experiences.  This leads to the rise of digital companions – the natural evolution of digital assistants.  

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

By the end of this article, the reader should understand;
1.	What is digital assistant?
2.	What is digital companion? 
3.	What are the differences between digital assistants and digital companions? And how are they related?
4.	Applications of the digital assistants and digital companions.
5.	The transition from digital assistants to the digital companions

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @Pius1991  - approved
