### ISSUE TITLE
Automation in DevOps: An Overview

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#814]
### Brief Summary: 
Devops is a combination of software development and operations. This application shortens the life cycle of software development and enhances the quality of software.  Automation in DevOps is important because it enhances accuracy, speed and reliability. This article provides an overview of DevOps automation and how it works. 

### Key Takeaways: 
1. What is DevOps?
2. Why automation is needed in DevOps
3. How automation works in DevOps
4. DevOps automation tools

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @mbaabuones , but this is far more broad than we prefer for content. Automation in DevOps is more of a philosophy that underpins the entire DevOps movement. We're looking for more practitioner-focused content that seeks to address narrowly focused developer challenges.
