### ISSUE TITLE
Introduction to Random Forest in Machine Learning 

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#815]
### Brief Summary: 
A random forest is a supervised machine learning algorithm that is used to solve regression and classification problems. This article introduces readers to this concept. 

### Key Takeaways: 
1. What is a Random Forest?
2. Features of a random forest algorithm
3. How random forest algorithm works
4. Classification of random forest
5. Applications of random forest

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
