### ISSUE TITLE
Introduction to Theory of Computation

### ISSUE THREAD

**Issue by OMONDIELLY** [section-io/engineering-education#817]
### Brief Summary: 
Have you ever wondered why some computer  programs run so efficiently? Computers programs can be viewed as abstracted mathematical models. A good understanding of the theory of computation is required so as to write  efficient computer programs while focusing on capabilities and limitations of computers.
This article will explore the basics of theory of computation and the role it plays in efficiency of computers.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1.Importance of theory of computation
2. Basics of Automata
3. Computability theory
4. Complexity theory

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @OMONDIELLY - approved
