### ISSUE TITLE
Getting started with Windows forms using c#

### ISSUE THREAD

**Issue by mohamedgh16** [section-io/engineering-education#818]
### Brief Summary: 
Windows forms allow the programmers to create a graphical user interface (GUI) that allows the interaction with the program visually. It provides one of the most productive ways to create desktop apps based on the visual designer provided in Visual studio. You can create smart-client apps that display information, request input from users, and communicate with remote computers over a network.

### Key Takeaways: 
1.Windows form uses.
2.Tool box.
3. Properties window.
4.make a basic interactive calculator.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mohamedgh16 - approved
