### ISSUE TITLE
Integrating Django with TinyMCE 

### ISSUE THREAD

**Issue by Sajeyks** [section-io/engineering-education#819]
### Brief Summary: 
TinyMCE is a rich text editor that enables users to enter text ,messages,images and links etc.

### Key Takeaways: 
By the end of the tutorial the reader should be able to :
    1. Install TinyMCE
    2. Add default configuration for TinyMCE editor 
         in settings.py 
    3.Getting TinyMCE into action.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Sajeyks - approved
