### ISSUE TITLE
Understanding Regression Analysis in Machine Learning

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#823]
### Brief Summary: 
Regression analysis is a statistical tool for estimating the relationship between a target variable and predictor variables. This article provides an overview of regression analysis in machine learning. 

### Key Takeaways: 
1. What is regression analysis?
2. Regression model in machine learning
3. Types of regressions in machine learning
4. Applications of regression in machine learning
5. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
This topic has already been sufficiently covered in this article - https://www.section.io/engineering-education/supervised-learning-algorithms/. Please select a different topic to explore, and be sure to cross check against published articles and open issues/PRs to ensure there's no overlap with other articles.
