### ISSUE TITLE
Web Scraping with Python Beautiful Soup

### ISSUE THREAD

**Issue by Tsanguu** [section-io/engineering-education#824]
### Brief Summary: 
Beautiful Soup is a python library that can parse HTML and XML strings. Web scraping is the process of getting information from the internet specifically web pages.

### Key Takeaways: 
Introduction to web scraping
Installing Beautiful Soup
Scraping HTML content from a page
Parsing HTML with Beautiful Soup
Extracting data from HTML elements
Saving extracted content

### References: 
https://www.crummy.com/software/BeautifulSoup/bs4/doc/
https://programminghistorian.org/en/lessons/intro-to-beautiful-soup

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @Tsanguu , however we do not wish to publish any articles on web scraping technologies, as we have solutions that actively work against web scrapers. Please select a different topic area to explore.
