### ISSUE TITLE
 MySQL with Node.js

### ISSUE THREAD

**Issue by kimkimani** [section-io/engineering-education#826]
### Brief Summary: 
MySQL is an open-source relational database management system. This guide discusses how to use it with Node.js.

### Key Takeaways: 
We will discuss the common database operation and how to implement them in Node.js using MySQL.
They include;
- Creating a Database
- Adding Tables and Rows
- Insert into Database
- Fetch and Display From Database
- Update and Delete Database Records

### References: 
https://www.npmjs.com/package/mysql

**Comment by ninjaginja** [comment]
great topic @kimkimani - approved
