### ISSUE TITLE
Getting Started with AWS DynamoDB

### ISSUE THREAD

**Issue by Tsanguu** [section-io/engineering-education#828]
### Brief Summary: 
Amazon DynamoDB is a fully managed NoSQL database service. DynamoDB provides fast and predictable performance with seamless scalability. This article will discuss DynamoDB extensively including DynamoDB Operations.

### Key Takeaways: 
- Introduction to DynamoDB
- Setting up DynamoDB
- DynamoDB Operations (Create, Write, Read, Update, Query)
- DynamoDB API and SDK

### References: 
https://aws.amazon.com/dynamodb/

**Comment by ninjaginja** [comment]
good topic @Tsanguu - approved. I'd suggest working Python into the title so readers will know what the example will entail.
