### ISSUE TITLE
What it Takes to be a Flutter Developer.

### ISSUE THREAD

**Issue by bluemutheu** [section-io/engineering-education#830]
### **Brief Summary:**
In a time and date in which technology allows for the creation of cross-platform applications despite a wide range of Operating systems available , it is important to shade light into some of these careers and have a look at who is responsible for creating such applications and how they do it. The article will looking into Flutter Developers as a profession and what their contribution to technology is. A deep dive into Flutter Developers and their use of Flutter open Source platform will be explained bringing to an understanding of what exactly is entailed in the profession.

### **Key Takeaways:** 

1. The article will bring a vast understanding of who a Flutter Developer is to the reader. 

2. The prior knowledge and skills needed to become a Flutter Developer will also be discussed in the article. 

3. It will explain the key roles and responsibilities of a Flutter Developer and what to expect on to do a daily basis pursuing the career. 

4.The article will describe in depth the tools used by a Flutter developer bring the reader to an understanding of the tools they should familiarize themselves with.

### **References:**
N/A.

**Comment by ninjaginja** [comment]
good topic @bluemutheu - approved. As you're drafting this article, please be mindful of avoiding overly general concepts and try to provide as many actionable takeaways as possible to enrich the developer's understanding of this topic.

**Comment by ninjaginja** [comment]
Also, I see that you suggested another topic as well, which I've provided feedback on. We recommend focusing on seeing an article through from start to finish before suggesting additional topics. This will help you incorporate any and all feedback into future articles, while also allowing us to generate payouts faster.

**Comment by bluemutheu** [comment]
Okay understood, @ninjaginja.
