### ISSUE TITLE
Understanding Variables In JavaScript

### ISSUE THREAD

**Issue by twish-254** [section-io/engineering-education#831]
### Brief Summary: 

Variables are an important concept in any programming language, this makes it essential for any person interested in javascript programming to learn variables. Variables are used to hold any type of data. In javascript, you can declare variables using keywords such as var, const or let.

### Key Takeaways: 
By the end of this tutorial the reader should be able to :

- Understand different types of variables
- Declare variables in JavaScript
- Use the variables in JavaScript
- understand the scope of variables
- Differentiate between const, let and var

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @twish-254  - approved.

**Comment by twish-254** [comment]
Thank you
