### ISSUE TITLE
The Ultimate Guide to Learning Data Science.

### ISSUE THREAD

**Issue by bluemutheu** [section-io/engineering-education#836]
### Brief Summary: 
The increased use of data to gear the growth of businesses (data-driven businesses), has prompted to the demand of data scientists in the world. More and more people are switching their profession to become data scientists or gaining interest in the field. The article will be a guide on how to maneuver into the field for those who are interested in the field or need to familiarize themselves with data science especially those who are not from a technical or computer science background.

### Key Takeaways: 

1. The article will enlighten the reader on where to begin learning data science, gain data skills to when the reader should start indulging in projects to build up on their experience. 

2. Other key takeaways will be the relevant material to look into, where to find them and most reliable ones to learn data science from scratch. 

3. The reader will take on the dos and the don'ts of studying data science to gain the most of the journey from scratch to a professional data scientist or gain data skills set.

### References: 
https://www.dataquest.io/blog/learn-data-science/
https://developer.ibm.com/technologies/data-science/articles/

**Comment by ninjaginja** [comment]
Thanks you for the topic suggestion @bluemutheu , however this topic is far more broad than we prefer with content. We're really looking for articles that address specific developer challenges from a unique angle, such as with individual projects or original code examples. Please feel free to suggest another topic based on this feedback.
