### ISSUE TITLE
Comparing Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS)

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#841]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A network intrusion is any unauthorized activity on a computer network. Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS) can help block intruders who aim to steal sensitive data, cause data breaches, and install malware.
IIDS analyze network traffic for signatures that match known cyber-attacks. IPS also analyze packets and stops the packet from being delivered based on the attacks it detects, helping stop the attack.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. An overview of IDS and IPS 
2. Problems IDS/IPS Address 
3. IDS vs. IPS
4. Why IDS and IPS are Critical for Cybersecurity
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
