### ISSUE TITLE
How to create CRUD API with Spring MVC

### ISSUE THREAD

**Issue by paulodhiambo** [section-io/engineering-education#845]
### Brief Summary: 
Spring Boot is an open source Java-based framework that makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run".
This article aims to teach the reader how to create various crud APIS with Spring boot and Spring MVC.

### Key Takeaways: 
Basic [Spring Boot](https://spring.io/guides/gs/spring-boot/) knowledge is required to understand the concept covered in this article.
1. What is Spring Boot and Spring MVC.
2. Basics of Spring MVC.
3. How to create crud API Spring MVC.
4. Basics of Spring Data JPA. 
5. Using H2 database for data persistence.

### References: 
[Spring Data JPA](https://spring.io/projects/spring-data-jpa)

**Comment by ninjaginja** [comment]
great topic @paulodhiambo - approved. I would suggest making the title more descriptive of what the reader can expect to learn or be able to do after reading this article (e.g. 'How to...', 'Creating APIs with...')
