### ISSUE TITLE
Laravel CRUD API

### ISSUE THREAD

**Issue by jumamiller** [section-io/engineering-education#848]
### Brief Summary: 
Laravel is a PHP-based web framework with an expressive, elegant syntax. It is termed the framework for web artisan. The foundation has already laid the foundation, freeing the web artisan to create without sweating the small things. Laravel is model after the MVC (Model View Controller) architecture and revolves around CRUD (Create, Retrieve, Update, Delete) operations.

### Key Takeaways: 
1. Installing Laravel 8 Application.
2. Models and Migrations
3. Creating Resource routes.
4. Creating Controllers.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @jumamiller , however it looks like this topic is already being covered in #652
