### ISSUE TITLE
How and when to apply session storage with JavaScript

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#850]
### Brief Summary: 

Session storage allows web applications to store data in the browser. It is an excellent alternative to cookies which are increasingly becoming insecure. Session storage is usually cleared whenever a user exits an application.

### Key Takeaways: 
-Understand what is session storage.
 - Know how to implement session storage.
- Know when to implement session storage.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE  - approved
