### ISSUE TITLE
All about fragments in android applications

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#852]
### Brief Summary: 
Fragments are simply independent android components that can be used in activities. Though a fragment runs in an activity, it has its own lifecycle and layout.

### Key Takeaways: 
 - Understand what are fragments
 - Know how to use fragments in android 
 - Debug errors in the implementation of fragments.

### References: 

https://developer.android.com/guide/fragments

**Comment by ninjaginja** [comment]
This is a good topic @WanjaMIKE - approved. 

As a side note, I'd suggest seeing some of your other articles through before suggesting new topics. Keeping a clean pipeline of articles that are actually in progress helps us facilitate reviews and payouts at a faster rate for everyone.

**Comment by WanjaMIKE** [comment]
@ninjaginja Noted
