### ISSUE TITLE
Building a CI/CD pipeline using gitlab

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#853]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Gitlab is a platform, similar to github, that allows users to host repositories and use git. In this article, I will cover the basics of gitlab and how it works by building a simple CI ppeline. Gitlab offers a feature called gitlab-ci, which allows users to build Ci pipelines and run them in the gitlab UI. 

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. The readers will be able to setup a gitlab environment and understand how to use it
2. They will be able to setup their own CI/CD pipeline in gitlab using gitlab-ci
3. Understand how gitlab-runner is used to deploy a CI pipeline 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://docs.gitlab.com/

**Comment by ninjaginja** [comment]
good topic @adithbharadwaj - approved
