### ISSUE TITLE
Understanding Loops and Iterations in Dart.

### ISSUE THREAD

**Issue by bluemutheu** [section-io/engineering-education#856]
### Brief Summary: 
Dart is a programming language developed by Google to develop cross-platform applications using a framework called flutter. Loops and Iterations are an important aspect of any programming language and ought to be understood well. This article will explain the loops and iteration of the language to bring an understanding to the user.

### Key Takeaways: 
1. The types of loops and iterations in Dart Language.

2. Know the syntax of loops and iteration in Dart.

3. Understand how loops and iterations in Dart work.

### References: 
N/A.

**Comment by ninjaginja** [comment]
good topic @bluemutheu - approved.
