### ISSUE TITLE
Express Server for Agora Cloud Recording

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#859]
## Brief Summary

In this tutorial, we'll be going over what Agora's Cloud recording is and build an Express server to record an Agora live stream using their APIs and store it in Amazon S3.

## Key Takeaways

- Project Structure
- Cloud Recording vs On-Premise recording.
- Record Streamers Live feed and store it in Amazon S3.

**Comment by ninjaginja** [comment]
cool topic @zolomohan - approved
