### ISSUE TITLE
Understanding Hill Climbing Algorithm in Artificial Intelligence

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#863]
### Brief Summary: 
Hill climbing algorithm is an AI algorithm that increases value continuously until a peak solution is achieved. This algorithm is utilized in the optimization of mathematical problems. This article provides an understanding of this important concept. 

### Key Takeaways: 
1. Introduction to hill climbing algorithm
2. Features of hill climbing algorithm
3. State space diagram analysis
4. Problems in hill climbing algorithm
5. Types of hill climbing algorithm
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
