### ISSUE TITLE
Automation Testing in Selenium: An Overview

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#864]
### Brief Summary: 
Selenium is a popular open-source tool used by software developers for automation testing. This application has played an important role in eliminating some of the challenges experienced in manual testing. This article provides an overview of this important software. 

### Key Takeaways: 
1. Introduction to Selenium
2. Why Selenium is widely used in automation testing
3. Components of Selenium
4. How automation testing in Selenium works
5. Limitations of Selenium automation testing
6. Conclusion

### References: 
https://www.seleniumeasy.com/selenium-tutorials/introduction-to-selenium

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
