### ISSUE TITLE
How AIOps is transforming IT operations 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#865]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Digital transformation encompasses DevOps and the adoption of cloud and new technologies like containers. It represents a shift from centralized IT to applications and developers, an increased pace of innovation and deployment, and the acquisition of new digital users—machine agents, Internet of Things (IoT) devices, Application Program Interfaces (APIs), etc. All of these new technologies and users are straining traditional performance and service management strategies and tools to the breaking point. AIOps is the IT operations solution required to handle these digital transformation issues. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is AIOps
2. Benefits and challenges of AIOps 
3. How AIOps works 
4. Best AIOps software 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
