### ISSUE TITLE
Deploying Machine Learning models using Flask

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#869]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this article, we will understand how Machine learning models are built and deployed in Flask webframework. A step-by-step guide for building an application using Flask will also be demonstrated.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand how Machine learning models are built and deployed
- The reader will have an overview of Flask framework

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://www.coursera.org/learn/deploying-machine-learning-models
- https://stackoverflow.blog/2020/10/12/how-to-put-machine-learning-models-into-production/
- https://www.analyticsvidhya.com/blog/2020/04/how-to-deploy-machine-learning-model-flask/

**Comment by ninjaginja** [comment]
good topic @srishilesh - please be sure that there is not significant overlap with the two articles being worked on in #717 .

**Comment by srishilesh** [comment]
> good topic @srishilesh - please be sure that there is not significant overlap with the two articles being worked on in #717 . 

Alright 😀
