### ISSUE TITLE
Getting started with NodeMCU

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#870]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
In this article, we will give an intro on various microcontrollers like NodeMCU and Arduino. We will also get an overview on how to setup Arduino IDE and build a "Hello World" project with NodeMCU.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand about various microcontrollers and its usage
- The reader will be setting up and building a simple project with NodeMCU

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://en.wikipedia.org/wiki/NodeMCU
- https://www.arduino.cc

**Comment by ninjaginja** [comment]
good topic @srishilesh - approved

**Comment by srishilesh** [comment]
@ninjaginja I am currently working on this issue. Requesting to re-open.
