### ISSUE TITLE
Working with forms in django

### ISSUE THREAD

**Issue by Anitaachu** [section-io/engineering-education#871]
**### Brief Summary:** 
Django is a high-level python open source backend framework with various in-built libraries and packages. Django framework is easy, fast and simple, due to its inbuilt libraries a lot of functionalities can be built with a fewer lines of code rather than starting from scratch. One of the inbuilt package is **django forms**. This article provides a walk through of how this form works and how they are created with only a few lines of code.

### Key Takeaways: 

1. An introduction to django forms.
2. The various types of django forms and uses.
3. How to import django form package.
4. Saving form data in database.

### References: 
https://www.djangoproject.com/
https://docs.djangoproject.com/en/3.1/ref/forms/api/
https://djangobook.com/mdj2-django-forms/

**Comment by ninjaginja** [comment]
good topic @Anitaachu - approved
