### ISSUE TITLE
Understand Hashing in Cryptography

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#876]
### Brief Summary: 
Hashing is a method of cryptography that converts any form of data into a unique string of text using a mathematical function. This article will give an in-depth understanding of what is cryptographic hashing, and how it works. It will also touch on cryptographic functions and the different types of hashing. 

### Key Takeaways: 
1. What is Hashing
2. How Hashing Works
3. Cryptographic Hash Functions
4. Types of Hashing
5. Applications of Hashing

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @JudyNduati - approved
