### ISSUE TITLE
Working with React Hooks

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#879]
### Brief Summary: 
React is a  JavaScript library for building interactive user interfaces. This a beginner tutorial aimed at helping dive into React ecosystem with functional component.

### Key Takeaways: 
1. Introduction to React hooks
2. Common React Hooks
4. Creating a custom hook

### References: 
https://reactjs.org/

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @ReactifyStudio . Please review this previously published article to make sure that there's not too much overlap before continuing with your draft - https://www.section.io/engineering-education/build-an-outlook-clone-using-react-hooks/

**Comment by ReactifyStudio** [comment]
Just teaching the core hooks not a project based unlike that one

**Comment by ReactifyStudio** [comment]
I can't see the overlap

**Comment by ReactifyStudio** [comment]
Thanks, I'm really convinced it overlaps
