### ISSUE TITLE
An Overview of Fuzzy Logic System

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#885]
### Brief Summary: 
Fuzzy logic is a computing technique that is based on the degree of truth. It is applied in various industries such as finance, manufacturing and automobile. This article provides readers with a basic understanding of a fuzzy logic system. 

### Key Takeaways: 
1. What is a fuzzy logic?
2. Fuzzy logic architecture
3. Using Fozzy logic (algorithm)
4. Fuzzy logic membership function
5. Applications of fuzzy logic
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
