### ISSUE TITLE
10 Powerful Business Intelligence Tools for Data Analysts

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#886]
### Brief Summary: 
Business intelligent tools enable businesses to visualize and analyze data for effective strategic planning. This article analyzes top ten business intelligent tools that can enable businesses to achieve growth. 

### Key Takeaways: 
1. Introduction to business intelligence
2. Why business intelligent tools are important
3. Top 10 business intelligent tools for data analysts
4. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved. Please note that there is a typo in your title/summary; it should be 'business intelligence tools'
