### ISSUE TITLE
An Overview of Meta-Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#888]
### Brief Summary: 

The application of machine learning to real-world problems is such an involving task for data scientists. For instance, they need to assess algorithms and tune many parameters. This may be based on their experience, biases, or assumptions. To automate this process, machine learning may be used to learn the most suitable parameters and algorithms for a given task. Meta-learning is used to achieve this automation. 

### Key Takeaways: 

The reader should:
1. Get an introduction to Meta-Learning
2. Understand the steps involved in Meta-Learning
3. Learn the types of Meta-Learning Algorithms

### References: 

https://medium.com/datathings/meta-modelling-meta-learning-34734cd7451b

https://lilianweng.github.io/lil-log/2018/11/30/meta-learning.html

https://hub.packtpub.com/what-is-meta-learning/

https://robotronblog.com/2017/10/25/what-is-meta-learning-in-machine-learning/

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
