### ISSUE TITLE
Threading in WorkManager

### ISSUE THREAD

**Issue by LinusMuema** [section-io/engineering-education#891]
### Brief Summary: 
WorkManager manages threads automatically for the developer. But it is a useful skill to understand threading in these cases and how coroutines/RxJava handles threads too. This article aims to help the user get a basic understanding of threading in background work and how to use the two asynchronous libraries.

### Key Takeaways: 
1. How WorkManager handles threading
2. Using coroutines in WorkManager
3. Using RxJava in WorkManager
4. The difference in thread management of the libraries

### References: 
[WorkManager in Android](/engineering-education/android-workmanager)

**Comment by ninjaginja** [comment]
good topic @LinusMuema - approved
