### ISSUE TITLE
Introduction to friend functions in C++

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#892]
### Brief Summary: 
A non-member function cannot have access to the private data of a class. However, there could be a situation where we would like two classes to share a particular function. C++ allows the common function made friendly with both the classes, thereby allowing the function to have access to the private data of these classes. in this article, we will take a look at how to make a non-member function friend to a class.

### Key Takeaways: 
1. What are friend functions
2. Friend function declaration
3. Examples of friend functions

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @Dawe-7 - approved
