### ISSUE TITLE
Reproduciblity to Improve Machine Learning

### ISSUE THREAD

**Issue by collins-a** [section-io/engineering-education#894]
### Brief Summary: 

Reproducibility in machine learning involves getting the same results, using the same algorithm, data, and parameters on every run. It helps to remove variations when rerunning experiments, which helps in refining the models. Reproducing results in machine learning projects can be very difficult. It may even be impossible in some cases. We explore the most important concepts of reproducibility in this article. 

### Key Takeaways: 

Reader should:
1. Get an introduction to the concepts of reproducible ML
2. Learn the significances of reproducibility in ML 
3. Understand the challenges to attaining reproducible ML
4. Be aware of basic measures to attain reproducibility 

### References: 

https://towardsdatascience.com/reproducible-machine-learning-cf1841606805#:~:text=%20Reproducible%20Machine%20Learning%20%201%20A%20step,authors%20use%20non-parametric%20Mann%E2%80%93Whitney%20U%20test...%20More%20

https://suneeta-mall.github.io/2019/12/21/Reproducible-ml-research-n-industry.html

https://determined.ai/blog/reproducibility-in-ml/

https://machinelearningmastery.com/reproducible-machine-learning-results-by-default/

https://blog.dominodatalab.com/machine-learning-reproducibility-crisis/

**Comment by ninjaginja** [comment]
good topic @collins-a - approved
