### ISSUE TITLE
Creating a Todo progressive web app with ReactJS

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#895]
### Brief Summary: 
A progressive web application is a type of application software delivered through the web, built using common web technologies including HTML, CSS and JavaScript. It is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices.This tutorial aims to build a simple To-do application with React using this technology.

### Key Takeaways: 
1.React introduction
2.Building Progressive web apps
### References: 
https://reactjs.org/

**Comment by ninjaginja** [comment]
good topic @ReactifyStudio  - please be sure that you use the proper reference for React (no JS on the end) throughout your content. You're good to proceed with this topic.
