### ISSUE TITLE
History of C++

### ISSUE THREAD

**Issue by joshjwelsh** [section-io/engineering-education#897]
### Brief Summary: 
C++ has remained one of the most used and loved languages for the past 35 years. Being one of the oldest language still in active use is a massive achievement and this success lies in its long and impressive history. 

### Key Takeaways: 
1) Who was the founder of C++ and what were his inspirations? 
2) What were the guiding principles of C++? 
3) What are the major versions of C++?

### References: 
https://www.youtube.com/watch?v=uTxRF5ag27A&t=5176s
https://en.wikipedia.org/wiki/C%2B%2B11
https://en.wikipedia.org/wiki/C%2B%2B03
https://www.cplusplus.com/info/history/
https://en.wikipedia.org/wiki/C%2B%2B

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @joshjwelsh, however we're steering away from overly generalized content and prefer more targeted topics that hone in on addressing specific developer challenges. With that in mind, please feel free to suggest another topic.
