### ISSUE TITLE
How to build a CRUD API using Deno and MongoDB

### ISSUE THREAD

**Issue by ReactifyStudio** [section-io/engineering-education#898]
### Brief Summary: 
Deno is a  secure runtime for JavaScript that supports and configures TypeScript out of the box. MongoDB is a cross-platform document-oriented database. In this article, we will learn how to build a CRUD application in Deno and using MongoDB as the database layer.
### Key Takeaways: 
1. Introduction to Deno
2. Using Postman API client
3. Introducing MongoDB and mongoose

### References: 
N/A

**Comment by ninjaginja** [comment]
@ReactifyStudio Please hold off on suggesting new topics until you've seen an article through from start to finish. I'm going to close this issue for now, and you can request to reopen when we've reached that point. Thank you!
