### ISSUE TITLE
Introduction to Solid Principle

### ISSUE THREAD

**Issue by corpsgeek** [section-io/engineering-education#903]
### Brief Summary: 
The solid principle is an object-oriented programming design principle intended to make software designs more understandable, flexible, and maintainable. This article will be non-language specific to ensure readers truly understand the concept. 

### Key Takeaways: 
- What solid principle is
- How to implement solid principle
- The differences between concrete classes and interfaces in solid principle
- How to write clean and extensible code using solid principle

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @corpsgeek  - approved
