### ISSUE TITLE
Introduction to Oracle DBMS and Python  

### ISSUE THREAD

**Issue by joshjwelsh** [section-io/engineering-education#910]
### Brief Summary: 
Use python to connect to an oracle DBMS system. Learn how to use cursor to execute SQL commands through python.

### Key Takeaways: 
1) Connect to DBMS
2) Executing SQL commands
3) Display results using Pandas 

### References: 
NA

**Comment by ninjaginja** [comment]
@joshjwelsh I suspect that your tutorial series will take a bit of time to work through. We prefer to keep the open issues list reflective of content that is actively being worked on. I'm going to close this issue until you've worked through the other content, and we can re-open when ready.
