### ISSUE TITLE
The Best Continuous Integration and Continuous Delivery Tools.

### ISSUE THREAD

**Issue by corpsgeek** [section-io/engineering-education#911]
### Brief Summary: 
Continuous Integration is a method of software engineering that merges all the activities of developers in an environment. It is designed to provide feedback on any bug found in the
codebase and ensure they are corrected without delay.

### Key Takeaways: 
- What is CI/CD
- Why use CI/CD tools
- Top 10 CI/CD tools and their features, pros and cons, popularity and pricing, and getting started with them.

### References: 
- CI/CD Tools docs

**Comment by ninjaginja** [comment]
@corpsgeek Thanks for the topic suggestion. We try to keep open issues reflective of the content that is actively being worked on. I see that you've submitted another topic idea prior to this one today. Could you please work through that one first, then we can reopen this one when ready?
