### ISSUE TITLE
The Best CI/CD Tools

### ISSUE THREAD

**Issue by corpsgeek** [section-io/engineering-education#912]
### Brief Summary: 
Continuous Integration is a method of software engineering that merges all the activities of
developers in an environment. It is designed to provide feedback on any bug found in the
codebase and ensure they are corrected without delay.

### Key Takeaways: 
- What CI/CD is
- Why use CI/CD
- Top 10 CI/CD Tools and their features

### References: 
- CI/CD Tools docs

**Comment by ninjaginja** [comment]
@corpsgeek I'm a bit confused as to why you opened a new issue here. Per my comment on #911, we'd prefer that you work through your previously submitted topic (#903) prior to suggesting a new topic. This allows us to get articles from start to finish faster, which expedites payouts for everyone. This topic will be fine to start once you have submitted a draft for your other article. We just prefer to keep the open issue list clean. You may request to reopen this once you are ready to begin working on this draft.

**Comment by corpsgeek** [comment]
oh alright, I was surprised the issue was closed, didn't read the comment. Thank you @ninjaginja
