### ISSUE TITLE
How to execute Unix commands in Python

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#916]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Linux is one of the most popular operating systems used by software developers. Most servers and VMs in the cloud run on Linux based operating systems. Therefore, it will be very helpful for software engineers to be able to execute Linux commands through programming languages. Fortunately, Python has a rich set of libraries that allow us to do so, and in this tutorial, I will explore this in-depth.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand why it is essential to run and execute Linux commands
2. Explore python libraries that allow us to execute Linux commands
3. Understand how this is done by building applications for various use cases

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
great topic @adithbharadwaj - approved
