### ISSUE TITLE
Aggregation in Database Management Systems (DBMS)

### ISSUE THREAD

**Issue by mbaabuones** [section-io/engineering-education#918]
### Brief Summary: 
Aggregation refers to the process by which entities are combined to form a single meaningful entity. This article provides an overview of aggregation in DBMS, a software package that supports data management in organizations. 

### Key Takeaways: 
1. Introduction to DBMS
2. What is Aggregation in DBMS?
3. Reasons for using aggregation in DBMS
4. Process flow for aggregation in DBMS
5. Example of aggregation in DBMS
6. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
good topic @mbaabuones - approved
