### ISSUE TITLE
Understanding Access Control Systems 

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#921]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Consumers interact with electronic access control systems every day. When we think of access control systems, the first thing that comes to mind is often the remote key, keypad, or key card used to enter an office, car, or home. But what exactly are access control systems?
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What are Electronic Access Control Systems?
2. Types of access control systems and how they work: 
         
- Role-Based Access Control (RBAC)
- Discretionary Access Control (DAC
-  Mandatory Access Control (MAC)

3. Latest technology in access control systems 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @EKahuha. This is on the fringe of our preferred topic areas. We're really looking for content that digs deeper into web-based technologies. I'd like to request that you select a different topic area to explore.
