### ISSUE TITLE
How to Protect your System against Ransomware as a Service (RaaS)

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#922]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Ransomware-as-a-Service (RaaS) borrows from the Software-as-a-Service (SaaS) model. This subscription-based malicious model enables even the novice cybercriminal to launch ransomware attacks without much difficulty. It is therefore important to protect systems against this ransomware. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is Ransomware-as-a-Service (RaaS)?
2. How does it function?
3. Protecting against ransomware as a service

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @EKahuha - approved
