### ISSUE TITLE
Variables, Data Types and Control Statements in C# 

### ISSUE THREAD

**Issue by Jeff-mwangi** [section-io/engineering-education#930]
### Brief Summary: 
Variables are one of the key basics in C# programming. They are names of a memory space or location that stores a value of a data type. We declare variables in C# using keywords such as int, char, string, double, or bool. This makes it fundamental for any individual inspired by C# programming to learn how to use variables.

### Key Takeaways: 
By the end of this tutorial the reader will be able to:
- Declare variables
- Initialize variables
- Understand the various types of variables
- Use variables in C#
- Add two variables
### References: 
N/A

**Comment by ninjaginja** [comment]
@Jeff-mwangi could you elaborate on the unique spin that you intend to take on this content, to differentiate it from what is already readily available through docs?

**Comment by Jeff-mwangi** [comment]
@ninjaginja , I will also cover on data types in C# as many programmers confuse between the two basic concepts.

**Comment by Jeff-mwangi** [comment]
@ninjaginja , I will also cover on Control statements in C#. There are four types of control statements in C# (Decision making statements,iteration statements,selection statements,jump statements) we will look at each of them.
The reader should be able to determine when and where to use each control statement.

**Comment by ninjaginja** [comment]
ok, please be sure to adjust your title so it is specific to the primary challenge your content addresses.

**Comment by Jeff-mwangi** [comment]
@ninjaginja , i have updated my title

**Comment by ninjaginja** [comment]
great, thank you @Jeff-mwangi. Minor corrections: 'Variables, Data Types and Control Statements in C#' (spacing and capitalization)
