### ISSUE TITLE
Blockchain is going to change our lives.

### ISSUE THREAD

**Issue by murageB** [section-io/engineering-education#936]
### Brief Summary: Blockchain is going to change our lives.

Some would say that blockchain is the next big revolutionary technology, bigger than the internet itself and to be honest, they would be right.

This is due to the numerous use cases of blockchain protocols and their ability to affect virtually every aspect of our lives.

In this article, I choose to focus on government-managed services and how blockchain could be used to streamline and improve said services and build trust with its citizens. 

### Key Takeaways:

I want my reader to leave with a basic understanding of blockchain.

My reader should be able to site a few cases uses of blockchain and how it can improve their lives.

They should be able to see how diverse the use cases are and possibly even think of possible use cases of their own.

### References:

[https://settlemint.com/government-blockchain-use-cases/](https://settlemint.com/government-blockchain-use-cases/)

[https://settlemint.com/healthcare-blockchain-use-caseshealthcare/](https://settlemint.com/healthcare-blockchain-use-caseshealthcare/)

[https://www.researchgate.net/publication/325493742_Blockchain_for_government_services_-_Use_cases_security_benefits_and_challenges](https://www.researchgate.net/publication/325493742_Blockchain_for_government_services_-_Use_cases_security_benefits_and_challenges)

[https://www.boozallen.com/s/insight/blog/3-potential-benefits-of-government-blockchain.html#:~:text=Public sector blockchain can build trust%2C protect data%2C and reduce costs&text=Excitement around the technology is, secure data sharing%2C and more](https://www.boozallen.com/s/insight/blog/3-potential-benefits-of-government-blockchain.html#:~:text=Public%20sector%20blockchain%20can%20build%20trust%2C%20protect%20data%2C%20and%20reduce%20costs&text=Excitement%20around%20the%20technology%20is,secure%20data%20sharing%2C%20and%20more).

**Comment by ninjaginja** [comment]
@murageB, we've already got several published articles on the foundations of blockchain, including one article that focuses specifically on healthcare use cases. We try to prevent too much overlap across content. Please take a look at the published article library and let me know if you'd like to propose a more differentiated approach to this content, or alternatively, you may choose to explore a different topic area.

**Comment by murageB** [comment]
Thank you for your reply. So I had already taken a look at that, the article that focused on specifically on the health care use case and I do understand why you would raise an issue. However, my article is aimed at exploring several use cases of blockchain and bringing to light the potential of blockchain. I have entirely avoided the healthcare use case so as to avoid redundancies. Pleaserecoincider and I hope to hear from you soon.

**Comment by murageB** [comment]
Thank you for your reply. So I had already taken a look at that, the article that focused on specifically on the health care use case and I do understand why you would raise an issue. However, my article is aimed at exploring several use cases of blockchain and bringing to light the potential of blockchain. I have entirely avoided the healthcare use case so as to avoid redundancies. Please reconsider and I hope to hear from you soon.

**Comment by ninjaginja** [comment]
Thank you for the expanded explanation @murageB, but I still think that the topic, as you've described it, is far too broad/general. We're more interested in publishing content that take's a practitioner's approach to addressing challenges that engineers face. Please take guidance from the list of published articles and accepted topics. Thank you.
