### ISSUE TITLE
Express Server for Agora Cloud Recording Query and Update

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#940]
## Brief Summary

This is a follow-up article. Readers will have to go through the previous article to set up cloud recording and the express server.

This tutorial will focus on the additional features of the Agora cloud recording component and how to implement it on the express server built in the previous tutorial.

## Key Takeaways

- Quering the recording session.
- Updating the subscription list.
- Updating the recording layout.

Previous Article #859.

**Comment by ninjaginja** [comment]
Sounds like a good follow-up article @zolomohan. Please be sure that your title is reflective of the specific takeaway/learnings that the reader can expect (vs. simply stating 'Pt.2').

**Comment by zolomohan** [comment]
@ninjaginja, is this title okay?

**Comment by zolomohan** [comment]
@ninjaginja, updated the title.

**Comment by ninjaginja** [comment]
great, thank you!
