### ISSUE TITLE
Getting started with MATLAB

### ISSUE THREAD

**Issue by ahmadmardeni1** [section-io/engineering-education#947]
### Brief Summary: 
MATLAB (an abbreviation of "matrix laboratory") is a proprietary multi-paradigm programming language and numerical computing environment developed by MathWorks. MATLAB allows matrix manipulations, plotting of functions and data, implementation of algorithms, creation of user interfaces, and interfacing with programs written in other languages.

Although MATLAB is intended primarily for numerical computing, an optional toolbox uses the MuPAD symbolic engine allowing access to symbolic computing abilities. An additional package, Simulink, adds graphical multi-domain simulation and model-based design for dynamic and embedded systems.

### Key Takeaways: 
- What is MatLab and what we can do with it.
-  Vectors and matrices.
- Graphics - 2D Plots.
- Script and function files (M-files).
- Flow control (if, while, for).
- practical examples of Sin and Cos wave.

(Maybe I will create a second part for plotting)
### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @ahmadmardeni1 - approved
