### ISSUE TITLE
User Experience Process Explained.

### ISSUE THREAD

**Issue by bluemutheu** [section-io/engineering-education#950]
### Brief Summary: 
User experience has become a major necessity in the world of product design. The article will explain what process we undertake during UX design to come up with a user-friendly product. The article will also give tools used by UX designers to see the UX process to success. It will highlight the modern and best UX design practices.

### Key Takeaways: 
1. What is UX design.
2. Process and Methodology of UX design.
3. Best UX design practices.
4. Tools for a UX designer.

### References: 
N/A

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @bluemutheu. This is a very broad topic and we generally prefer more targeted subject matters that aim to address a specific developer challenge with a practitioner's approach. I'd suggest trying to think of a more specific, concrete topic to explore.
