### ISSUE TITLE
10 Customer Relationship Management (CRM) Tools for Business Analytics

### ISSUE THREAD

**Issue by skay-ai** [section-io/engineering-education#957]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

CRM is a strategy that results in increased profits for a business.  CRM Tools helps businesses build a relationship with their existing customers that, in turn, create loyalty and customer retention.

Table of Content:
- Introduction to Customer Relationship Tool (CRM)
- How CRM Tools help the businesses to grow?
- Benefits of CRM Tools
- 10 popular CRM Tools for Business Analytics
- Conclusion

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- Reader will understand the importance of CRM and CRM Tools
- How CRM will help in developing, managing and maintaining a profitable relationship with the customers.
- Reader will understand Features and Benefits of various CRM Tools

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

- https://www.softwaretestinghelp.com
- https://www.mastersindatascience.org
- https://www.hubspot.com

**Comment by ninjaginja** [comment]
Thanks for the topic suggestion @skay-ai. However, this is outside of our preferred topic areas. We're looking for content that aims to address specific developer challenges with real examples and a practitioner's approach. Please take a look at other approved topics and previously published articles to get a getter idea of the type of content that we publish and feel free to suggest a new topic.

**Comment by skay-ai** [comment]
Thank you for your prompt response

I am a new contributor.  Though this issue is closed, I have raised a
question here, just for my clarification.  While I was going thro'
previously approved topics, I saw issue number #886, where I found a
similar contribution was uploaded.

I would appreciate if you could clarify.

Thanks in advance.

With regards,

SKAY-AI

**Comment by ninjaginja** [comment]
Thanks for the clarifying question @skay-ai. So, the difference between the accepted issue that you pointed out and your suggested topic area is that business intelligence tools are within the data science field (a topic that we actively cover), whereas CRM tools are more closely related to sales and marketing. We're looking for content that takes a deep dive into web technologies (from a computer science perspective), not philosophical pieces that are more on the surface of the benefits that specific technologies might bring. I hope this is helpful.
