### ISSUE TITLE
Building local unit tests in android-kotlin

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#958]
### Brief Summary: 
Unit testing is a key feature in software development. It also brings about a development paradigm known as Test-Driven Development.
Local unit tests are used to test the business logic of applications. This article goes through implementing local unit tests in android applications using the `Truth` library in conjunction with `JUnit4`.

### Key Takeaways: 
1. The reader will understand what test-driven development is.
2. The reader will understand how to write local unit tests in android.
3. The reader will learn how to run tests in android studio.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @kayere - approved.
