### ISSUE TITLE
Automating UI tests in android

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#959]
### Brief Summary: 
Other than testing the business logic of applications. Android developers also need to write tests that ensure their User interface works as expected.
This article goes through writing these tests using the `Espresso` framework.

### Key Takeaways: 
1. The reader will learn how to write UI tests.
2. The reader will understand the benefits of automating UI tests.
3. The reader will understand how to use the `Espresso` framework to write UI tests.

### References: 
N/A

**Comment by ninjaginja** [comment]
good topic @kayere - approved. My only suggestion would be to add 'Espresso' into the title - 'Automating UI Tests in Android with the Espresso Framework'

**Comment by kayere** [comment]
Noted
