### ISSUE TITLE
Introduction to recursion

### ISSUE THREAD

**Issue by adithbharadwaj** [section-io/engineering-education#963]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Recursion is a very popular class of algorithms used to solve numerous problems in computer science. However, it is sometimes hard to fully understand and use recursion to solve algorithmic problems. In this tutorial, I will make recursion easy to understand along with code examples for problems involving recursion. We will use recursion to solve common problems asked in coding interviews.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand the theory behind recursion and how it works
2. Solve algorithmic problems using recursion and recursive functions
3. Understand the limitations of recursion and its pros and cons
4. How to handle recursion limits in languages like Python

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
great topic @adithbharadwaj - approved
