### ISSUE TITLE
Building an Express Server to Capture Agora Cloud Screenshots

### ISSUE THREAD

**Issue by zolomohan** [section-io/engineering-education#968]
## Brief Summary

In this tutorial, we will be going over how to capture screenshots of the streams happening in your applications if you are using the Agora SDKs for real-time engagement like Video Conferences, Video Calls, or Live Broadcasts.

We will be building an Express server that will act as an interface between your client application and the Agora APIs.

**Comment by ninjaginja** [comment]
good topic @zolomohan - approved. Just one minor suggestion for the title: 'Building an Express Server to Capture Agora Cloud Screenshots' (?) ... does this more accurately capture the takeaway for the reader?

**Comment by zolomohan** [comment]
That's much better. Thanks, @ninjaginja.
