### ISSUE TITLE
How to use Streamlit to build a UI for ML Models

### ISSUE THREAD

**Issue by rahulbanerjee26** [section-io/engineering-education#973]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
How to build a simple UI for a Machine Learning Model using Python and Streamlit. Streamlit is a Python library and really useful to build a web app for ML Models. You do not need to use HTML or CSS. Beginner level Python Knowledge is sufficient

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Reader should understand the basics of Streamlit
- Reader should be able to know how to setup Streamlit
-  Reader should be able to build UI Components using Streamlit

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://www.streamlit.io/

**Comment by ninjaginja** [comment]
great topic @rahulbanerjee26 - approved
