### ISSUE TITLE
Choosing between Modern Data Warehouses: BigQuery vs Redshift vs Snowflake

### ISSUE THREAD

**Issue by EKahuha** [section-io/engineering-education#976]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Most of the modern data warehouse solutions are designed to work with raw data. They allow you to re-transform data on the fly without a need to re-ingest your data stored in a warehouse.

Knowing which data warehouse is right for you can be a challenge. This article three modern data warehouses BigQuery, Redshift, and Snowflake.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

- What is BigQuery, Redshift, and Snowflake? 

- A comparison of BigQuery, Redshift, and Snowflake in terms of : 

1. Security
2. Scalability: horizontally vs. vertically
3. Support and maintenance
4. Architecture 
5. Data Volume

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
great topic @EKahuha - approved
