### ISSUE TITLE
The Evolution of Resource Sharing Technologies over the Internet

### ISSUE THREAD

**Issue by KiokoM** [section-io/engineering-education#977]
### Brief Summary: 
We take a look at the different technologies that have been used over the years to help with resource sharing over the internet or intranet.

### Key Takeaways: 
- Background of different web technologies used from COBRA, DCOM, Java RMI, and Web Services (SOAP and Rest)
- An in-depth look into SOAP and REST web services and best application for each
- Look into the REST architectural principles

### References: 
N/A

**Comment by KiokoM** [comment]
@ninjaginja  How does "Web Technologies for Resource Sharing" sound?

**Comment by ninjaginja** [comment]
That still sounds very vague. What, specifically, can readers expect to gain? Is it an understanding of the origins of web technologies for resource sharing over the Internet? Or, are you really focusing in on breaking down SOAP and REST web services? The title should be very specific to the outcome.

**Comment by KiokoM** [comment]
I'm thinking of diving into the origins of web technologies and finishing off where they are at as of now.

**Comment by KiokoM** [comment]
"Origins and Growth of Web Technologies"?

**Comment by ninjaginja** [comment]
'Web technologies' is far more expansive than just resource sharing technologies... perhaps something like 'The Evolution of Resource Sharing Technologies Over the Internet'?

**Comment by KiokoM** [comment]
I see your point, using 'Web' opens a huge door in terms of what can be covered. I'll use your suggestion for the topic header. Thank you
