### ISSUE TITLE
Web Frameworks

### ISSUE THREAD

**Issue by KiokoM** [section-io/engineering-education#978]
### Brief Summary: 
We look into the different frameworks used in web development from CSS, Front-end, and back-end frameworks used.

### Key Takeaways: 
- Introduction to web frameworks
- Look into CSS Frameworks, Front-end Javascript Frameworks, and back-end frameworks
- For the back-end, we will do a shallow dive on Django and express

### References: 
N/A

**Comment by ninjaginja** [comment]
This topic seems far too broad @KiokoM. We've had lots of articles cover different across the takeaways that you've defined. We're looking for in-depth content on specific challenges that developers are looking to solve. Please select a narrower focus area to suggest.
