### ISSUE TITLE
Big O Notation

### ISSUE THREAD

**Issue by Agusioma** [section-io/engineering-education#981]
### Brief Summary: 
The article contains analysis of performance of our algorithms using the Big O notation.
It majorly talks about how code writers should not write what 'works' but what works efficiently.
Python is used for illustrations.

### Key Takeaways: 

1. What is Big O notation.
2. Some commonly used Big O notations.
3. Estimating one's code using Big O.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

[Towards Data Science](https://towarsddatascience.com/the-fundamentals-of-the-big-o-notation-7fe14210b675)

**Comment by ninjaginja** [comment]
good topic @Agusioma - approved. Before you submit your final draft for review, please be sure that you put it through a thorough grammar/readability check. I noticed a few strange word choices in your summary, and want to be sure that we maximize your opportunity for a full payout. We do not provide editing services.

**Comment by Agusioma** [comment]
Thank you
