### ISSUE TITLE
Understanding Network Routing

### ISSUE THREAD

**Issue by Agusioma** [section-io/engineering-education#982]
### Brief Summary: 
We discuss how network routers find paths from origins, like  data centers, to destinations in a network using various algorithms and protocols.

### Key Takeaways: 

1. What is routing.
2. Types of routing.
3. Brief understanding of pathfinding algorithms such as the Dijkstra's algorithm.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @Agusioma - approved. As a bit of advice, we suggest working through a single article from start to finish before suggesting new topics. This allows you to incorporate any and all feedback into future articles and enables us to expedite reviews/payouts for everyone.

**Comment by Agusioma** [comment]
Thank you
