### ISSUE TITLE
CSS Frameworks

### ISSUE THREAD

**Issue by KiokoM** [section-io/engineering-education#983]
### Brief Summary: 
Looks at the different frameworks and libraries used in CSS in website design and break them down in terms of their use.

### Key Takeaways: 
- Looks into the different frameworks that are used in CSS (Bootstrap, Semantic, materialize, and tailwind)
- Takes a look at the pros and cons of these frameworks
- Have a comparison among for best fit in web development

### References: 
- [Bootstrap](https://getbootstrap.com/)
- [Semantic](https://semantic-ui.com/)
- [Materialize](https://materializecss.com/)
- [Tailwind](https://tailwindcss.com/)

**Comment by ninjaginja** [comment]
@KiokoM We're trying to encourage authors to see articles through from suggestion to final draft before submitting new article ideas. This allows you to better incorporate feedback from the review process into future articles while also allowing us to expedite payouts for all. I'm going to close this issue for now, and you can request to reopen once you've worked through your other article.
