### ISSUE TITLE
How to implement Capsule Networks using TensorFlow and the Keras API

### ISSUE THREAD

**Issue by Bayler** [section-io/engineering-education#986]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

A CapsNet consists of capsules instead of neurons in its architecture. Unlike neurons, that outputs scalars with no direction, capsules outputs vectors that have a direction.

This is a follow-up article from my previous article on Capsule Networks (https://www.section.io/engineering-education/capsule-networks-an-enhancement-to-convolution-neural-networks/). The article demonstrates how to implement Capsule Networks in code.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

In this article, you will learn how to implement Capsule Networks (CapsNet) using:
1. Tensorflow
2. Keras API
3. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. https://www.section.io/engineering-education/capsule-networks-an-enhancement-to-convolution-neural-networks/

**Comment by ninjaginja** [comment]
great follow-up content @Bayler  - approved
