### ISSUE TITLE
Getting started with classes and objects in C++

### ISSUE THREAD

**Issue by Dawe-7** [section-io/engineering-education#992]
### Brief Summary: 
C++ is one of the Object-oriented programming (OOP) language. The limitations of C language are evident when a software project is too large to be handled. This problem was addressed by adding several extensions to the C language. The most important addition was the concept of class. In this article, we will take a look at classes and objects in depth.

### Key Takeaways: 
By the end of this tutorial, the reader will be able to:
1. Know what a class and object is
2. Create a class
3. Create objects
4. Use objects as function arguments

### References: 
N/A

**Comment by ninjaginja** [comment]
@Dawe-7, we've got several published articles that span across these topics, but I don't think we have an article that explicitly serves as a getting started guide. I think it's ok to go ahead and proceed, but please take a look at the previously published articles (you can do a simple search on 'C++') and be mindful of overlap.

**Comment by Dawe-7** [comment]
Okay, I will make sure of that.
