### ISSUE TITLE
Creating a Django Hello World App Using PostgreSQL Database

### ISSUE THREAD

**Issue by atoyegbe** [section-io/engineering-education#995]
### Brief Summary: 
we discuss what is Django web framework, how to install and get our Django app working.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- How to create a virtual environment for our Django project.
- Installing and creating our first Django Project
- Using Django Templates
### References: 
https://www.djangoproject.com

**Comment by ninjaginja** [comment]
good topic @atoyegbe, but could you please elaborate on what additional value or unique angle you intend to deliver to readers beyond what's already available in the getting started guides that are available through the documentation (https://docs.djangoproject.com/en/3.1/intro/tutorial01/)?

**Comment by atoyegbe** [comment]
I Will be showing, How to set up PostgreSQL Database in Django.
The article will center around setting up a Django Project with PostgreSQL Database.

**Comment by ninjaginja** [comment]
ok, great. Could you please make sure that the title reflects that?

**Comment by atoyegbe** [comment]
Done. Is that okay?

**Comment by ninjaginja** [comment]
I'd suggest shortening a bit to 'Creating a Django Hello World App Using PostgreSQL Database'

**Comment by atoyegbe** [comment]
Done Thanks.

**Comment by atoyegbe** [comment]
@ninjaginja can i work on it now?

**Comment by ninjaginja** [comment]
yep, good to go 👍
