### ISSUE TITLE
Introduction to Microservices Using Spring and Eureka

### ISSUE THREAD

**Issue by john-amiscaray** [section-io/engineering-education#999]
### Brief Summary: 
This article is an introduction to the microservice architecture along with a practical implementation using Spring and Eureka.
It will first cover the theory behind microservice architecture such as its advantages over the traditional monolithic approach, how microservices communicate with each other and the client, and some terminology. Then that knowledge will be used to create a simple application using Spring and Eureka that implements microservices.

### Key Takeaways: 
- What are microservices?
- What are the advantages and disadvantages of developing in this style?
- What is service discovery?
- How to create a simple application using Spring and Eureka that uses microservices.

### References: 
https://www.n-ix.com/microservices-vs-monolith-which-architecture-best-choice-your-business/

**Comment by ninjaginja** [comment]
really great topic @john-amiscaray  - approved 👍
